### ISSUE TITLE
Option to limit RAM usage per instance

### ISSUE THREAD

**Issue by Dr01000111** [BedrockLauncher/BedrockLauncher#103]
Add an option in the bedrock launcher to customize the maximum amount of ram Minecraft can use

**Comment by TresAbhi** [comment]
@CarJem, is this even possible in the first place?

**Comment by ambiennt** [comment]
UWP apps already use ram as needed so theres no benefit in allocating more if that were to be possible. And why would you want to limit your ram, the game isn't contained in a VM

**Comment by CarJem** [comment]
Yeah, this here doesn't seem very plausable

**Comment by NT690** [comment]
https://superuser.com/questions/1263090/is-it-possible-to-limit-the-memory-usage-of-a-particular-process-on-windows might be of use.
