### ISSUE TITLE
problema no acesso a o manicraft gratis

### ISSUE THREAD

**Issue by WDKM** [BedrockLauncher/BedrockLauncher#105]
A o eu entra eu me deparo com o manicraft versão paga,
e pelo que eu vejo em vídeos e tutoriais isso não acontecia com nenhum dos canais

**Comment by TresAbhi** [comment]
You have to own a version of Minecraft prior to using bedrock launcher. **This is not a tool for piracy**.

Google translation:
> Debes tener una versión de Minecraft antes de usar el lanzador de Bedrock. **Esta no es una herramienta para la piratería**.
