### ISSUE TITLE
Launcher fails to fetch `CefSharp.Core.Runtime.dll`

### ISSUE THREAD

**Issue by FrosticeYT** [BedrockLauncher/BedrockLauncher#109]
![image](https://user-images.githubusercontent.com/90916297/144708466-355b7c75-a095-438d-86a0-e8c7e17a442a.png)

**Comment by NT690** [comment]
Wouldn't this be a duplicate of #84? Or is there a difference between the two.

**Comment by Rayth** [comment]
yep it's a duplicate
