### ISSUE TITLE
Launcher breaking Microsoft Store apps

### ISSUE THREAD

**Issue by ThatsAnotherJ** [BedrockLauncher/BedrockLauncher#110]
Ever since I started using the Launcher it's been breaking all my MS Store apps. I tried to uninstall the Launcher but it just wouldn't uninstall. I tried uninstalling Minecraft Bedrock itself and then the uninstall failed. I also tried uninstalled the MS Store Java Launcher and that failed too. I'm believed to think it's the Launcher because everything has been fine before this.

**Comment by ThatsAnotherJ** [comment]
Also, Minecraft Bedrock and the Java Launcher are not launching

**Comment by Rayth** [comment]
> Ever since I started using the Launcher it's been breaking all my MS Store apps. I tried to uninstall the Launcher but it just wouldn't uninstall. I tried uninstalling Minecraft Bedrock itself and then the uninstall failed. I also tried uninstalled the MS Store Java Launcher and that failed too. I'm believed to think it's the Launcher because everything has been fine before this.

This sounds more like your store is bugged than a launcher problem seeing as we've had no previous issues reported about this. I personally use this launcher to update my bedrock edition and have used the store for other apps without any issues. I've also had 0 issues manually uninstalling minecraft or any other app inside settings.



> Also, Minecraft Bedrock and the Java Launcher are not launching

Can you elaborate?

**Comment by TresAbhi** [comment]
Please try to provide more information in one or more of the following ways:
- Record footage of the various issues in action
- Provide error logs of the launcher
- Elaborate more on the issues with steps to reproduce the issue
- Differentiate issues with your machine alone and Bedrock Launcher
