### ISSUE TITLE
Download file can't open

### ISSUE THREAD

**Issue by Sly-Moose** [BedrockLauncher/BedrockLauncher#111]
![Screenshot_20211205-104257](https://user-images.githubusercontent.com/95586899/144759629-25b848af-b8b7-4e6f-a063-2c1f6e7d96ee.png)
This is all I'm getting after tapping on the file. Those are just drawing apps on my tablet, and trying to open the file with the drawing apps just leads me to the drawing apps to simply draw. Nothing else happens. I feel like I don't know what I'm suppose to be doing.

**Comment by Rayth** [comment]
This is a windows application, you can't use it on android/ios.
