### ISSUE TITLE
Uninstalling version takes forever

### ISSUE THREAD

**Issue by chino** [BedrockLauncher/BedrockLauncher#113]
Trying to run uninstall causes the icon to rotate but never shows a dialog.  After that the entry is still left in the application list and never goes away.  The install directory still exists with a lot of files in it as well and clicking the uninstaller.exe in there doesn't do anything either.  I tried to reinstalled it again to give it another try but same thing happened.  Not sure what other info I could give but please let me know as I'd like to cleanup the system properly.

**Comment by chino** [comment]
Is there a specific log file for the uninstall process?  I see a `Log.txt` under `Program Files -> Launcher`  but it's basically empty.

**Comment by TresAbhi** [comment]
Yeah, that's the log. Re-run the app up until the issue happens, and then open `Log.txt`.

**Comment by chino** [comment]
Well, I run the uninstaller, it just spins the mouse, nothing happens, then the log just has:

```
Application Starting...
Application Pre-Initalization Finished!
Checking for updates
Current tag: 0.0.2.0
Latest tag: 0.0.1.8
```

**Comment by TresAbhi** [comment]
You seem to be on an older version, please update the launcher and then try to see if it's still an issue

**Comment by chino** [comment]
That's strange?  All I did was go to https://bedrocklauncher.github.io/ and download from that link?

Doing that again it creates a Log.txt in the Downloads folder which now says `0.0.2.1`.

Also after the installation finished there is a Log.txt under program files that looks like the previous contents with the old version numbers even though I deleted the folder entirely and never ran it yet.  So perhaps that file is just accidently in the installer by accident?

After running the actual program then the same Log.txt under program files updates to say `0.0.2.1`.

Running the uninstaller still seems to do nothing.

Not sure what else to do at this point?

**Comment by chino** [comment]
I tried the Beta version this time and it did the same behavior except this time there is never a Log.txt file at all.

**Comment by Rayth** [comment]
you'll probably find that even tho the folder remains after running the uninstaller, the files are gone and you can't run the launcher. at that point you should be able to manually remove from the start menu and delete the folder.

**Comment by chino** [comment]
Well the entry also does not get removed from the windows application list which is undesirable? Also does it undo the changes to the game folders and replace the original games?

**Comment by TresAbhi** [comment]
@chino I believe `com.mojang` permanently gets renamed to `com.mojang.default`; unless, you rename it.

**Comment by chino** [comment]
How would I get rid of the entry from the windows application list?

**Comment by Rayth** [comment]
when you try run the launcher from that list, windows usually detects its not there and asks you to remove it

**Comment by chino** [comment]
As far as I can see in windows 10 the add/remove apps screen only has an option to uninstall and nothing about launching.

**Comment by NT690** [comment]
Close Issue? (9 days since last activity)

**Comment by Rayth** [comment]
> As far as I can see in windows 10 the add/remove apps screen only has an option to uninstall and nothing about launching.

After you run the uninstall, if you try launch the app from your start menu it will fail and ask if you want to remove from the list.

**Comment by chino** [comment]
That just deletes the shortcut but not the application it self in the, "add or remove applications" registry.

**Comment by NT690** [comment]
I think this should have the bug and affects <version> labels.

**Comment by Rayth** [comment]
Latest release has no installer or uninstaller.
