### ISSUE TITLE
Add support for 1.17, 1.18

### ISSUE THREAD

**Issue by minusfourty** [BedrockLauncher/BedrockLauncher#116]
When testing out the launcher, all versions of 1.17 and 1.18 are incompatible.

**Comment by Rayth** [comment]
> When testing out the launcher, all versions of 1.17 and 1.18 are incompatible.

What do you mean incompatible? I used the launcher to update every version of 1.17 and 1.18 so far

**Comment by Rayth** [comment]
Also please provide some logs if possible

**Comment by NT690** [comment]
Close Issue? (It`s been 8 days since last reply)
