### ISSUE TITLE
Stop this madness

### ISSUE THREAD

**Issue by Mydadisacomputer** [BedrockLauncher/BedrockLauncher#118]
Stop this. please make it 32 bit. i only wanna have fun. i don't want any hate towards me i only wanna play the game and forgot about this madness. don't cause any drama. or death threats. i only want to have fun. just go with it. even if you beg to me to not download it NORE TRUST ANYONE ON THIS DUMPSTER FIRE ever. bye and listen to this comment and don't go and spread randomness to humans. because you will be a terrible human being or any being if you do so. This is for myself. and my entertainment. goodbye

**Comment by Rayth** [comment]
Yeah i'm going to close this just because of the multitude of spam that isn't relevant.

**Comment by TresAbhi** [comment]
What?

**Comment by Mydadisacomputer** [comment]
then what do i do

**Comment by Mydadisacomputer** [comment]
> multitude

what did i do

**Comment by Mydadisacomputer** [comment]
:/

**Comment by Rayth** [comment]
> :/

You didn't even say there's a problem. You had a whole rant about not wanting any hate toward you. If there is a genuine issue with the software, start a new issue and give some actual details

**Comment by gituser245** [comment]
https://github.com/projectcomet64/M64MM/issues/37
