### ISSUE TITLE
Problem starting Minecraft Bedrock

### ISSUE THREAD

**Issue by nisel11** [BedrockLauncher/BedrockLauncher#119]
I wanted to download this launcher, because the regular launcher does not provide such features as this one, and when downloading the latest release for minecraft, an error got out 

 System.Exception: Deployment failed: Windows не удается установить пакет Microsoft.MinecraftUWP_1.18.203.0_x64__8wekyb3d8bbwe, поскольку он зависит от платформы, которую не удается найти. Предоставьте платформу "Microsoft.Services.Store.Engagement", опубликованную "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", с нейтральной архитектурой или архитектурой процессора x64 и минимальной версией 10.0.1610.0 вместе с этим пакетом для установки. Платформы с именем "Microsoft.Services.Store.Engagement", установленные в настоящий момент: {}
   в BedrockLauncher.ViewModels.GameManager.<RegisterPackage>d__27.MoveNext() в D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:строка 549
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в BedrockLauncher.ViewModels.GameManager.<Launch>d__19.MoveNext() в D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:строка 277
 
Please tell me how to solve the problem

**Comment by Rayth** [comment]
duplicate of #73
