### ISSUE TITLE
No Insider Accounts

### ISSUE THREAD

**Issue by SpectiZ** [BedrockLauncher/BedrockLauncher#12]
![Screenshot (5)](https://user-images.githubusercontent.com/85769337/121754460-50ab0a80-cada-11eb-8fd8-beaf7ae56415.png)

**Comment by AvgZing** [comment]
Update to the latest version, seems fixed.

**Comment by SpectiZ** [comment]
> 
> 
> Update to the latest version, seems fixed.

Still no insider accounts for me...

**Comment by ShadowFlame303** [comment]
Make sure the user you're using on your PC is an admin. Ran into the same issue but I was able to fix it by promoting the user I was using to admin. Followed one of the first tutorials that showed up on Google.

**Comment by SpectiZ** [comment]
> 
> 
> Make sure the user you're using on your PC is an admin. Ran into the same issue but I was able to fix it by promoting the user I was using to admin. Followed one of the first tutorials that showed up on Google.

I am an admin though...
![Screenshot (6)](https://user-images.githubusercontent.com/85769337/121970967-55bbc400-cd3d-11eb-8415-87b925a869e9.png)

**Comment by CarJem** [comment]
Chalking this up to user error... not application error... sorry.

**Comment by ATXLtheAxolotl** [comment]
I'm having the same problem, and I know the problem is that I'm on a non-administrator account. Is there anyway to use this on a normal permission user?
