### ISSUE TITLE
Installer not working

### ISSUE THREAD

**Issue by ghost** [BedrockLauncher/BedrockLauncher#122]
i tried different versions of the installer but it said its incompatible pls help

**Comment by Rayth** [comment]
@itsyamonkey can you provide logs or any errors?

**Comment by itsyamonkey** [comment]
i cant find / i dont know where the logs are, the installer didnt work, but the portable worked

**Comment by Rayth** [comment]
@itsyamonkey you said it was saying incompatible. is there a message along with that? and again, what are your PC specs?

**Comment by itsyamonkey** [comment]
my laptop is acer aspire 5733
4gb ram
intel core i3 380M
intel HD graphics

and i ran the compability troubleshooter and it said imcomptable

**Comment by Rayth** [comment]
what windows version are you using?

**Comment by itsyamonkey** [comment]
windows 10

**Comment by Rayth** [comment]
So you ran compatability troubleshoort, but what happens when you actually run the installer file? you said you got the portable to work and that's installed from the same installer

**Comment by itsyamonkey** [comment]
ik but, wheen i run the installer, nothing happens, literally nothing

**Comment by Rayth** [comment]
so how do you get portable to work? and are you running the installer with administrator priveliges

**Comment by itsyamonkey** [comment]
idk, i just downloaded the build.zip, and it works, but the .exe doesn't work

**Comment by tttyfd** [comment]
https://bedrocklauncher.github.io/You can download it here

**Comment by NT690** [comment]
Close Issue? (3 months since last reply)
