### ISSUE TITLE
I installed it, but I can't start MinecraftBedrock

### ISSUE THREAD

**Issue by tttyfd** [BedrockLauncher/BedrockLauncher#123]
I installed it, but I can't start MinecraftBedrock

**Comment by Rayth** [comment]
do you **own** minecraft? and are you logged into the microsoft store with the account that owns minecraft

**Comment by TresAbhi** [comment]
Please check the FAQ on the [official website](https://bedrocklauncher.github.io) since there are answers to this exact question.
