### ISSUE TITLE
Profiles names with characters outside of the English letters renders it unusable 

### ISSUE THREAD

**Issue by gituser245** [BedrockLauncher/BedrockLauncher#124]
i got some info tell me if something matches just to see if the info i found is correct

[Info About Windows users.txt](https://github.com/BedrockLauncher/BedrockLauncher/files/7818012/Info.About.Windows.users.txt)

**Comment by TresAbhi** [comment]
What is this about?

**Comment by gituser245** [comment]
if a windows users with non wnglish letters is created programs are not working  like versions of minecrft above 1.16.200 lauched with the bedrock launcher will lauch but crash right after more info in the txt about what programs i found that dont work what i did to fix it dont have technical information tho

**Comment by Rayth** [comment]
I remember something like this before but maybe @CarJem will know more

**Comment by TresAbhi** [comment]
Can you please provide a log, we know that has been an issue.

**Comment by gituser245** [comment]
i dont have a log and i fixed my local user a while ago and ive been trying to test on a new local user but i get reregister errors on any version of the program that use so ill try again later on a different pc + i tested it before if i remember correctly it should be fixed

**Comment by TresAbhi** [comment]
Closing until we have concrete information
