### ISSUE TITLE
(MCBE Launcher V2.0 Test #1) some bugs

### ISSUE THREAD

**Issue by gituser245** [BedrockLauncher/BedrockLauncher#127]
1) Extraction failed:  (Portable & Normal)
BedrockLauncher.Exceptions.PackageExtractionFailedException: The process cannot access the file 'C:\Users\Damianos\Desktop\build\Minecraft-1.10.0.7.Appx' because it is being used by another process
(the error shows up at 100% extraction so if i launch the profile a second time with the error seems to launch normally i didnt check the version files if something is missing tho)

[MCBE Launcher Portable error_log.txt](https://github.com/BedrockLauncher/BedrockLauncher/files/7910932/MCBE.Launcher.Portable.error_log.txt)
[MCBE Launcher Perma Directory.txt](https://github.com/BedrockLauncher/BedrockLauncher/files/7910933/MCBE.Launcher.Perma.Directory.txt)
)

2) When Creating a skin pack the page doesnt automatically refresh or something so the created skin pack doest show up need to swith tabs and back to refresh

3) Skin packs the skin preview model doesnt exist (picture of what i mean) might have to do with the refreshing issue
![Untitled](https://user-images.githubusercontent.com/84343022/150479921-f41651aa-806f-487f-8fe6-79e40e49e7ba.png)

4) not sure is this broken? maybe in the news tab all icon dont load have a look 
(old)
![image](https://user-images.githubusercontent.com/84343022/150482108-a62bab71-a6c0-4fb3-9034-cde986502aa2.png)
![image](https://user-images.githubusercontent.com/84343022/150482149-dd424fae-3630-4ee5-b630-16ee6c19bea4.png)
![image](https://user-images.githubusercontent.com/84343022/150482166-4148e412-67e0-4594-9c0c-794c2e6383b2.png)
(new)
![image](https://user-images.githubusercontent.com/84343022/150482221-21bd4155-1cab-4a3c-a1c1-5d4b71110cd2.png)
![image](https://user-images.githubusercontent.com/84343022/150482255-d7a8a5e0-c559-4404-979b-50ae2275e9e8.png)
![image](https://user-images.githubusercontent.com/84343022/150482270-5985d29e-4893-4e24-a40f-2a1ab95ee13c.png)

if i find anything more i might update this unless its unnecessary you tell me

**Comment by Rayth** [comment]
1. Are you running in admin mode?
2. The skin stuff is being worked on in the full re-write thats happening right now.
3. ^
4. News stuff is also being worked on atm.

Also why have you put MCBE Launcher V2.0?

**Comment by gituser245** [comment]
yes i am running in admin mode and the error shows up at 100% extraction so if i launch the profile with the error it launches i didnt check the version files if something is missing tho

and heres a tweet about why im calling it that
https://twitter.com/carter5467_99/status/1484289417732833284?s=20

**Comment by Rayth** [comment]
Still wouldn't be v2.0 since we don't even have  a v1.0 yet

**Comment by gituser245** [comment]
i wouldnt say its about the version its like the program is taking a new path new visions its going to be bigger and better

+i dont know what else to call it
