### ISSUE TITLE
Failed to find Download Links

### ISSUE THREAD

**Issue by kilivan4iK** [BedrockLauncher/BedrockLauncher#13]
Application Starting...
Application Pre-Initalization Finished!
Checking for updates
OK
OK
Current tag: 0.0.1.8
Latest tag: 0.0.1.8
New UWP version: 
250727482 62a2b986-c366-4197-9809-6d986656b750 Microsoft.MinecraftUWP_1.17.2.70_x86__8wekyb3d8bbwe
New UWP version: 
250727484 86d33060-bb8d-4acd-8ef0-f8696d9fa64f Microsoft.MinecraftUWP_1.17.2.0_x86__8wekyb3d8bbwe
New UWP version: 
250727486 f5c26150-fa98-434f-8f37-a7d5a2ec3867 Microsoft.MinecraftUWP_1.17.2.70_x64__8wekyb3d8bbwe
New UWP version: 
250727483 77453360-6d8b-4222-ba8c-e1ba07d03e6f Microsoft.MinecraftUWP_1.17.2.70_arm__8wekyb3d8bbwe
New UWP version: 
250727485 917533a2-a8a1-48bd-83d0-ea71f0c22ac2 Microsoft.MinecraftUWP_1.17.2.0_arm__8wekyb3d8bbwe
New UWP version: 
250727482 62a2b986-c366-4197-9809-6d986656b750 Microsoft.MinecraftUWP_1.17.2.70_x86__8wekyb3d8bbwe
New UWP version: 
250727484 86d33060-bb8d-4acd-8ef0-f8696d9fa64f Microsoft.MinecraftUWP_1.17.2.0_x86__8wekyb3d8bbwe
New UWP version: 
250727483 77453360-6d8b-4222-ba8c-e1ba07d03e6f Microsoft.MinecraftUWP_1.17.2.70_arm__8wekyb3d8bbwe
New UWP version: 
250727486 f5c26150-fa98-434f-8f37-a7d5a2ec3867 Microsoft.MinecraftUWP_1.17.2.70_x64__8wekyb3d8bbwe
New UWP version: 
250727485 917533a2-a8a1-48bd-83d0-ea71f0c22ac2 Microsoft.MinecraftUWP_1.17.2.0_arm__8wekyb3d8bbwe
Download start
Waiting for authentication
Authentication complete
Download failed:
System.Exception: Failed to Find Download Links ---> System.InvalidOperationException: Последовательность не содержит соответствующий элемент
   в BedrockLauncher.UpdateProcessor.Win10VersionDBExtensions.first_node_or_throw(XElement element, XName name) в D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10VersionDBExtensions.cs:строка 55
   в BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<getDownloadLinks>d__32.MoveNext() в D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:строка 433
   --- Конец трассировки внутреннего стека исключений ---
   в BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<getDownloadLinks>d__32.MoveNext() в D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:строка 446
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   в BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<getDownloadLink>d__33.MoveNext() в D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:строка 452
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в BedrockLauncher.Downloaders.VersionDownloader.<Download>d__4.MoveNext() в D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\Downloaders\VersionDownloader.cs:строка 48
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в BedrockLauncher.Methods.GameManager.<DownloadVersion>d__34.MoveNext() в D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\Methods\GameManager.cs:строка 456
Download start
Waiting for authentication
Authentication complete
Download failed:
System.Exception: Failed to Find Download Links ---> System.InvalidOperationException: Последовательность не содержит соответствующий элемент
   в BedrockLauncher.UpdateProcessor.Win10VersionDBExtensions.first_node_or_throw(XElement element, XName name) в D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10VersionDBExtensions.cs:строка 55
   в BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<getDownloadLinks>d__32.MoveNext() в D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:строка 433
   --- Конец трассировки внутреннего стека исключений ---
   в BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<getDownloadLinks>d__32.MoveNext() в D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:строка 446
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   в BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<getDownloadLink>d__33.MoveNext() в D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:строка 452
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в BedrockLauncher.Downloaders.VersionDownloader.<Download>d__4.MoveNext() в D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\Downloaders\VersionDownloader.cs:строка 48
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в BedrockLauncher.Methods.GameManager.<DownloadVersion>d__34.MoveNext() в D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\Methods\GameManager.cs:строка 456
Download start
Waiting for authentication
Authentication complete
Download failed:
System.Exception: Failed to Find Download Links ---> System.InvalidOperationException: Последовательность не содержит соответствующий элемент
   в BedrockLauncher.UpdateProcessor.Win10VersionDBExtensions.first_node_or_throw(XElement element, XName name) в D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10VersionDBExtensions.cs:строка 55
   в BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<getDownloadLinks>d__32.MoveNext() в D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:строка 433
   --- Конец трассировки внутреннего стека исключений ---
   в BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<getDownloadLinks>d__32.MoveNext() в D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:строка 446
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   в BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<getDownloadLink>d__33.MoveNext() в D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:строка 452
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в BedrockLauncher.Downloaders.VersionDownloader.<Download>d__4.MoveNext() в D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\Downloaders\VersionDownloader.cs:строка 48
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в BedrockLauncher.Methods.GameManager.<DownloadVersion>d__34.MoveNext() в D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\Methods\GameManager.cs:строка 456
Download start
Waiting for authentication
Authentication complete
Download failed:
System.Exception: Failed to Find Download Links ---> System.InvalidOperationException: Последовательность не содержит соответствующий элемент
   в BedrockLauncher.UpdateProcessor.Win10VersionDBExtensions.first_node_or_throw(XElement element, XName name) в D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10VersionDBExtensions.cs:строка 55
   в BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<getDownloadLinks>d__32.MoveNext() в D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:строка 433
   --- Конец трассировки внутреннего стека исключений ---
   в BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<getDownloadLinks>d__32.MoveNext() в D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:строка 446
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   в BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<getDownloadLink>d__33.MoveNext() в D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:строка 452
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в BedrockLauncher.Downloaders.VersionDownloader.<Download>d__4.MoveNext() в D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\Downloaders\VersionDownloader.cs:строка 48
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в BedrockLauncher.Methods.GameManager.<DownloadVersion>d__34.MoveNext() в D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\Methods\GameManager.cs:строка 456
Download start
Waiting for authentication
Authentication complete
Download failed:
System.Exception: Failed to Find Download Links ---> System.InvalidOperationException: Последовательность не содержит соответствующий элемент
   в BedrockLauncher.UpdateProcessor.Win10VersionDBExtensions.first_node_or_throw(XElement element, XName name) в D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10VersionDBExtensions.cs:строка 55
   в BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<getDownloadLinks>d__32.MoveNext() в D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:строка 433
   --- Конец трассировки внутреннего стека исключений ---
   в BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<getDownloadLinks>d__32.MoveNext() в D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:строка 446
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   в BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<getDownloadLink>d__33.MoveNext() в D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:строка 452
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в BedrockLauncher.Downloaders.VersionDownloader.<Download>d__4.MoveNext() в D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\Downloaders\VersionDownloader.cs:строка 48
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в BedrockLauncher.Methods.GameManager.<DownloadVersion>d__34.MoveNext() в D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\Methods\GameManager.cs:строка 456

**Comment by AvgZing** [comment]
Seconded: have this issue when trying to download insider builds.

**Comment by CarJem** [comment]
Closing Because of Lack of Inactivity... and being unable to reproduce the issue in the current commits.

**Comment by SuperFluffyGame** [comment]
I have this same problem, don't know what to do.

**Comment by SuperFluffyGame** [comment]
I found why it does this. You have to be *enrolled* in the minecraft beta on insider.

**Comment by AvgZing** [comment]
I am enrolled 
![image](https://user-images.githubusercontent.com/25853984/124000852-04990a80-d9a2-11eb-9087-a59b360e1b7b.png)

But I still get this issue
![image](https://user-images.githubusercontent.com/25853984/124000922-15e21700-d9a2-11eb-9497-7e93613d7b88.png)
when trying to access the latest beta. I am using the latest dev version.

**Comment by Mitko1239** [comment]
> I am enrolled
> ![image](https://user-images.githubusercontent.com/25853984/124000852-04990a80-d9a2-11eb-9087-a59b360e1b7b.png)
> 
> But I still get this issue
> ![image](https://user-images.githubusercontent.com/25853984/124000922-15e21700-d9a2-11eb-9497-7e93613d7b88.png)
> when trying to access the latest beta. I am using the latest dev version.

Same here :\

**Comment by Mitko1239** [comment]
Ok, @AvgZing I actually fixed it with this:
![image](https://user-images.githubusercontent.com/1289999/128430890-c0568ca5-4ae8-40e4-8396-83459aba6ec7.png)
