### ISSUE TITLE
my minecraft keeps ending forever

### ISSUE THREAD

**Issue by gusthavo17** [BedrockLauncher/BedrockLauncher#132]
my minecraft keeps ending forever

**Comment by Rayth** [comment]
Can you elaborate? What's happening exactly

**Comment by gusthavo17** [comment]
![Captura de Tela (4)](https://user-images.githubusercontent.com/59624881/151343425-749da844-9966-4e8a-99cf-4aeebd815560.png)
keeps loading infinitely

**Comment by Rayth** [comment]
Can you provide your log file, translated into english if possible too

**Comment by gusthavo17** [comment]
[Log.txt](https://github.com/BedrockLauncher/BedrockLauncher/files/7952145/Log.txt)

**Comment by gusthavo17** [comment]
the error keeps
[Log.txt](https://github.com/BedrockLauncher/BedrockLauncher/files/7952924/Log.txt)

**Comment by Rayth** [comment]
you haven't got a name for the installion for the version you're trying to play. Goto installtions, modify your one and give it a name.

Also check if using "Latest Release" works

**Comment by gusthavo17** [comment]
I modified and gave a name but it doesn't work

**Comment by Rayth** [comment]
can you post an updated log now. it should have a different error from the last one. Also are you running in admin mode?

**Comment by gusthavo17** [comment]
[Log.txt](https://github.com/BedrockLauncher/BedrockLauncher/files/7960214/Log.txt)
yes  i running in adimin mode

**Comment by Rayth** [comment]
Can you try uninstalling minecraft from control panel > apps then run from launcher.

**Comment by gusthavo17** [comment]
minecraft does not appear in control panel

**Comment by Rayth** [comment]
ok in that case, goto the windows store, install minecraft then uninstall it again and try running the launcher.

**Comment by gusthavo17** [comment]
my problem is solved thank you very much

**Comment by TresAbhi** [comment]
> my problem is solved thank you very much

Technology do be like that sometimes...
