### ISSUE TITLE
Not a issue, but a question.

### ISSUE THREAD

**Issue by Herobrine8761** [BedrockLauncher/BedrockLauncher#133]
Is it safe? Won't it harm my desktop? I am very scared but enough brave to test the application. I am using it, no matter what. Please reply me.

**Comment by Rayth** [comment]
Yes it is safe. I have used it since alpha testing and had no issues. The beauty is that I have it set to store data on my external HD so everything is already backed up.

**Comment by Rayth** [comment]
Well what issue are you having? Everyone else gets it working fine. I've been using it for over a year

**Comment by Herobrine8761** [comment]
I downloaded and installed the game. Then I clicked on the Play button. It started to download some files (so I gave it a while). It was done so I began to start Minecraft. And it gave me an error (Which I have forgotten till now) and it did not open. I was very disappointed by that.

**Comment by Rayth** [comment]
can you share your log file? or tell us the error?

**Comment by TresAbhi** [comment]
So you're saying you received an error **after the game launched**? Is there a way you can provide information as to how the launcher is responsible for that interaction?

**Comment by Herobrine8761** [comment]
> can you share your log file? or tell us the error?

That app is kind of LOST? IT IS NOT SHOWING THE APP IN MY APP MENU!!!! I DIDN'T EVEN UNINSTALL IT! IS THIS SOME SORTA DATA STEALER?????

**Comment by Rayth** [comment]
> > can you share your log file? or tell us the error?
> 
> That app is kind of LOST? IT IS NOT SHOWING THE APP IN MY APP MENU!!!! I DIDN'T EVEN UNINSTALL IT! IS THIS SOME SORTA DATA STEALER?????

it's literally open source. you can check the code yourself. it steals nothing

**Comment by Herobrine8761** [comment]
> > > can you share your log file? or tell us the error?
> > 
> > 
> > That app is kind of LOST? IT IS NOT SHOWING THE APP IN MY APP MENU!!!! I DIDN'T EVEN UNINSTALL IT! IS THIS SOME SORTA DATA STEALER?????
> 
> it's literally open source. you can check the code yourself. it steals nothing

BUT IT IS SHOWING NOWHERE! EVEN IN THE CONTROL PANEL!

**Comment by Rayth** [comment]
Did you run the installer, or did you download the zip and run from there?

**Comment by Herobrine8761** [comment]
I did the whole process- even the app ran before my eyes

**Comment by Herobrine8761** [comment]
> Did you run the installer, or did you download the zip and run from there?

To be honest the app directly

**Comment by Herobrine8761** [comment]
no zip files

**Comment by Rayth** [comment]
You had to have removed it then, or your antivirus did (false positives still occur). The app can't remove itself without you running the uninstaller

**Comment by Herobrine8761** [comment]
Ok let me check my antivirus

**Comment by Herobrine8761** [comment]
It's saying something about a dangerous file or app got uninstalled- Perhaps the antivirus took the app a bit too serious

**Comment by Herobrine8761** [comment]
Sorry, I didn't prefer checking my antivirus- as this was the first application that got automatic uninstalled.

**Comment by synnkfps** [comment]
crazy kid Herobrine8761

**Comment by Herobrine8761** [comment]
I am not dead. I can see what you say.
