### ISSUE TITLE
After opening, Minecraft shows 'unlock the full game'? 

### ISSUE THREAD

**Issue by Villadome** [BedrockLauncher/BedrockLauncher#137]
Is this a issue or is that supposed to happen?

**Comment by Rayth** [comment]
Do you actually own minecraft? This isn't a way to get minecraft for free. 

https://bedrocklauncher.github.io/faq

**Comment by Villadome** [comment]
Then you may not like this! There is a guy selling your tutorial on YouTube showing that this works and unlocks the total game! Idk if he really is guilty. But here he is https://youtu.be/0hH_vniLzOc

**Comment by Villadome** [comment]
He is speaking Hindi but since I understand Hindi thus I know he is fraud.

**Comment by Rayth** [comment]
He has comments disabled and I don't speak hindi. from the description though it says how to install the launcher and run minecraft. Unless he specifically says in the video that it will get you minecraft for free, I don't see anything wrong
