### ISSUE TITLE
Make Insider Account Non-Mandatory + Hide Beta Versions in List

### ISSUE THREAD

**Issue by LeqzDoIt** [BedrockLauncher/BedrockLauncher#14]
Unfortunately, Xbox Insider Hub is not available in my country and I can't sign up for Minecraft for Windows 10 Beta. I probably can use a VPN but I don't really care about the Beta anyway.  Unticking Beta from the profiles tab only hide Beta profiles but not Beta version from the download list as it does with Snapshots in Java Edition Launcher.

**Comment by CarJem** [comment]
I will double check to make sure it does... You should be seeing this addressed in a couple of versions

**Comment by CarJem** [comment]
Fixed in the Following Commits:
ac90659ce17654c9d0352d371fef2159faaf7635
28a2818536a9a3486f48ebe2afe8ce3ce1aa080e
