### ISSUE TITLE
Refresh Button Not Consistent In Placement Through Pages

### ISSUE THREAD

**Issue by NT690** [BedrockLauncher/BedrockLauncher#140]
![2022-02-08 21_08_28-Minecraft Bedrock Launcher](https://user-images.githubusercontent.com/70166536/153125930-e3f10453-127e-4113-b5c1-f27cd0cedcd4.png)
![2022-02-08 21_09_08-Minecraft Bedrock Launcher](https://user-images.githubusercontent.com/70166536/153125943-183e0102-e0d8-4429-a4ac-2de23e0ce2c4.png)
In the first picture, the refresh button is in the bottom right, while in the second one, it is in the mid-top right.

**Comment by CarJem** [comment]
Fixed in the latest update, closing!
