### ISSUE TITLE
Skin not recognised

### ISSUE THREAD

**Issue by SecretGamerV071** [BedrockLauncher/BedrockLauncher#147]
When i use the import option on the skins menu, after selecting the skin pack, it deiplays error "Unable to import skin pack" and in the subtitle " That's not a skin pack, silly!"

**Comment by TresAbhi** [comment]
Can you please provide the skin pack? I will assess why that may happen.

**Comment by SecretGamerV071** [comment]
[SGV_Enderman_Skins_compilation.zip](https://github.com/BedrockLauncher/BedrockLauncher/files/8060113/SGV_Enderman_Skins_compilation.zip)
(Uploaded a .zip as .mcpack isn't supported by GitHub)
