### ISSUE TITLE
External launcher tab is not properly scaled with the name

### ISSUE THREAD

**Issue by LeqzDoIt** [BedrockLauncher/BedrockLauncher#15]
![Minecraft Bedrock Launcher 13-Jun-21 12_01_45 PM](https://user-images.githubusercontent.com/64237500/121795139-633f5400-cc40-11eb-9145-4d1aa11bcb19.png)

As you can see, the word edition is obscured because it exceeds the tab size.

**Comment by CarJem** [comment]
I'm unsure if I should address this... Considering that changing the size would be against Mojang Specifications with the UI

**Comment by LeqzDoIt** [comment]
If you want to follow the specifications, characters should be limited. I can live without the word edition I suppose.
You will the address the arguments problem right ? 
Also, can you add the ability to add more external launchers ? I'll love to put the Pi Edition in the launcher when MCPI-Reborn 2.0 released.

**Comment by CarJem** [comment]
It has been considered... I will fix the issue at hand... But there are other issues I'm prioritizing atm
