### ISSUE TITLE
1.18.20.26 classified as release instead of beta, and crashes the launcher

### ISSUE THREAD

**Issue by SuperFluffyGame** [BedrockLauncher/BedrockLauncher#150]
Latest Release defaults to 1.18.20.26, and when I launch it, it crashes. I tried making a separate instance of it and it still doesn't work.

**Comment by SuperFluffyGame** [comment]
Dunno if this is relevant or not, but there isn't any official changelogs. https://feedback.minecraft.net/hc/en-us/sections/360001185332-Beta-Information-and-Changelogs

**Comment by Rayth** [comment]
We're aware of this issue and it's due to the new Minecraft Previews being labelled differently in the store from betas. It's installing Preview and you'll find that if you go through start menu. At the moment the work-around is to create an installation of 1.18.10 and run it through that. A fix is being worked on but we have no ETA at the present time.

**Comment by NT690** [comment]
I think CarJem fixed this. He says so [here](https://twitter.com/carter5467_99/status/1493017072544190465?s=20&t=p3avxi9qGM8Wb8QAEtEkrw), however, it's still in beta.

**Comment by TresAbhi** [comment]
Yup, a fix is coming. I believe it's in Bedrock launcher `2.0`.

**Comment by gtsouth** [comment]
Where is the fix?  I still can't play.

**Comment by TresAbhi** [comment]
It's not out yet.

**Comment by AvgZing** [comment]
To play, just create a new installation in the correct released version, rather than by using "latest Release"

**Comment by Rayth** [comment]
> To play, just create a new installation in the correct released version, rather than by using "latest Release", as was mentioned earlier. You can duplicate the latest release installation and change the version from there, to keep your worlds and saves and etc.

This has already been mentoned in a higher comment. Please don't comment without reading other comments first as it just created un-necessary spam

**Comment by TresAbhi** [comment]
Fixed with a temporary solution!

**Comment by gtsouth** [comment]
> > To play, just create a new installation in the correct released version, rather than by using "latest Release", as was mentioned earlier. You can duplicate the latest release installation and change the version from there, to keep your worlds and saves and etc.
> 
> This has already been mentoned in a higher comment. Please don't comment without reading other comments first as it just created un-necessary spam

No help at all.  Just telling me not to comment.  I read the previous comment.  I don't know how to do what was said.  No instructions.  Again.... not too much help..  just rudeness.   I still haven't been able to play since February.

**Comment by gtsouth** [comment]
I went back a version.  Game works but all of my hours of progress are gone.

**Comment by Rayth** [comment]
> I went back a version. Game works but all of my hours of progress are gone.

This has been fixed in the latest beta version of the launcher which is why this issue is closed. https://github.com/BedrockLauncher/BedrockLauncher-Beta/releases/tag/2022.4.17.21

**Comment by gtsouth** [comment]
The latest beta version closes right away on me.

**Comment by gtsouth** [comment]
I get an error code and an option to send a crash report

**Comment by Rayth** [comment]
well whats the error code? check the folder that the beta is in and there should be one called logs. find the latest log file.

make sure your running bedrocklauncher.exe not the installer in the build.zip folder after extracting.

**Comment by gtsouth** [comment]
-2146233088
Failed to Find Download Links

**Comment by gtsouth** [comment]
Can't find the folder

**Comment by Rayth** [comment]
it will be wherever you downloaded it to. i gave you the download link above. you download the build.zip file then extract it and run the exe file which isn't an installer. Anymore issues please make a new issue.
