### ISSUE TITLE
I can install it, but I can't make a micra. 

### ISSUE THREAD

**Issue by kazaminosuke** [BedrockLauncher/BedrockLauncher#156]
Error-2147024894 ErrorApp-register failed

**Comment by kazaminosuke** [comment]
https://drive.google.com/file/d/1UXuIErkRvJ94RxjGVOXodF3t1uoWH_3A/view?usp=sharing An errorVideo

**Comment by Rayth** [comment]
That video is not publically shared.

**Comment by TresAbhi** [comment]
Duplicate of #39.
