### ISSUE TITLE
Bedrock Launcher Doesnt Run Latest Version Of MInecraft

### ISSUE THREAD

**Issue by Midnight-Mellow** [BedrockLauncher/BedrockLauncher#160]
When I try to run the Latest Release installation it does not run, Minecraft doesn't open and crash it just doesn't open. Other Installations work fine but I cant get the newest to work.

**Comment by Narlotl** [comment]
https://github.com/BedrockLauncher/BedrockLauncher/issues/150#issuecomment-1038451918
This is being worked on and should be fixed in the next release/update of the launcher.
