### ISSUE TITLE
Installations with special characters makes them unusable

### ISSUE THREAD

**Issue by CXCubeHD** [BedrockLauncher/BedrockLauncher#164]
https://user-images.githubusercontent.com/49782272/155707662-c66e1211-be4e-4bee-bc0b-544c071db70b.mp4

**Comment by Rayth** [comment]
Don't use special characters in your installation name.

**Comment by TresAbhi** [comment]
This is a known bug, however, I don't know why we did not file a bug report; but, it's here anyway. I am unsure whether or not this is fixed in `v2.0`. @CarJem would know.

**Comment by NT690** [comment]
this seems to be fixed in the beta 
[log for the interested](https://github.com/BedrockLauncher/BedrockLauncher/files/8644559/Log_2022-05-06_22-44-56.log)
