### ISSUE TITLE
No compiled builds since 0.0.2.1

### ISSUE THREAD

**Issue by AvgZing** [BedrockLauncher/BedrockLauncher#165]
There have been tons of changes and fixes since the last release back in June (111 commits!), but there have been no releases. Is there a reason for this?

**Comment by Rayth** [comment]
Well there is the beta 0.0.2.6 that you can use, but yes there is a reason for commits. There's language updates, and carjem is currently redoing alot of code to improve the performance of the launcher

**Comment by AvgZing** [comment]
You have to compile that beta yourself though, no?

**Comment by Rayth** [comment]
> You have to compile that beta yourself though, no?

when you run the installer it asks you which version you want to install.
