### ISSUE TITLE
STILL NOT LAUNCHING

### ISSUE THREAD

**Issue by ORGINRISHITH** [BedrockLauncher/BedrockLauncher#172]
THE BEDROCK IS NOT LAUNCHING INSTEAD LAUNCHER IS COLOSING AFTER 10 SECONDS

**Comment by Narlotl** [comment]
[#150](https://github.com/BedrockLauncher/BedrockLauncher/issues/150)
This is a known issue and is will be fixed in the next update of the launcher.
