### ISSUE TITLE
Issue when trying to open v1.14.60

### ISSUE THREAD

**Issue by SecretGamerV071** [BedrockLauncher/BedrockLauncher#174]
![image](https://user-images.githubusercontent.com/95269740/157818035-733af1f1-b1df-44c8-b6ba-3e9f136d291e.png)
Getting this error. Then the games open, and immediately closes. No crash report, no entry in Log.txt. Only displays a white screen for a few seconds and then closes.

**Comment by Rayth** [comment]
did you have mc installed prior to installing the launcher?

**Comment by TresAbhi** [comment]
While you're at it, can we have a log? We have had several people have this issue but nobody has provided a log.

**Comment by SecretGamerV071** [comment]
> did you have mc installed prior to installing the launcher?

Obviously. I'm not that much of an idiot

**Comment by SecretGamerV071** [comment]
> While you're at it, can we have a log? We have had several people have this issue but nobody has provided a log.

Can you tell me where can I find the Log.txt file? I am not able to. If it helps, the launcher doesn't show one of those boxes that you get when your game crashes. The game open, I see the "Mojang Studios" screen. Then it closes. This is also a problem with versions 1.10.0.7 to 1.15.0.54(Beta). 1.16 and above works just fine.

**Comment by TresAbhi** [comment]
It's where the bedrock launcher is installed.
