### ISSUE TITLE
Problem If you have Minecraft Preview.

### ISSUE THREAD

**Issue by xbox-one-x-guy** [BedrockLauncher/BedrockLauncher#177]
I don't know if this has already been reported, I did not see it when going through issues.
Here's the issue:
If you own (just own no need for it to be installed on the pc) the Minecraft Preview, when downloading the "latest release", the launcher downloads the latest preview version instead (it is available on the start menu for verification that the app has been installed and you can see the APPX file of that in the Bedrock Launcher's directory when you start installing "Latest Release" inside the launcher.
and after installing and extraction, the launcher attempts to launch it and what happens is, the launcher just stops showing that loading when launching and nothing happens. (it keeps looping launching on Public Beta 0.0.1.8.)

**Comment by Rayth** [comment]
Duplicate #150 

Doesn't matter if you have preview installed already or not.

**Comment by xbox-one-x-guy** [comment]
oh opps sorry I did not see #150
