### ISSUE TITLE
Windows cannot use the PreserveApplicationData flag because the app didn't run in development mode

### ISSUE THREAD

**Issue by Mcfly2340** [BedrockLauncher/BedrockLauncher#178]
![image](https://user-images.githubusercontent.com/71077562/160809711-2a183e47-00a4-42e3-9b4b-fe68e8660b18.png)
log files:
[Log.txt](https://github.com/BedrockLauncher/BedrockLauncher/files/8379606/Log.txt)

**Comment by TresAbhi** [comment]
Duplicate of #76
