### ISSUE TITLE
`Microsoft.VCLibs.140.00` framework goes missing

### ISSUE THREAD

**Issue by Asterbelia** [BedrockLauncher/BedrockLauncher#181]
i get this error message when i click on play, anyone know how to fix? :/
(some lines are in italian sorry)
:

Application Starting...
Checking for updates
Current tag: 0.0.2.6
Latest tag: 0.0.2.1
Application Pre-Initalization Finished!
Registering package
Deployment failed: Non è possibile installare il pacchetto Microsoft.MinecraftWindowsBeta_1.18.3031.0_x64__8wekyb3d8bbwe perché questo pacchetto dipende da un framework non trovato. Specifica il framework "Microsoft.VCLibs.140.00" pubblicato da "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", con un'architettura del processore neutrale o x64 e una versione minima 14.0.30704.0, insieme al pacchetto da installare. I framework con nome "Microsoft.VCLibs.140.00" attualmente installati sono: {Microsoft.VCLibs.140.00_14.0.27810.0_x86__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.27810.0_x64__8wekyb3d8bbwe}
App re-register failed:
System.Exception: Deployment failed: Non è possibile installare il pacchetto Microsoft.MinecraftWindowsBeta_1.18.3031.0_x64__8wekyb3d8bbwe perché questo pacchetto dipende da un framework non trovato. Specifica il framework "Microsoft.VCLibs.140.00" pubblicato da "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", con un'architettura del processore neutrale o x64 e una versione minima 14.0.30704.0, insieme al pacchetto da installare. I framework con nome "Microsoft.VCLibs.140.00" attualmente installati sono: {Microsoft.VCLibs.140.00_14.0.27810.0_x86__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.27810.0_x64__8wekyb3d8bbwe}
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in BedrockLauncher.ViewModels.GameManager.<DeploymentProgressWrapper>d__28.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:riga 575
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in BedrockLauncher.ViewModels.GameManager.<RegisterPackage>d__27.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:riga 540
App launch failed:
System.Exception: Deployment failed: Non è possibile installare il pacchetto Microsoft.MinecraftWindowsBeta_1.18.3031.0_x64__8wekyb3d8bbwe perché questo pacchetto dipende da un framework non trovato. Specifica il framework "Microsoft.VCLibs.140.00" pubblicato da "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", con un'architettura del processore neutrale o x64 e una versione minima 14.0.30704.0, insieme al pacchetto da installare. I framework con nome "Microsoft.VCLibs.140.00" attualmente installati sono: {Microsoft.VCLibs.140.00_14.0.27810.0_x86__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.27810.0_x64__8wekyb3d8bbwe}
   in BedrockLauncher.ViewModels.GameManager.<RegisterPackage>d__27.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:riga 549
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in BedrockLauncher.ViewModels.GameManager.<Launch>d__19.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:riga 277
Registering package
Deployment failed: Non è possibile installare il pacchetto Microsoft.MinecraftWindowsBeta_1.18.3031.0_x64__8wekyb3d8bbwe perché questo pacchetto dipende da un framework non trovato. Specifica il framework "Microsoft.VCLibs.140.00" pubblicato da "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", con un'architettura del processore neutrale o x64 e una versione minima 14.0.30704.0, insieme al pacchetto da installare. I framework con nome "Microsoft.VCLibs.140.00" attualmente installati sono: {Microsoft.VCLibs.140.00_14.0.27810.0_x86__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.27810.0_x64__8wekyb3d8bbwe}
App re-register failed:
System.Exception: Deployment failed: Non è possibile installare il pacchetto Microsoft.MinecraftWindowsBeta_1.18.3031.0_x64__8wekyb3d8bbwe perché questo pacchetto dipende da un framework non trovato. Specifica il framework "Microsoft.VCLibs.140.00" pubblicato da "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", con un'architettura del processore neutrale o x64 e una versione minima 14.0.30704.0, insieme al pacchetto da installare. I framework con nome "Microsoft.VCLibs.140.00" attualmente installati sono: {Microsoft.VCLibs.140.00_14.0.27810.0_x86__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.27810.0_x64__8wekyb3d8bbwe}
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in BedrockLauncher.ViewModels.GameManager.<DeploymentProgressWrapper>d__28.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:riga 575
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in BedrockLauncher.ViewModels.GameManager.<RegisterPackage>d__27.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:riga 540
App launch failed:
System.Exception: Deployment failed: Non è possibile installare il pacchetto Microsoft.MinecraftWindowsBeta_1.18.3031.0_x64__8wekyb3d8bbwe perché questo pacchetto dipende da un framework non trovato. Specifica il framework "Microsoft.VCLibs.140.00" pubblicato da "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", con un'architettura del processore neutrale o x64 e una versione minima 14.0.30704.0, insieme al pacchetto da installare. I framework con nome "Microsoft.VCLibs.140.00" attualmente installati sono: {Microsoft.VCLibs.140.00_14.0.27810.0_x86__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.27810.0_x64__8wekyb3d8bbwe}
   in BedrockLauncher.ViewModels.GameManager.<RegisterPackage>d__27.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:riga 549
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in BedrockLauncher.ViewModels.GameManager.<Launch>d__19.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:riga 277

**Comment by Rayth** [comment]
If you're clicking to play latest release, please read #150 otherwise can you provide a translation?

**Comment by Narlotl** [comment]
Probably not perfect:

```Application Starting ...
Checking for updates
Current tag: 0.0.2.6
Latest tag: 0.0.2.1
Application Pre-Initalization Finished!
Registering package
Deployment failed: The Microsoft.MinecraftWindowsBeta_1.18.3031.0_x64__8wekyb3d8bbwe package cannot be installed because this package depends on a framework not found. Specifies the "Microsoft.VCLibs.140.00" framework published by "CN = Microsoft Corporation, O = Microsoft Corporation, L = Redmond, S = Washington, C = US", with a neutral or x64 processor architecture and a minimum version of 14.0 .30704.0, along with the package to be installed. The frameworks named "Microsoft.VCLibs.140.00" currently installed are: {Microsoft.VCLibs.140.00_14.0.27810.0_x86__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.27810.0_x64__8wekyb3d8bbwe}
App re-register failed:
System.Exception: Deployment failed: The Microsoft.MinecraftWindowsBeta_1.18.3031.0_x64__8wekyb3d8bbwe package cannot be installed because this package depends on a framework not found. Specifies the "Microsoft.VCLibs.140.00" framework published by "CN = Microsoft Corporation, O = Microsoft Corporation, L = Redmond, S = Washington, C = US", with a neutral or x64 processor architecture and a minimum version of 14.0 .30704.0, along with the package to be installed. The frameworks named "Microsoft.VCLibs.140.00" currently installed are: {Microsoft.VCLibs.140.00_14.0.27810.0_x86__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.27810.0_x64__8wekyb3d8bbwe}
in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (Task task)
in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (Task task)
in BedrockLauncher.ViewModels.GameManager.d__28.MoveNext () in D: \ UserData \ Source \ mc_repos \ BedrockLauncher \ BedrockLauncher \ ViewModels \ GameManager.cs: line 575
--- End stack trace from previous location where exception was thrown ---
in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (Task task)
in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (Task task)
in BedrockLauncher.ViewModels.GameManager.d__27.MoveNext () in D: \ UserData \ Source \ mc_repos \ BedrockLauncher \ BedrockLauncher \ ViewModels \ GameManager.cs: line 540
App launch failed:
System.Exception: Deployment failed: The Microsoft.MinecraftWindowsBeta_1.18.3031.0_x64__8wekyb3d8bbwe package cannot be installed because this package depends on a framework not found. Specifies the "Microsoft.VCLibs.140.00" framework published by "CN = Microsoft Corporation, O = Microsoft Corporation, L = Redmond, S = Washington, C = US", with a neutral or x64 processor architecture and a minimum version of 14.0 .30704.0, along with the package to be installed. The frameworks named "Microsoft.VCLibs.140.00" currently installed are: {Microsoft.VCLibs.140.00_14.0.27810.0_x86__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.27810.0_x64__8wekyb3d8bbwe}
in BedrockLauncher.ViewModels.GameManager.d__27.MoveNext () in D: \ UserData \ Source \ mc_repos \ BedrockLauncher \ BedrockLauncher \ ViewModels \ GameManager.cs: line 549
--- End stack trace from previous location where exception was thrown ---
in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (Task task)
in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (Task task)
in BedrockLauncher.ViewModels.GameManager.d__19.MoveNext () in D: \ UserData \ Source \ mc_repos \ BedrockLauncher \ BedrockLauncher \ ViewModels \ GameManager.cs: line 277
Registering package
Deployment failed: The Microsoft.MinecraftWindowsBeta_1.18.3031.0_x64__8wekyb3d8bbwe package cannot be installed because this package depends on a framework not found. Specifies the "Microsoft.VCLibs.140.00" framework published by "CN = Microsoft Corporation, O = Microsoft Corporation, L = Redmond, S = Washington, C = US", with a neutral or x64 processor architecture and a minimum version of 14.0 .30704.0, along with the package to be installed. The frameworks named "Microsoft.VCLibs.140.00" currently installed are: {Microsoft.VCLibs.140.00_14.0.27810.0_x86__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.27810.0_x64__8wekyb3d8bbwe}
App re-register failed:
System.Exception: Deployment failed: The Microsoft.MinecraftWindowsBeta_1.18.3031.0_x64__8wekyb3d8bbwe package cannot be installed because this package depends on a framework not found. Specifies the "Microsoft.VCLibs.140.00" framework published by "CN = Microsoft Corporation, O = Microsoft Corporation, L = Redmond, S = Washington, C = US", with a neutral or x64 processor architecture and a minimum version of 14.0 .30704.0, along with the package to be installed. The frameworks named "Microsoft.VCLibs.140.00" currently installed are: {Microsoft.VCLibs.140.00_14.0.27810.0_x86__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.27810.0_x64__8wekyb3d8bbwe}
in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (Task task)
in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (Task task)
in BedrockLauncher.ViewModels.GameManager.d__28.MoveNext () in D: \ UserData \ Source \ mc_repos \ BedrockLauncher \ BedrockLauncher \ ViewModels \ GameManager.cs: line 575
--- End stack trace from previous location where exception was thrown ---
in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (Task task)
in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (Task task)
in BedrockLauncher.ViewModels.GameManager.d__27.MoveNext () in D: \ UserData \ Source \ mc_repos \ BedrockLauncher \ BedrockLauncher \ ViewModels \ GameManager.cs: line 540
App launch failed:
System.Exception: Deployment failed: The Microsoft.MinecraftWindowsBeta_1.18.3031.0_x64__8wekyb3d8bbwe package cannot be installed because this package depends on a framework not found. Specifies the "Microsoft.VCLibs.140.00" framework published by "CN = Microsoft Corporation, O = Microsoft Corporation, L = Redmond, S = Washington, C = US", with a neutral or x64 processor architecture and a minimum version of 14.0 .30704.0, along with the package to be installed. The frameworks named "Microsoft.VCLibs.140.00" currently installed are: {Microsoft.VCLibs.140.00_14.0.27810.0_x86__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.27810.0_x64__8wekyb3d8bbwe}
in BedrockLauncher.ViewModels.GameManager.d__27.MoveNext () in D: \ UserData \ Source \ mc_repos \ BedrockLauncher \ BedrockLauncher \ ViewModels \ GameManager.cs: line 549
--- End stack trace from previous location where exception was thrown ---
in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (Task task)
in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (Task task)
in BedrockLauncher.ViewModels.GameManager.d__19.MoveNext () in D: \ UserData \ Source \ mc_repos \ BedrockLauncher \ BedrockLauncher \ ViewModels \ GameManager.cs: line 277```

**Comment by Rayth** [comment]
https://docs.microsoft.com/en-us/troubleshoot/developer/visualstudio/cpp/libraries/c-runtime-packages-desktop-bridge

Check the 4 links on this website see if one of them installs what you need, then it should work.

**Comment by Asterbelia** [comment]
> https://docs.microsoft.com/en-us/troubleshoot/developer/visualstudio/cpp/libraries/c-runtime-packages-desktop-bridge
> 
> Check the 4 links on this website see if one of them installs what you need, then it should work


i tried but it didn't work, but it does install the microsoft thing, and it still gives me the same error :/ i dunno why

**Comment by NT690** [comment]
i know it's really late but try the latest release https://github.com/BedrockLauncher/BedrockLauncher-Beta/releases/tag/2022.4.17.21
