### ISSUE TITLE
Can I play Minecraft online without buying it?

### ISSUE THREAD

**Issue by Fernffa** [BedrockLauncher/BedrockLauncher#185]
I'm new, just discovered this (never bought or tried Minecraft Bedrock) <3

**Comment by TheEpikBoi** [comment]
No you have to buy the game

**Comment by TresAbhi** [comment]
Read the disclaimers: https://github.com/BedrockLauncher/BedrockLauncher/blob/master/docs/DISCLAIMERS.md
