### ISSUE TITLE
[Suggestion] Add X86 Minecraft APPX files support for the launcher like a seperate add button for x86 minecraft

### ISSUE THREAD

**Issue by LeontKing2** [BedrockLauncher/BedrockLauncher#188]
It would be really helpfull as we can install shaders in x86 mc

**Comment by LeontKing2** [comment]
even if we cannot there are lots of features still in x86 mc which are not there in x64 like jump delay input lag stuff

**Comment by LeontKing2** [comment]
the "cannot" is for shaders in x86 mc

**Comment by Rayth** [comment]
This depends entirely on how the X86 versions are found. I only know of the link trough the hive website, but the launcher pulls data from the microsoft store directly. If the x86 versions can be taken from the store then @CarJem would theorhetically be able to do this.

**Comment by DelofJ** [comment]
I don't know if this comment will help, but I'm posting it anyway
On [this issue](https://github.com/MCMrARM/mc-w10-version-launcher/issues/114), of the original Minecraft Windows 10 Version downloader from MCMrARM, which is used in the Bedrock Launcher, MCMrARM talks about the fact that we can get the IDs of x86 builds in [its list](https://github.com/MCMrARM/mc-w10-versiondb/blob/master/versions.txt) of IDs allowing to download them with [its script](https://gist.github.com/MCMrARM/d4fe4a8f38e8a12034c1c830b19989c2)
I don't know if it's the way that the Bedrock Launcher works but I tried to download an APPX x86 build with this method and it worked
You said it would be possible to add the x86 builds to the launcher if the x86 versions can be taken from the store
Now that we can download the x86 builds of the APPXs, it's theoretically possible to add them to the launcher, right ? (or am I totally wrong ?)

**Comment by Rayth** [comment]
Correct, however there's now the fact the OP posted this to install shaders. As of 1.18.30 even the x86 version wont allow shaders as it's been moved to render dragon.

**Comment by DelofJ** [comment]
Now we need to wait for every computers and phones to support RTX
Not joke now I don’t know if it’s necessary for the Bedrock Launcher to support the x86 builds but I think for some people it would be useful, for example people who have computers with x86 architecture

**Comment by Rayth** [comment]
The latest beta launcher does support x86 builds
https://github.com/BedrockLauncher/BedrockLauncher-Beta/releases/tag/2022.4.17.21

**Comment by TresAbhi** [comment]
@Rayth so can we close now?

**Comment by miqumi** [comment]
Okay uhh you can also install shaders in x64
