### ISSUE TITLE
Launcher and github tags different for version prompting an update to be available

### ISSUE THREAD

**Issue by Mcfly2340** [BedrockLauncher/BedrockLauncher#190]
![image](https://user-images.githubusercontent.com/71077562/163843522-82c5cd66-1cf2-4e53-8666-192c6c39198e.png)
this pop-up stays after the update.

**Comment by TresAbhi** [comment]
Can you provide a log?

**Comment by gituser245** [comment]
pressing the x button doesnt close it either it starts to update

**Comment by TresAbhi** [comment]
Noted. Can you provide a log?

**Comment by gituser245** [comment]
i dont think i have a log i checked in PFx86 dont see anything

**Comment by gituser245** [comment]
[Log_2022-04-18_23-05-33.log](https://github.com/BedrockLauncher/BedrockLauncher/files/8507894/Log_2022-04-18_23-05-33.log)
if something will check some more

**Comment by TresAbhi** [comment]
I believe I do understand the issue. The GitHub release recognizes the build as `....21` but the build it `....20` so it always assumes there's an update.

**Comment by CarJem** [comment]
Won't fix as the new release is now out and addresses the issue

**Comment by AshUosis** [comment]
> Won't fix as the new release is now out and addresses the issue

It still shows the banner

**Comment by Rayth** [comment]
> > Won't fix as the new release is now out and addresses the issue
> 
> It still shows the banner

https://github.com/BedrockLauncher/BedrockLauncher/releases/tag/2022.7.4.195

If you're still seeing banner, you're not on latest release
