### ISSUE TITLE
Launcher doesn't link `com.mojang` folder after registering package and requires second game launch

### ISSUE THREAD

**Issue by gituser245** [BedrockLauncher/BedrockLauncher#192]
loading a profile with a different version of minecraft than the profile that was previously loaded will result in having to load the profile twice
[Log_2022-04-19_17-54-06.log](https://github.com/BedrockLauncher/BedrockLauncher/files/8514194/Log_2022-04-19_17-54-06.log)
e
video was too big for git hub so i have posted it on youtube
https://youtu.be/SvMhIpG9Two

**Comment by gituser245** [comment]
heres a cleaner log
[Log_2022-04-19_20-26-42.log](https://github.com/BedrockLauncher/BedrockLauncher/files/8515229/Log_2022-04-19_20-26-42.log)
g
![image](https://user-images.githubusercontent.com/84343022/164063614-1a9fab6f-1aa3-45e4-8d6f-aaf8333dea49.png)
previously loaded (Latest Release) loaded after (Mai Version)

**Comment by Rayth** [comment]
It appears the first install of a version (registering package) doesn't copy/link up the files and acts like it's a fresh install.

**Comment by DelofJ** [comment]
I have one thing to add regarding this, it's not a bug but rather a suggestion, if you choose to play "Latest Release" or "Latest Beta", 2 different folders are created and you can't change this, and if you want to do a custom installation it gives you 3 different folders and you have to reconfigure the game each time, is it planned that you can edit these installations to change their directory like a new installation ?

**Comment by Rayth** [comment]
> I have one thing to add regarding this, it's not a bug but rather a suggestion, if you choose to play "Latest Release" or "Latest Beta", 2 different folders are created and you can't change this, and if you want to do a custom installation it gives you 3 different folders and you have to reconfigure the game each time, is it planned that you can edit these installations to change their directory like a new installation ?

Different directories are intentional and required because lower game versions cannot play worlds that were loaded in a higher version. So if you create a beta world, you can't play it on release etc.

**Comment by DelofJ** [comment]
Ok, I didn't think we couldn't play on a world created in beta once the release was out, moreover for my use I only use betas to create temporary worlds and have betas and releases in the same file allowed that the changes of parameters be done only once and everywhere, but I can understand

**Comment by Rayth** [comment]
Updated. Still affects latest release. Developer working on it.

**Comment by Rayth** [comment]
Fixed https://github.com/BedrockLauncher/BedrockLauncher/commit/3ed563d2826badcfafa0817d0df8700c778f1e42
