### ISSUE TITLE
Launcher fails to create the link for com.mojang

### ISSUE THREAD

**Issue by DelofJ** [BedrockLauncher/BedrockLauncher#193]
In build 2022.4.17.20 ( or 2022.4.17.21 idk ), the launcher does not create a link for com.mojang to packageData, and when you change the version of Minecraft, you play as if it's a fresh installation, with nothing
The same problem occurs with Minecraft Preview

**Comment by Rayth** [comment]
I just encountered this as well. Afer installing latest version, I closed MC then re-opened and it linked correctly.

**Comment by Rayth** [comment]
Same issue as #192

**Comment by DelofJ** [comment]
Oh ok, I didn't see that this issue was already open, thanks
