### ISSUE TITLE
Fail to Switch to Java Launcher

### ISSUE THREAD

**Issue by DelofJ** [BedrockLauncher/BedrockLauncher#194]
When you click on "Switch to Java Launcher", you get a crash report, this problem occurs with Minecraft Bedrock Launcher 2022.4.17.20, and for info I have both launcher installed, from the Microsoft Store and the Legacy from minecraft.net
https://gist.github.com/DelofJ/2799b8e0ac850d3c183a394e19e8ab32

I also have a suggestion, before the launcher update, you could edit the settings.json to point the ExternalLauncherPath to `shell:appsFolder\\\Microsoft.4297127D64EC6_8wekyb3d8bbwe!Minecraft` to launch the Microsoft Store Launcher
`shell:appsFolder\` is the path that list all applications registered on Windows
`Microsoft.4297127D64EC6_8wekyb3d8bbwe!Minecraft` is the "file name" of the app
the \\ is to cancel the first \ so the json doesn't interpret it as a "command"

**Comment by DelofJ** [comment]
Update, the same issue occurs when you want to "Repair/Update Game" In the Installation tab of Minecraft Dungeons

**Comment by Rayth** [comment]
Feature removed in latest release.
