### ISSUE TITLE
Missing `.Net` frameworks

### ISSUE THREAD

**Issue by SuperFluffyGame** [BedrockLauncher/BedrockLauncher#195]
"To run this application, you must install missing frameworks for .NET. Would you like to download now?"

It then takes you to the runtime download page witch ive already installed.

**Comment by TresAbhi** [comment]
Lucky for you, I solved this issue just yesterday!

1. Go to the official [ASP.NET download](https://dotnet.microsoft.com/en-us/download/dotnet/3.1)
2. Install the `x64` or the `x86` (highlighted in green) depending on your computer ![](https://i.imgur.com/XCDixDX.png)
3. Go to the [official C++ Redistributable downloads page](https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170) ad scroll down and download the appropriate version: ![](https://i.imgur.com/efDCnHP.png)
4. Restart your computer
5. Done!

**Comment by SuperFluffyGame** [comment]
didnt work :(

**Comment by VanillaChan6571** [comment]
I found out that you also need the following ".net frameworks":
[windowsdesktop-runtime-6.0.8-win-x64](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.8-windows-x64-installer) & [windowsdesktop-runtime-6.0.8-win-x86](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.8-windows-x86-installer)

This solved **my** issue.

**Comment by Rayth** [comment]
This issue is relating to an old version of the launcher which is why it's closed. At that time, those 2 runtimes were NOT required as they are now with the new version. Amusingly the download page for the new version even states you need the desktop runtime frameworks.
