### ISSUE TITLE
Chinese Simplified has already been translated to but is not avaliable in the program

### ISSUE THREAD

**Issue by zhenlige** [BedrockLauncher/BedrockLauncher#199]
There is already a Chinese Simplified translation in Crowdin:
<img width="123" alt="image" src="https://user-images.githubusercontent.com/38127204/165873134-4d34b5c0-a1a6-4630-a596-e6098084e708.png">
But not in the program:
<img width="269" alt="image" src="https://user-images.githubusercontent.com/38127204/165873325-7039f15d-4899-4567-8285-12e34f42b9fc.png">

**Comment by TresAbhi** [comment]
The PR has not been merged
