### ISSUE TITLE
When installing it says npm Warn saveError ENOENT, EPERM and npm warn Windows no description, repository field no Readme data No license field. I used the git clone in Visual studio.

### ISSUE THREAD

**Issue by madkdlkdnodfs** [BedrockLauncher/BedrockLauncher#2]
![2](https://user-images.githubusercontent.com/77518076/118984946-035cd280-b94c-11eb-959d-5b0eda36f0e7.png)
![3](https://user-images.githubusercontent.com/77518076/118984948-035cd280-b94c-11eb-9c61-20ec80afae70.png)
![Screenshot 2021-05-20 091213](https://user-images.githubusercontent.com/77518076/118984949-03f56900-b94c-11eb-987c-8eb62665b60e.png)

**Comment by CarJem** [comment]
You do have three.js with npm's command installed Correct?

**Comment by madkdlkdnodfs** [comment]
Yes I have node.js with npm installed. It also was telling me that there was no valid license when I would try to build the launcher. It would ask me to crate a proper license to be able to get it to work.

**Comment by CarJem** [comment]
You'll need to install the community edition of Resharper... sorry it's not
mentioned yet

**Comment by CarJem** [comment]
You'll need to install the community edition of Resharper... sorry it's not mentioned yet

**Comment by CarJem** [comment]
Fixed the mess... closing
