### ISSUE TITLE
not loading after clicking "play"

### ISSUE THREAD

**Issue by deadxxxxinside** [BedrockLauncher/BedrockLauncher#201]
when i am clicking on the button play, a few second pass and after launching a game, the launcher just closing and the game is not launching without any issue. windows vers 19044.1645.

**Comment by Rayth** [comment]
What version of the launcher are you on? Can you give us a log file?

**Comment by deadxxxxinside** [comment]
> What version of the launcher are you on? Can you give us a log file?
launcher vers 0.0.2.1, pls tell me where i can find the log file

**Comment by Rayth** [comment]
Ok so your issue is a duplcate of #150 

It is fixed in this beta: https://github.com/BedrockLauncher/BedrockLauncher-Beta/releases/tag/2022.4.17.21
