### ISSUE TITLE
Minecraft doesn't load

### ISSUE THREAD

**Issue by Astroblik** [BedrockLauncher/BedrockLauncher#203]
I have downloaded the launcher and the minecraft version but I can't get minecraft to start because the launcher keeps getting stuck on the actual 'launching' of the game

**Comment by Rayth** [comment]
Sounds like you're on the old version with issue #150 

Try downloading https://github.com/BedrockLauncher/BedrockLauncher-Beta/releases/tag/2022.4.17.21
