### ISSUE TITLE
[error] [with logs] error -2146233088

### ISSUE THREAD

**Issue by skhrlx** [BedrockLauncher/BedrockLauncher#207]
´´´
Application Starting...
Application Pre-Initalization Finished!
Checking for updates
Current tag: 0.0.2.1
Latest tag: 0.0.2.1
Download start
Waiting for authentication
Authentication complete
Download failed:
System.Exception: Failed to Find Download Links ---> System.InvalidOperationException: A sequência não contém elementos de correspondência
   em BedrockLauncher.UpdateProcessor.Win10VersionDBExtensions.first_node_or_throw(XElement element, XName name) na D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10VersionDBExtensions.cs:linha 55
   em BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<getDownloadLinks>d__32.MoveNext() na D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:linha 427
   --- Fim do rastreamento de pilha de exceções internas ---
   em BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<getDownloadLinks>d__32.MoveNext() na D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:linha 446
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<getDownloadLink>d__33.MoveNext() na D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:linha 452
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em BedrockLauncher.Downloaders.VersionDownloader.<Download>d__11.MoveNext() na D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\Downloaders\VersionDownloader.cs:linha 78
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em BedrockLauncher.ViewModels.GameManager.<DownloadVersion>d__20.MoveNext() na D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:linha 353
Download start
Waiting for authentication
Authentication complete
Download failed:
System.Exception: Failed to Find Download Links ---> System.InvalidOperationException: A sequência não contém elementos de correspondência
   em BedrockLauncher.UpdateProcessor.Win10VersionDBExtensions.first_node_or_throw(XElement element, XName name) na D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10VersionDBExtensions.cs:linha 55
   em BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<getDownloadLinks>d__32.MoveNext() na D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:linha 427
   --- Fim do rastreamento de pilha de exceções internas ---
   em BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<getDownloadLinks>d__32.MoveNext() na D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:linha 446
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<getDownloadLink>d__33.MoveNext() na D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:linha 452
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em BedrockLauncher.Downloaders.VersionDownloader.<Download>d__11.MoveNext() na D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\Downloaders\VersionDownloader.cs:linha 78
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em BedrockLauncher.ViewModels.GameManager.<DownloadVersion>d__20.MoveNext() na D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:linha 353
´´´

**Comment by TresAbhi** [comment]
Duplicate of #81
