### ISSUE TITLE
Game crashes when loading the latest version

### ISSUE THREAD

**Issue by Amaricanolol** [BedrockLauncher/BedrockLauncher#209]
Ive tried to launch the latest version cuz i wanna play bedwars with my sis(shes on mobile), but somehow its just not working
pls fix this or im gonna hate bedrock even more
and yeah the new windows 10 launcher wont launch any version so ye
here is the log if needed
[Log.txt](https://github.com/BedrockLauncher/BedrockLauncher/files/8734814/Log.txt)

**Comment by Rayth** [comment]
Download https://github.com/BedrockLauncher/BedrockLauncher-Beta/releases/tag/2022.4.17.21
