### ISSUE TITLE
Impossibility to launch Minecraft Beta versions

### ISSUE THREAD

**Issue by DelofJ** [BedrockLauncher/BedrockLauncher#212]
Since Mojang retired the Minecraft Beta system, you can no longer install and play Minecraft Beta builds through the launcher, I also made a report on the GitHub of MCMrARM's MCLauncher since that is the system being used, the report is [here](https://github.com/MCMrARM/mc-w10-version-launcher/issues/200)

**Comment by Rayth** [comment]
This is fixed in the latest beta version of the launcher.

**Comment by DelofJ** [comment]
Ok, nice

**Comment by Rayth** [comment]
> Ok, nice, thanks

See this comment:
https://github.com/BedrockLauncher/BedrockLauncher/issues/211#issuecomment-1137100725
