### ISSUE TITLE
I can't install it

### ISSUE THREAD

**Issue by summoringer** [BedrockLauncher/BedrockLauncher#215]
Whenever I try to install the launcher tis pop up:
![image](https://user-images.githubusercontent.com/105224744/172467170-ab56acf6-8694-4a29-8246-85651d56fed1.png)
I try to install it again... hopeless.
I also tried to restart me PC
pleas help me

**Comment by summoringer** [comment]
if u need more infos too my PC just ask

**Comment by TresAbhi** [comment]
Please provide a log

**Comment by summoringer** [comment]
I fixed it the problem was my virus scanner it's called "bull guard". I uninstalled it
