### ISSUE TITLE
Renaming an installation creates a new installation when run

### ISSUE THREAD

**Issue by Rayth** [BedrockLauncher/BedrockLauncher#217]
If you rename an installation inside the app it creates a full new installation instead when you press the "play" button.

Reproduction steps:
Step 1- Create an installation on any version and run. Create a world so there is data to track.
Step 2- Close minecraft
Step 3- Goto the "Installations" tab
Step 4- Click the "Folder" icon beside the play button for your installation to open the correct location, then navigate to the directory of your profile (2 parent directory above the folder that opens)
Step 5- Inside the launcher, Click the 3 dots beside the above button and click edit
Step 6- Change the "name" of the installation and press save.
Step 7- Run the installation under the new name.

When running, watch your folder that's open. You will see a new folder get created, but it won't copy the data over from the old folder.

**Comment by Rayth** [comment]
Updated. still affects latest release.

**Comment by CarJem** [comment]
## Discord Conversation Port:


### **CarJem:**
Well here's the deal... By Intended Behavior... leaving the directory blank automatically defaults to a folder friendly version of what ever the installation is named if not set

###  **Rayth:**
which I like, but if the installation gets renamed, shouldn't the launcher look for a folder friendly version of the old installation name then rename it to a folder friendly version of the new installation name?

###  **CarJem:**
Yeah... so here's what we could do...
When an installation is created... it doesn't leave it blank... rather it takes the folder friendly name and saves it then and there 
This wouldn't conflict with any existing logic... and would fix the issue and it's an easy fix
