### ISSUE TITLE
.NET framework not found

### ISSUE THREAD

**Issue by Feelsev3** [BedrockLauncher/BedrockLauncher#219]
Can you explain what specific Framework i need because i have installed every framework even the .NET preview 7 and in software requirements it's not explained.

![obraz](https://user-images.githubusercontent.com/70484896/173018079-08858b8d-c562-4748-8e04-51ffb577525b.png)

**Comment by Feelsev3** [comment]
i installed every microsoft c++ redistributable and then it said that i need 6.0.5 framework

**Comment by Rayth** [comment]
https://github.com/BedrockLauncher/BedrockLauncher/issues/195#issuecomment-1103371313
