### ISSUE TITLE
"unhandled exception occured" crash when clicking Play

### ISSUE THREAD

**Issue by ImEthanBradberry** [BedrockLauncher/BedrockLauncher#220]
When I click the green PLAY button I get this error:

_Unhandled exception occured:
Object reference not set to an instance of an object._

Im using Windows 10 1809 LTSC Enterprise to avoid bloatware from regular versions. Microsoft insists that I update to use the Minecraft Launcher so to avoid that I tried your software but it crashes. I just want to install Bedrock. I have Java bought since like 2010, I already did the migration thing. How do I install Bedrock? I just want to edit Bedrock worlds with the Amulet app but I need to install Bedrock first.

Edit: I got past the error by disabling Tinywall, but then I got another error. Looking at the log it seems it is again Microsoft insisting on me updating to the latest Windows 10 version. It is obvious Bedrock is just an excuse to push people into updating their OS.

**Comment by NT690** [comment]
Could you post the log file? The error you said in the original comment is the same as #53, but it looks like you are getting a different error.

**Comment by TresAbhi** [comment]
Seems like "Tinywall" was the issue in your case. Closing. Make sure to report the other issue in a new report, but this time, with a log.
