### ISSUE TITLE
Missing NET Frameworks

### ISSUE THREAD

**Issue by PSGitHubUser1** [BedrockLauncher/BedrockLauncher#221]
**When I open it, it shows 'missing net frameworks' and when I try to download NET Framework 4.8 (latest), it shows I have already installed it in my Computer but when I check in Control Panel or Settings, nothing shows releated to this.**

**Comment by Rayth** [comment]
4.8 isn't the latest .net framework. Given this error, I'm assuming you're on the latest beta. Read this comment: https://github.com/BedrockLauncher/BedrockLauncher/issues/195#issuecomment-1103371313
