### ISSUE TITLE
Minecraft not opening

### ISSUE THREAD

**Issue by HyperDondon** [BedrockLauncher/BedrockLauncher#222]
when i press launch the launcher closes (as intended) but nothing happens i use windows 10 21h1 (OS Build 19044.1706) i have gtx 1650 a core i5 10300h

**Comment by Rayth** [comment]
Can you provide log? Which version of the launcher are you on?

**Comment by crackBB** [comment]
> Can you provide log? Which version of the launcher are you on?
how to check it

**Comment by crackBB** [comment]
Im using last release of launcher

**Comment by Rayth** [comment]
Use this version: https://github.com/BedrockLauncher/BedrockLauncher-Beta/releases/tag/2022.4.17.21

Unzip the build.zip folder, and run the bedrock launcher exe file (NOT THE INSTALLER)

**Comment by crackBB** [comment]
i opened it and nothing happened

**Comment by crackBB** [comment]
![Знімок екрана (56)](https://user-images.githubusercontent.com/107645637/174243934-66071d6a-bb14-4e2e-84c2-d60ea1589396.png)

**Comment by crackBB** [comment]
Так-Yes Ні-No. im from Ukraine

**Comment by crackBB** [comment]
i downloaded it but i still cant open it

**Comment by Rayth** [comment]
https://github.com/BedrockLauncher/BedrockLauncher/issues/195#issuecomment-1103371313 follow these instructions and please keep replies to 1 post rather than 4.

**Comment by crackBB** [comment]
kk

**Comment by HyperDondon** [comment]
> Can you provide log? Which version of the launcher are you on?

 It dosent give an error so there is no log to provide

**Comment by Rayth** [comment]
> > Can you provide log? Which version of the launcher are you on?
> 
> It dosent give an error so I cant provide log I use the latest version of the launcher

There would be a log file in your launcher folder, but read the comments above that's most likely your problem
