### ISSUE TITLE
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified

### ISSUE THREAD

**Issue by PageNotFound40** [BedrockLauncher/BedrockLauncher#223]
the entire error is 
Application Starting...
Application Pre-Initalization Finished!
Checking for updates
Current tag: 0.0.2.1
Latest tag: 0.0.2.1
Download start
Resolved download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/bb2a7627-a305-4e33-bc2d-7570381b1b24?P1=1655174090&P2=404&P3=2&P4=YIOHKzQjwl8LYkoLHp%2fSZSmEjHYJ4naj16oJgySW55wZBY%2f9txDoEv5NwuIFBDDnmEnHar2C9RCBAMGSk1RISg%3d%3d
Actual download started
Download complete
Extraction started
Extracted successfully
CantFindJavaLauncher: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Minecraft Launcher\Minecraft Launcher.lnk
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at BedrockLauncher.MainWindow.<NavigateToJavaLauncher>b__21_1() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\MainWindow.xaml.cs:line 223

**Comment by NT690** [comment]
you might want to try the latest beta and see if you get the same bug here https://github.com/BedrockLauncher/BedrockLauncher-Beta/releases/tag/2022.4.17.21
