### ISSUE TITLE
Minecraft Preview versions fail to launch

### ISSUE THREAD

**Issue by AshUosis** [BedrockLauncher/BedrockLauncher#225]
![hgc](https://user-images.githubusercontent.com/107533626/173753399-59c70e40-4242-48be-864d-14f0be2e5f39.png)

**Comment by AshUosis** [comment]
![god help](https://user-images.githubusercontent.com/107533626/173757190-24233790-96b3-4b58-9f1a-a6111cf26c44.png)

**Comment by Rayth** [comment]
use the latest beta version of the app: https://github.com/BedrockLauncher/BedrockLauncher-Beta/releases/tag/2022.4.17.21
