### ISSUE TITLE
App Registration Failed

### ISSUE THREAD

**Issue by FlameQuard** [BedrockLauncher/BedrockLauncher#230]
![image](https://user-images.githubusercontent.com/84311327/174584286-109aec35-cd51-430c-9ae4-c4d296a6d515.png)

i have latest NET framework & also its installed through visual studio 2022, still not working

**Comment by Rayth** [comment]
Are you on the latest beta of the launcher? https://github.com/BedrockLauncher/BedrockLauncher-Beta/releases/tag/2022.4.17.21

Duplicate #73

**Comment by FlameQuard** [comment]
But where is the solution
