### ISSUE TITLE
SSL Connectioin could not be established

### ISSUE THREAD

**Issue by SilinVeredno** [BedrockLauncher/BedrockLauncher#238]
Screenshot
![IMG_20220703_213555](https://user-images.githubusercontent.com/80191234/177053030-9f298c8b-4649-44c7-a78d-669f9ad0f8ec.jpg)

**Comment by Rayth** [comment]
What version of the launcher are you using? Can you provide the log file from your installation folder

**Comment by King-Silicon** [comment]
> What version of the launcher are you using? Can you provide the log file from your installation folder

![image](https://user-images.githubusercontent.com/80191234/177055155-cf9fd3a6-7328-4a2f-b9f2-cfe362e539e0.png)

**Comment by TresAbhi** [comment]
@King-Silicon, please provide the version, what you've provided is a screenshot of the website.

**Comment by SilinVeredno** [comment]
> @King-Silicon, please provide the version, what you've provided is a screenshot of the website.

I don't know which version, I downloaded from the site.  Perhaps this is the latest

**Comment by SilinVeredno** [comment]
> > @King-Silicon, please provide the version, what you've provided is a screenshot of the website.
> 
> I don't know which version, I downloaded from the site.  Perhaps this is the latest.
> Then I download from github and say 

BRUH, I did not notice that this is a launcher for windows 10. I have windows 7. Please advise a launcher for my OS
