### ISSUE TITLE
.NET frameworks seemingly missing

### ISSUE THREAD

**Issue by SIsilicon** [BedrockLauncher/BedrockLauncher#239]
I'm trying out the lite version of the launcher for the first time ([this one](https://github.com/BedrockLauncher/BedrockLauncher/releases/tag/2022.7.3.63)).
I've tried installing the desktop runtime (both x64 and x86), but with both of these the following error message is given.

![To run this application, you must install missing frameworks for .NET. Would you like to download now?](https://user-images.githubusercontent.com/34734122/177065125-c18b5953-3e47-487c-b74d-9d49c3f328b7.png)

**Comment by NT690** [comment]
[#195 (comment)](https://github.com/BedrockLauncher/BedrockLauncher/issues/195#issuecomment-1103371313)
follow this comment

**Comment by SIsilicon** [comment]
Ah, thanks! However, it only looks like I needed to install the Core runtime. Didn't have to restart or use the vc_redit file.

**Comment by SIsilicon** [comment]
Perhaps @CarJem should update the release notes accordingly.
