### ISSUE TITLE
DLL Injection Support?

### ISSUE THREAD

**Issue by jqms** [BedrockLauncher/BedrockLauncher#24]
This is just a suggestion, but you should add a DLL injector into it, so you can automatically inject say Onix Client into the game when you launch

**Comment by CXCubeHD** [comment]
No cause then many antimalware programs go crazy

**Comment by h-m-m-m** [comment]
maybe not in the bedrock launcher but as a extra thing you can add

**Comment by Amaricanolol** [comment]
u can use a dll injector by putting the dll folder onto the minecraft.windows.exe file
