### ISSUE TITLE
Minecraft Launcher 2022.7.3.63 Sees Old Profiles As Latest Release

### ISSUE THREAD

**Issue by DLazaridisGM** [BedrockLauncher/BedrockLauncher#241]
1) Minecraft Launcher 2022.7.3.63 Sees Old Profiles As Latest Release and read only
2) the sort by option always resets to last played kinda annoying    and i didnt want to make a new issue soo its here

to fix it in User_profile.json i just changed VersioningMode": 3, from 2 to 3

        {
          "DisplayName": "Main Version",
          "VersionUUID": "49968828-1578-4f5a-b182-1455ec2b57d6",
          "IconPath": "bedrock.png",
          "IsCustomIcon": false,
          "DirectoryName": "",
          "ReadOnly": false,
          "VersioningMode": 3,
          "LastPlayed": "2022-07-04T19:35:34.9704285+03:00",
          "InstallationUUID": "7103357d-08db-45c9-8f81-326ce2a98161",
          "VersionType": 0
        },

![image](https://user-images.githubusercontent.com/84343022/177196350-9ab92fdb-9cce-4cfc-9297-c514cf14320e.png)

**Comment by DelofJ** [comment]
I saw that if you Edit the Profile and Save it without modifying anything, it also fix it
They probably did a change to who the launcher works with VersioningMode
And also happens with 2022.7.4.195
