### ISSUE TITLE
Installation icons won't be selected when trying to choose them

### ISSUE THREAD

**Issue by Mcfly2340** [BedrockLauncher/BedrockLauncher#244]
whenever I edit an installation or create a new one, the installation icons won't be selected when I select them from the list.
I can click on every single one but the actual icon won't update to it.

**Comment by CarJem** [comment]
> Please provide a full log file (Application Folder>Data>Logs) and steps to reproduce.
No need, I verified the issue

**Comment by Mcfly2340** [comment]
> > Please provide a full log file (Application Folder>Data>Logs) and steps to reproduce.
> 
> No need, I verified the issue

it works now thanks!
