### ISSUE TITLE
Error -2147024894

### ISSUE THREAD

**Issue by MarkEvans1235** [BedrockLauncher/BedrockLauncher#248]
It says "The system cannot find the file specified. (Exception from HRESULT: 0x80070002)".
Can't really tell what's going on so I don't know if its an issue. Got any solutions?
![image](https://user-images.githubusercontent.com/109513057/179476208-e01c5ad6-db63-4733-8f75-941d57fc7dda.png)

**Comment by Rayth** [comment]
The version you're using is no longer supported. Please download the Lite version here: https://github.com/BedrockLauncher/BedrockLauncher/releases/tag/2022.7.4.195 

All you need to do is extract the ZIP file then run BedrockLauncher.exe
