### ISSUE TITLE
Game not launching

### ISSUE THREAD

**Issue by XM9G** [BedrockLauncher/BedrockLauncher#25]
When I try to play it keeps saying launching and eventually freezes 
![image](https://user-images.githubusercontent.com/83699020/123250816-d9d82d80-d52d-11eb-9025-5927380abbb4.png)

**Comment by CarJem** [comment]
Will investigate

**Comment by CoolAbhi1290** [comment]
This happened to me way to often. Heck, it's only up until when I started working on the website for this launcher, that the launcher actually launched.

**Comment by XM9G** [comment]
It works now, I think it was because I was using another launcher but now I uninstalled it.

**Comment by CoolAbhi1290** [comment]
This issue should be closed as it was reporter's fault
