### ISSUE TITLE
Minecraft gets open, closes after a moment.

### ISSUE THREAD

**Issue by remi-reyes** [BedrockLauncher/BedrockLauncher#251]
When I click launch, Minecraft opens for a moment, then closes and the launcher does too, in the logs I cant find any error message.

**Comment by Rayth** [comment]
Post your logs anyway

**Comment by remi-reyes** [comment]
Application Starting...
Application Pre-Initalization Finished!
Checking for updates
Current tag: 0.0.2.1
Latest tag: 2022.7.4.195
New version available!
Skipping package removal - same path: Microsoft.MinecraftUWP_1.19.5.0_x64__8wekyb3d8bbwe C:\Users\José Reyes\AppData\Roaming\.minecraft_bedrock\versions\Minecraft-28d2f975-a0fc-401a-9987-9a6a117f8922
App launch finished!

**Comment by Rayth** [comment]
The launcher version you are using is no longer supported. Please use the latest release:

https://github.com/BedrockLauncher/BedrockLauncher/releases/tag/2022.7.4.195

All you do is extract the zip folder and run BedrockLauncher.exe
