### ISSUE TITLE
Unable to Change Installation Picture 

### ISSUE THREAD

**Issue by NT690** [BedrockLauncher/BedrockLauncher#256]
Even though I click the "Save" button after I change the picture of an installation, the picture is still the same

**Comment by NT690** [comment]
This is the same for both creating and editing installation data

**Comment by tresabhi** [comment]
This was fixed in #244, are you sure you're on the latest beta?

**Comment by Rayth** [comment]
It was fixed, but a release wasn't pushed with the fix. So it is fixed in the development version. Either way it's a duplicate of #244
