### ISSUE TITLE
unable to re-register the application

### ISSUE THREAD

**Issue by juliana2307** [BedrockLauncher/BedrockLauncher#257]
Application Starting...
Application Pre-Initalization Finished!
Checking for updates
Current tag: 0.0.2.1
Latest tag: 2022.7.4.195
New version available!
registering package
Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.19.1003.0_x64__8wekyb3d8bbwe because this package is not supported on the device. The package requires OS version 10.0.19041.0 or later on the Windows.Universal device family. The device is currently running OS version 10.0.18363.1256.
App re-register failed:
System.Exception: Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.19.1003.0_x64__8wekyb3d8bbwe because this package is not supported on the device. The package requires OS version 10.0.19041.0 or later on the Windows.Universal device family. The device is currently running OS version 10.0.18363.1256.
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in BedrockLauncher.ViewModels.GameManager.<DeploymentProgressWrapper>d__28.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 596
--- End of stack trace from previous location where exception was thrown ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in BedrockLauncher.ViewModels.GameManager.<ReRegisterPackage>d__27.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 562

**Comment by Rayth** [comment]
The launcher version you are using is no longer supported. Please use the latest release:

https://github.com/BedrockLauncher/BedrockLauncher/releases/tag/2022.7.4.195

All you do is extract the zip folder and run BedrockLauncher.exe

**Comment by juliana2307** [comment]
error continues
BedrockLauncher.Exceptions.PackageRegistrationFailedException: Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.19.1003.0_x64__8wekyb3d8bbwe because this package is not compatible with the device. The package requires OS version 10.0.19041.0 or later on the Windows.Universal device family. The device is currently running OS version 10.0.18363.1256.
 ---> System.Exception: Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.19.1003.0_x64__8wekyb3d8bbwe because this package is not compatible with the device. The package requires OS version 10.0.19041.0 or later on the Windows.Universal device family. The device is currently running OS version 10.0.18363.1256.
   at BedrockLauncher.Handlers.PackageHandler.DeploymentProgressWrapper(IAsyncOperationWithProgress`2 t) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 462
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 218
   --- End of inner exception stack trace ---
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 229
   at BedrockLauncher.Handlers.PackageHandler.LaunchPackage(MCVersion v, String dirPath, Boolean KeepLauncherOpen) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 59

**Comment by NT690** [comment]
that and they need to update windows to install Minecraft 1.19.1
