### ISSUE TITLE
Show Patch Notes for Previews

### ISSUE THREAD

**Issue by TheNatBoi** [BedrockLauncher/BedrockLauncher#259]
The patch notes for Minecraft Previews do not show up, and they still have a webpage (https://feedback.minecraft.net/hc/en-us/sections/360001185332-Beta-and-Preview-Information-and-Changelogs). ![2022-07-25 10_05_37-Minecraft Bedrock Launcher](https://user-images.githubusercontent.com/70166536/180834809-671cc274-fdf5-4bd3-9216-df831e008f90.png)

**Comment by Rayth** [comment]
on 2022.7.4.195 i'm getting 0 patch notes at all

**Comment by CarJem** [comment]
let me explain... Microsoft recently added a layer of authentication to the Feedback site... So it makes it impossible for me to parse the website easily now for patch notes... This also breaks it on older versions... So for the time being... We have to use mojang's launcher patch notes... which at some point should get preview builds

**Comment by Rayth** [comment]
Patch notes page is being disabled while we work on outstanding bugs. I'll look more into this in the future for getting preview and release patch notes.
