### ISSUE TITLE
"To run this application, you must install missing frameworks for .NET" issue still persists even after I have installed the required package

### ISSUE THREAD

**Issue by Finny001** [BedrockLauncher/BedrockLauncher#261]

**Comment by Rayth** [comment]
https://github.com/BedrockLauncher/BedrockLauncher/releases/tag/2022.7.4.195

follow the instructions here **carefully**

**Comment by bloodmc** [comment]
The instructions only state `.NET Desktop Runtime 6.0.6 is REQUIRED` when `ASP.NET Core Runtime 6.0.6` is also required. I would also change to 6.X as 6.0.6 is now out-of-date.
