### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by jillv46** [BedrockLauncher/BedrockLauncher#266]
CarJem Are you the creator/owner of these? https://github.com/BedrockLauncher/BedrockLauncher and https://bedrocklauncher.github.io/

**Comment by Rayth** [comment]
Yes he is. bit of a redundant question. All you'd have to do is look at the commits and find his twitter

**Comment by jillv46** [comment]
My main question is now for getting the latest version of the launcher, what's the way to get it? Do I get it from the official site or on GitHub? I'm asking because when I open the launcher it says there's an update and when I click "Download now" it installs it but after it reopens again and the message is still there. So I was thinking of manually downloading them online but idk what place to get it from

**Comment by jillv46** [comment]
> Yes he is. bit of a redundant question. All you'd have to do is look at the commits and find his twitter

My main question is now for getting the latest version of the launcher, what's the way to get it? Do I get it from the official site or on GitHub? I'm asking because when I open the launcher it says there's an update and when I click "Download now" it installs it but after it reopens again and the message is still there. So I was thinking of manually downloading them online but idk what place to get it from
