### ISSUE TITLE
Main Question

### ISSUE THREAD

**Issue by jillv46** [BedrockLauncher/BedrockLauncher#267]
Idk why you closed my other one since I didn't ask my main question. I should have made the title "General Questions" and added a "s" after "Question". I was only asking if he was the owner since every social the website showed I got no reply (especially Twitter). Anyway for my main question is for getting the latest version of the launcher, what's the way to get it? Do I get it from the official site or on GitHub? I'm asking because when I open the launcher it says there's an update and when I click "Download now" it installs it but after it reopens again and the message is still there. So I was thinking of manually downloading them online but idk what place to get it from

**Comment by Rayth** [comment]
https://github.com/BedrockLauncher/BedrockLauncher/releases/tag/2022.7.4.195 this is the latest version. Because it's marked as a pre-release github doesn't show it as latest version. It doesn't have an auto updater anymore and no installer.

**Comment by jillv46** [comment]
> https://github.com/BedrockLauncher/BedrockLauncher/releases/tag/2022.7.4.195 this is the latest version. Because it's marked as a pre-release github doesn't show it as latest version. It doesn't have an auto updater anymore and no installer.

If I downloaded it from the official site, would it get the pre-release or the latest release one?

**Comment by Rayth** [comment]
You'll get the previous version 0.0.2.1 or something. It's pending an update on the site.

**Comment by jillv46** [comment]
As for the pre-release, would it have any bugs etc or is it the same stable as the latest release one?

**Comment by Rayth** [comment]
It's more stable. The "latest release" one doesn't support previews and if you click latest release it will try loading preview and fail. This new one is completely stable with less bugs, runs faster and smoother, and has full preview support.

**Comment by jillv46** [comment]
As for NET 6.0 which one do I get? I clicked on the link but there's a lot of options. I have windows laptops

**Comment by Rayth** [comment]
The page with the download link tells you exactly what to get.

**Comment by jillv46** [comment]
It shows ".NET Desktop Runtime 6.0.6 is REQUIRED" so the 6.0.7 won't work right?

**Comment by jillv46** [comment]
And would the desktop one work for laptops?
![image](https://user-images.githubusercontent.com/29643271/182977733-abe7b0fc-35c6-4892-900b-8e25d1e551f3.png)

**Comment by Rayth** [comment]
6.0.7 is just an update it'll work fine. Which one you click there depends on if you have an ARM based processor, 64bit or 32bit. If you can run the launcher, you want the x64 one cause that's 64 bit

**Comment by jillv46** [comment]
My laptop is 64 bit but there's 2 for 64, there's "Arm64" and "64"

**Comment by Rayth** [comment]
Both different. it'll be x64

**Comment by jillv46** [comment]
And even it says "Desktop" it will still work for laptops?

**Comment by Rayth** [comment]
Yes it doesn't matter. It's all windows.

**Comment by jillv46** [comment]
So I'm going to select the ".NET Desktop Runtime 6.0.7" and then "x64"

**Comment by Rayth** [comment]
Yes

**Comment by jillv46** [comment]
> So I'm going to select the ".NET Desktop Runtime 6.0.7" and then "x64"

I'm curious what the arm64 one is used for if I have to get the normal x64 one

**Comment by Rayth** [comment]
https://docs.microsoft.com/en-us/answers/questions/10614/what-is-the-difference-between-x64-and-arm64.html

**Comment by jillv46** [comment]
Ok so I downloaded it but when I try to install the Bedrock Launcher I get this message
![image](https://user-images.githubusercontent.com/29643271/182979678-ea6284c2-72c6-44db-ad98-9fe96a1e80ea.png)

**Comment by TheNatBoi** [comment]
[#195 (comment)](https://github.com/BedrockLauncher/BedrockLauncher/issues/195#issuecomment-1103371313)
follow this comment

**Comment by jillv46** [comment]
> [#195 (comment)](https://github.com/BedrockLauncher/BedrockLauncher/issues/195#issuecomment-1103371313) follow this comment

The thing that is needed to download in the comment seems different than what is in this video https://www.youtube.com/watch?v=oB_ITqzYBoQ&ab_channel=FKbajwa

**Comment by jillv46** [comment]
> > [#195 (comment)](https://github.com/BedrockLauncher/BedrockLauncher/issues/195#issuecomment-1103371313) follow this comment
> 
> The thing that is needed to download in the comment seems different than what is in this video https://www.youtube.com/watch?v=oB_ITqzYBoQ&ab_channel=FKbajwa

I couldn't find a video for Bedrock Launcher and I know it says "HandBrake" but the error is still the same for me besides it saying "Handbrakes" on the top right instead of "BedrockLauncher.exe"

**Comment by tresabhi** [comment]
@jillv46 The process is simplified for bedrock launcher in the comment @TheNatBoi mentioned.

**Comment by jillv46** [comment]
@Rayth @tresabhi @TheNatBoi Also how do I make it so all my worlds are in 1 profile like how the bedrock launcher is? When I make a new installation it makes a new folder and all my worlds aren't synced over

**Comment by Rayth** [comment]
> @Rayth @tresabhi @TheNatBoi Also how do I make it so all my worlds are in 1 profile like how the bedrock launcher is? When I make a new installation it makes a new folder and all my worlds aren't synced over

You would have to goto the save location and manually copy them. The reason they're not copied automatically is because of version incompatibility. Once you open a world in a higher game version, you can't play that world on a lower version.
