### ISSUE TITLE
App re-register failed  (spanish)

### ISSUE THREAD

**Issue by Brichios** [BedrockLauncher/BedrockLauncher#268]
Application Starting...
Application Pre-Initalization Finished!
Checking for updates
Current tag: 0.0.2.1
Latest tag: 2022.7.4.195
New version available!
Registering package
Deployment progress: Processing 0%
Deployment failed: Windows no puede instalar el paquete Microsoft.MinecraftWindowsBeta_1.19.2022.0_x64__8wekyb3d8bbwe porque depende de un marco que no se encontró. Proporcione el marco "Microsoft.Services.Store.Engagement" publicado por "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", con arquitectura de procesador neutra o x64 y versión mínima 10.0.1610.0, junto con este paquete para instalarlo. Los marcos con el nombre "Microsoft.Services.Store.Engagement" instalados actualmente son: {Microsoft.Services.Store.Engagement_10.0.18101.0_x64__8wekyb3d8bbwe Microsoft.Services.Store.Engagement_10.0.18101.0_x86__8wekyb3d8bbwe}
App re-register failed:
System.Exception: Deployment failed: Windows no puede instalar el paquete Microsoft.MinecraftWindowsBeta_1.19.2022.0_x64__8wekyb3d8bbwe porque depende de un marco que no se encontró. Proporcione el marco "Microsoft.Services.Store.Engagement" publicado por "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", con arquitectura de procesador neutra o x64 y versión mínima 10.0.1610.0, junto con este paquete para instalarlo. Los marcos con el nombre "Microsoft.Services.Store.Engagement" instalados actualmente son: {Microsoft.Services.Store.Engagement_10.0.18101.0_x64__8wekyb3d8bbwe Microsoft.Services.Store.Engagement_10.0.18101.0_x86__8wekyb3d8bbwe}
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en BedrockLauncher.ViewModels.GameManager.<DeploymentProgressWrapper>d__28.MoveNext() en D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:línea 596
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en BedrockLauncher.ViewModels.GameManager.<ReRegisterPackage>d__27.MoveNext() en D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:línea 562

**Comment by Rayth** [comment]
The launcher version you are using is no longer supported. Please use the latest release:

https://github.com/BedrockLauncher/BedrockLauncher/releases/tag/2022.7.4.195

All you do is extract the zip folder and run BedrockLauncher.exe
