### ISSUE TITLE
Installer Download speeds are incredibly slow.

### ISSUE THREAD

**Issue by CubeIR** [BedrockLauncher/BedrockLauncher#27]
On a 16mb/ps connection, takes almost forever (I assume It's downloading with speed of 15 to 30 kbps), waited a few hours it was half way, a little disruption & all downloaded content was gone as I had to start it over, I'm unable to install Bedrock launcher via installer

**Comment by CoolAbhi1290** [comment]
The reason why this happens is that the installer directly pulls the build files from GitHub as a `.zip` file. And when we update the existing build files, we remove all the existing ones and download the latest build files which are significantly slower.

**Comment by CoolAbhi1290** [comment]
This was fixed in the [latest public beta](https://github.com/BedrockLauncher/BedrockLauncher/releases/tag/0.0.2.1)

 > Removes x86, ARM/ARM64, and AnyCPU Support (the launcher didn't work on these platforms 100% anyways)
