### ISSUE TITLE
Question(s)

### ISSUE THREAD

**Issue by Fireworkstars46** [BedrockLauncher/BedrockLauncher#270]
Is it possible for me to use this launcher on iOS?

**Comment by Rayth** [comment]
Please see the FAQ https://bedrocklauncher.github.io/faq

![image](https://user-images.githubusercontent.com/4260473/184465751-8fecc14e-88ce-454e-b6da-f3b1042f3ab1.png)

**Comment by Fireworkstars46** [comment]
Would iOS support be added in the future?

**Comment by Rayth** [comment]
Not as far as I'm aware. this is primarily a version switcher for windows

**Comment by Fireworkstars46** [comment]
I'm asking cause I was hoping for a easier way to downgrade versions on it.
