### ISSUE TITLE
launcher bedrock problem 

### ISSUE THREAD

**Issue by Harryelgranuja-2** [BedrockLauncher/BedrockLauncher#272]
I have this problem every time I try to start the game
[The problem.txt](https://github.com/BedrockLauncher/BedrockLauncher/files/9334782/The.problem.txt)

**Comment by Rayth** [comment]
Can you make sure you're using the latest version of the launcher:
https://github.com/BedrockLauncher/BedrockLauncher/releases/tag/2022.7.4.195

Also ensure you are running in Admin mode.

**Comment by Rayth** [comment]
Just double checked your log. You launcher version is out of date. Please see link above and create a new issue if this persists
