### ISSUE TITLE
Can't play full game

### ISSUE THREAD

**Issue by majorsopa** [BedrockLauncher/BedrockLauncher#273]
I own the full game but cannot log in to my account and have access to anything outside the trial version.

**Comment by tresabhi** [comment]
Can you provide a log?

**Comment by majorsopa** [comment]
@tresabhi where do I find my logs?

**Comment by tresabhi** [comment]
In the installation directory

**Comment by majorsopa** [comment]
[Log_2022-08-17_01-35-48.log](https://github.com/BedrockLauncher/BedrockLauncher/files/9365397/Log_2022-08-17_01-35-48.log)

**Comment by Rayth** [comment]
This isn't a launcher error. It's an issue with logging in to your account. Make sure you have the Xbox app installed on your PC so it pops up to login but other than that we cannot assist with this.
