### ISSUE TITLE
Error when attempting to launch.

### ISSUE THREAD

**Issue by SpawnMaker** [BedrockLauncher/BedrockLauncher#274]
When attempting to open the launcher, I receive a pop up box stating, "To run this application, you must install missing frameworks for .NET.  Would you like to download it now?". When I click yes, absolutely nothing happens. Previously, with a different pop-up, it would bring me to a new tab where I could download something.

**Comment by Rayth** [comment]
Can you provide a log file?

dot net downloads are located at https://dotnet.microsoft.com/en-us/download/dotnet/6.0

If you're on the latest version you'll need desktop runtime and asp.net

**Comment by MinGGeMG-sourcecode** [comment]
I can't find the log file.
When I tried to run it, he popped up this window.
![image](https://user-images.githubusercontent.com/49353343/185306236-8a06b764-c63c-45b7-ae0b-c01d8f32c257.png)
But I already have the corresponding program installed.
![无标题](https://user-images.githubusercontent.com/49353343/185307243-b0e06a58-112c-4690-a9b9-9508b44d2f3f.png)

**Comment by tresabhi** [comment]
@SpawnMaker @MinGGeMG-sourcecode 
Try following instructions here: [#195 (comment)](https://github.com/BedrockLauncher/BedrockLauncher/issues/195#issuecomment-1103371313)

**Comment by MinGGeMG-sourcecode** [comment]
![image](https://user-images.githubusercontent.com/49353343/185310810-60e7b315-45e3-4a35-882b-387ff6ef86df.png)
![image](https://user-images.githubusercontent.com/49353343/185306236-8a06b764-c63c-45b7-ae0b-c01d8f32c257.png)
The problem has not been solved.

**Comment by Rayth** [comment]
You clearly haven't followed all the instructions then. Most likely missing the ASP.Net runtime like i mentioned.

Log file can either be found in the folder where the launcher is, or where you set the launcher to read your profiles.

**Comment by VanillaChan6571** [comment]
"You clearly haven't followed all the instructions then." ....blah blah blah... I shouldn't need to jump through hoops of github issues to find what to install whats needed. This is peek of frustration and anger. Recommend just adding "install needed dependencies" inside the launcher installer. FFS
