### ISSUE TITLE
[Enhancement] DLL Injection

### ISSUE THREAD

**Issue by Rayth** [BedrockLauncher/BedrockLauncher#275]
Add an option in "settings" where users could specify a DLL to be injected into Minecraft. This would allow us to use things like OnixClient without having to use 2 launchers.

https://github.com/notcarlton/OnixLauncher

Current launcher that Onix Client uses which includes the injection stuff, all in c#.

**Comment by rothgar** [comment]
What other launcher do you use to be able to inject DLLs?
