### ISSUE TITLE
How do i uninstall Minecraft bedrock launcher?

### ISSUE THREAD

**Issue by TeamHydraHp** [BedrockLauncher/BedrockLauncher#277]
I recently installed this Minecraft bedrock launcher just to try it out for fun. After I reviewed the application, I wanted to uninstall it to go back to the official application, now every time I try to uninstall it, it doesn't get deleted. When I uninstall Minecraft and reinstall it, it continues to go to the 'Minecraft bedrock layout' with the music in the background and whatnot. Can someone please explain to me how I am able to revert to the official application?

**Comment by Rayth** [comment]
You've installed an old version of the launcher. The new version doesn't have an installer, it's completely portable now. Simply goto where you installed it and delete the folder. The music is the game itself, not the launcher.
