### ISSUE TITLE
Minecraft Beta versions fail to launch

### ISSUE THREAD

**Issue by AshUosis** [BedrockLauncher/BedrockLauncher#280]
Minecraft Beta versions fail to launch
![m](https://user-images.githubusercontent.com/107533626/186594661-39066d13-fed3-4ef0-8d8c-e1674245fbb7.png)

**Comment by Rayth** [comment]
You're using an out-dated launcher. Please download the latest Pre-Release:

https://github.com/BedrockLauncher/BedrockLauncher/releases/tag/2022.8.23.79

**Comment by AshUosis** [comment]
> You're using an out-dated launcher. Please download the latest Pre-Release:
> 
> https://github.com/BedrockLauncher/BedrockLauncher/releases/tag/2022.8.23.79

When I downloaded it, and tried to play a beta version, It launches the latest release
