### ISSUE TITLE
App re-register failed

### ISSUE THREAD

**Issue by tsheeley** [BedrockLauncher/BedrockLauncher#282]
## Log
```
Application Starting...
Application Pre-Initalization Finished!
Checking for updates
Current tag: 0.0.2.1
Latest tag: 2022.8.23.79
New version available!
Download start
Resolved download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/b3a67bc2-b035-4baa-87b5-47aaf321ec62?P1=1661550184&P2=404&P3=2&P4=RX2YmBSyNnvxzsGoOW2BCJO%2fE9DNPhVS3mEWXMwcpbFC6bZh0bm5mLCvkV0075MvzSjE9WzxzZyzr0Q68yJFnQ%3d%3d
Actual download started
Download complete
Extraction started
Extracted successfully
Removing package: Microsoft.MinecraftUWP_1.14.6005.0_x64__8wekyb3d8bbwe
Package is in development mode
Deployment progress: Processing 0%
Deployment progress: Processing 0%
Deployment progress: Processing 100%
Deployment done: Completed
Removal of package done: Microsoft.MinecraftUWP_1.14.6005.0_x64__8wekyb3d8bbwe
Registering package
Deployment progress: Processing 0%
Deployment progress: Processing 1%
Deployment progress: Processing 2%
Deployment progress: Processing 49%
Deployment progress: Processing 51%
Deployment progress: Processing 98%
Deployment progress: Processing 98%
Deployment progress: Processing 100%
Deployment done: Completed
App re-register done!
App launch finished!
Registering package
Deployment progress: Processing 0%
Deployment progress: Processing 1%
Deployment progress: Processing 2%
Deployment progress: Processing 49%
Deployment progress: Processing 51%
Deployment progress: Processing 98%
Deployment progress: Processing 98%
Deployment progress: Processing 100%
Deployment done: Completed
App re-register done!
App launch finished!
Download start
Resolved download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/c204c051-22c5-4fda-9b7f-f0847f580bc6?P1=1661550799&P2=404&P3=2&P4=nbXj0MLtqoHPq37ROoa0K93s2gT1guWwyHyZLmXhbNrCcQJ8osGBHqnhuVDE2e6nUa0dqobIc1bvsr9uIoAuHg%3d%3d
Actual download started
Download complete
Extraction started
Extracted successfully
Registering package
Deployment progress: Processing 0%
Deployment failed: Windows cannot install package Microsoft.MinecraftWindowsBeta_1.19.2020.0_x64__8wekyb3d8bbwe because it has version 1.19.2020.0. A higher version 1.19.2023.0 of this package is already installed.
App re-register failed:
System.Exception: Deployment failed: Windows cannot install package Microsoft.MinecraftWindowsBeta_1.19.2020.0_x64__8wekyb3d8bbwe because it has version 1.19.2020.0. A higher version 1.19.2023.0 of this package is already installed.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<DeploymentProgressWrapper>d__28.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 596
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<ReRegisterPackage>d__27.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 562
```

## Original issue content

Pretty much the title... is the current release on the main website working with Windows 11?

There is nothing special about my machine... ASUS ROG... 16 gb RAM... Nvidia RTX 3060... standard Windows 11 install with my profile set as Admin and the developer flag turned on to install programs from any source.

I've already been playing the current Bedrock version from the MS store, but one of the Java-Bedrock crossplay servers I play on is lagging on updating their Geyser for 1.19.21, so I figured I would give this a try.

The install went smoothly and I had it back up my existing install.

I setup a previous version... hit Play... it looked like it downloaded, but then nothing happened... restarted several times... no change.

I then tried to uninstall the Bedrock Launcher from Add/Remove Programs... but the entry stayed... rebooted... still in there.

I then reinstalled Bedrock from the official launcher... but now, whenever I open MC, I have to hit the Log In button every time.

Will the new Lite version in development work better with Win11?

Any help on getting this resolved would be appreciated.

Thanks!

**Comment by tresabhi** [comment]
Windows 11 is currently not supported. However, it is likely that Windows 11 is not to blame for this issue. Please provide a log (found in the installation directory) so that we can resolve this issue.

**Comment by tsheeley** [comment]
I manually deleted the directory after uninstalling... I'll have to reinstall to recreate the logs. 

Please update the FAQ on the website then if Win11 is not supported... as I did check that first. While I understand it does say "Only Windows 10"... it does go on to say Win11 if MC can run on it.

![Screenshot 2022-08-26 095931](https://user-images.githubusercontent.com/31299310/186955483-d53e40a1-afb7-4a23-b102-809af82acb7c.png)

**Comment by tsheeley** [comment]
I'm doing some more testing... I went back to the last 1.14... and that one worked on the same Win 11 laptop.

The issue seems to be with the 1.19.20 series in general. So far only the 1.19.20.20 version has generated a crash log... the ones after that just don't do anything.

I'm working from home... so testing is slow, but I'm going through versions to see what works and doesn't.

I'll follow-up with logs soon.

**Comment by tsheeley** [comment]
Here are my findings so far...

Only 1.19.20.20 and .22 generated crash logs... see attached. The .23 and .24 versions just completely fail and do not seem to create a log.

I did also notice that switching to the Latest Release, and also manually selecting 1.29.21, it tries to install the 1.19.30 Betas and lists that as the version in the Installations tab, even when manually selecting .21.

It's also same for the Recovery Data installation... it goes by fast in the status bar, but I can see it also tries to install the beta for that too.

What's the upgrade path for the new Lite version if I wanted to try that to be able to access the Latest Releases? I'm seeing that the main release on the website is from 2021, so I imagine the Lite would be better?

[1.19.20.22 - Log.txt](https://github.com/BedrockLauncher/BedrockLauncher/files/9435275/1.19.20.22.-.Log.txt)
[1.19.20.20 - Log.txt](https://github.com/BedrockLauncher/BedrockLauncher/files/9435276/1.19.20.20.-.Log.txt)
.

**Comment by tresabhi** [comment]
This is a known issue on all versions of Windows. Thanks for providing a log.

**Comment by tsheeley** [comment]
Sure thing. Glad I could help.

For the new Lite version... does that still have the issue with installing the Betas for the Current Main Release?

If not, what's the ideal migration path between the two versions?

**Comment by tsheeley** [comment]
Final results of my testing...

I took a chance and just blindly tried out Lite... it works perfectly. I didn't need to do anything for it to detect the 2021 install. 

I'm seeing now that the version selector tags the ones that were previously failing as Previews and I can happily report that selecting Latest Release properly installs the current version.

Additionally, there are no problems with staying logged in when switching versions.

Thanks for the help!

(maybe you should switch out the link on the main site?... the Lite version seems to be working great so far. just a thought. i'm sure it would cut down on similar reports.)

**Comment by tresabhi** [comment]
Oh, you were using the old version. I missed that. The old builds are not supported; my bad.

**Comment by tsheeley** [comment]
Not a problem... like I said though, the website says that the old version should work as long as MC works for Windows 11.

It might be a good idea to amend that and possibly add a link to the main page for the Lite version for Win11 users... just an idea.

Either way, the Lite version fixed it for me and everything is working perfectly now.

Thanks again for the assist!
