### ISSUE TITLE
App re register failed :(

### ISSUE THREAD

**Issue by SAB236YT** [BedrockLauncher/BedrockLauncher#285]
got the log 
[Log.txt](https://github.com/BedrockLauncher/BedrockLauncher/files/9471913/Log.txt)

**Comment by Rayth** [comment]
The version of the launcher you are using (0.0.2.1) is no longer supported.

Please download the latest Pre-Release: https://github.com/BedrockLauncher/BedrockLauncher/releases/tag/2022.8.23.79

Simply extract the folder and run BedrockLauncher.exe (no installer required)

**Comment by SAB236YT** [comment]
i am using the lite!

**Comment by SAB236YT** [comment]
[Log_2022-09-02_16-58-13.log](https://github.com/BedrockLauncher/BedrockLauncher/files/9478933/Log_2022-09-02_16-58-13.log)
here is the log
