### ISSUE TITLE
Unable to use Launcher

### ISSUE THREAD

**Issue by PierogiPL** [BedrockLauncher/BedrockLauncher#288]
![image](https://user-images.githubusercontent.com/83957603/188227799-14e878ee-8d5b-4fbf-ba48-9de8425a6303.png)
This window appears when i try to open the launcher clicking on it doesent do anything for me.

**Comment by TheNatBoi** [comment]
https://github.com/BedrockLauncher/BedrockLauncher/issues/195#issuecomment-1103371313
follow these instructions

**Comment by PierogiPL** [comment]
thanks

**Comment by PierogiPL** [comment]
![image](https://user-images.githubusercontent.com/83957603/188241918-e3f10349-7ad3-4307-b778-50caf4cfccf8.png)
i get this after launch

**Comment by TheNatBoi** [comment]
Could you post a log file(It's located in data\logs and make sure it's the correct date and time)? Also check if you are on the correct version, if not the download it from here https://github.com/BedrockLauncher/BedrockLauncher/releases/download/2022.8.23.79/release.zip

**Comment by tresabhi** [comment]
Please use the lite version as it does not use those dependencies

**Comment by PierogiPL** [comment]
BedrockLauncher.Exceptions.AppLaunchFailedException: Specified cast is not valid.
 ---> System.InvalidCastException: Specified cast is not valid.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at WinRT.IObjectReference.As[T](Guid iid)
   at WinRT.BaseActivationFactory._As(Guid iid)
   at WinRT.ActivationFactory`1.As(Guid iid)
   at Windows.System.AppDiagnosticInfo.Make___objRef_global__Windows_System_IAppDiagnosticInfoStatics2()
   at Windows.System.AppDiagnosticInfo.get__objRef_global__Windows_System_IAppDiagnosticInfoStatics2()
   at Windows.System.AppDiagnosticInfo.RequestInfoForPackageAsync(String packageFamilyName)
   at BedrockLauncher.Handlers.PackageHandler.LaunchPackage(MCVersion v, String dirPath, Boolean KeepLauncherOpen) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 56
   --- End of inner exception stack trace ---
and no log file was created

**Comment by PierogiPL** [comment]
[Log_2022-09-03_17-14-05.log](https://github.com/BedrockLauncher/BedrockLauncher/files/9482890/Log_2022-09-03_17-14-05.log)
ok turns out there was in fact a file but the view report button didnt recongize that

**Comment by Rayth** [comment]
Make sure you have the .NET Desktop Runtime installed 
https://dotnet.microsoft.com/en-us/download/dotnet/6.0

**Comment by PierogiPL** [comment]
> Make sure you have the .NET Desktop Runtime installed https://dotnet.microsoft.com/en-us/download/dotnet/6.0

i have

**Comment by Rayth** [comment]
do you have any non-english characters in your PC username or installation or profile name on the launcher?

**Comment by PierogiPL** [comment]
> do you have any non-english characters in your PC username or installation or profile name on the launcher?

No, english characters only

**Comment by PierogiPL** [comment]
> Please use the lite version as it does not use those dependencies

where do i find it? i dont see it no where.

**Comment by PierogiPL** [comment]
> Please use the lite version as it does not use those dependencies

nevermind
