### ISSUE TITLE
Method for registering the launcher as an actual program

### ISSUE THREAD

**Issue by Furzide** [BedrockLauncher/BedrockLauncher#298]
the latest versions dont come with an installer therefore it runs standalone in it's own folder, is there a way to manually install it in the same way previous versions were installed, where windows recognises it as an actual app that can be uninstalled whenever?

**Comment by tresabhi** [comment]
When registering an app in Windows, it is required to mention an executable that uninstalls the app (`uninstall.exe` that deletes the installation directory). Since the lite version does not ship with it, this is possible. Do it manually.
