### ISSUE TITLE
ошибка

### ISSUE THREAD

**Issue by Puma221** [BedrockLauncher/BedrockLauncher#299]
![image](https://user-images.githubusercontent.com/115267110/194592158-55f1ebe2-ebc9-4ce9-8f6d-07e257947e24.png)

**Comment by Puma221** [comment]
всё установлено

**Comment by TheNatBoi** [comment]
[#195 (comment)](https://github.com/BedrockLauncher/BedrockLauncher/issues/195#issuecomment-1103371313)
follow this comment

**Comment by Rayth** [comment]
> [#195 (comment)](https://github.com/BedrockLauncher/BedrockLauncher/issues/195#issuecomment-1103371313) follow this comment

they need the desktop runtime which is linked on the download page.
