### ISSUE TITLE
Add optifine for EVERY version if u can

### ISSUE THREAD

**Issue by DesertSoldier43** [BedrockLauncher/BedrockLauncher#3]
That would be cool if you could add optifine meaning FOV changer with that smooth glide, FPS booster. I would be so greatful.

**Comment by DesertSoldier43** [comment]
also please add multiple instances of MCBE meaning like 2 windows of MCBE 1.17.0

**Comment by DesertSoldier43** [comment]
Wdym Wont Fix

**Comment by Rayth** [comment]
> Wdym Wont Fix

This is an app for launching a selected version of bedrock edition, not for adding extra things into it (optifine/fov changer).
