### ISSUE TITLE
couldn't uninstall the launcher

### ISSUE THREAD

**Issue by lonewolf750** [BedrockLauncher/BedrockLauncher#300]
attached google drive video [link](https://drive.google.com/file/d/1X4BQJjyps_QdhKNGSriwgISsvKjHPi15/view?usp=sharing) of my issue someone take a look into it and get it sorted out for me pls or tell me the steps to get rid the application

**Comment by Rayth** [comment]
Well you clearly used the old launcher since the new ones dont have installers, but basically you need to goto wherever it is installed and just delete the folder (Likely program files (x86))

It won't remove the entry from control panel but it will no longer be on your computer.
