### ISSUE TITLE
0.13 and 0.1 and all *0* versions are not opening

### ISSUE THREAD

**Issue by animasyon-kanali-official** [BedrockLauncher/BedrockLauncher#304]
i tried it it is gaving cursh note but when i press to chrush note it says this notepad is not real wanna create a new note?  it is saying this what can i do or is it a glitch?

**Comment by Rayth** [comment]
Those early versions aren't on the microsoft store so can't be installed.

**Comment by animasyon-kanali-official** [comment]
then why is there an version called 0.13

**Comment by Rayth** [comment]
because it lists MCPE versions. Have you checked if 1.0 or 1.1 work? They officially got made into Bedrock for 1.2 so without testing myself, I expect that to be the first version that *may* work
