### ISSUE TITLE
Startup failures

### ISSUE THREAD

**Issue by MrDexstor** [BedrockLauncher/BedrockLauncher#307]
Hello, I downloaded your launcher, unpacked it.
I started running the launcher and he asked me to install it."Net 6.0.9" , I did it and after that the launcher did not start.
I checked the task manager during startup and the launcher just appears there for 1 second and then disappears

**Comment by tresabhi** [comment]
Duplicate of #307

**Comment by tresabhi** [comment]
Duplicate of #306

My bad
