### ISSUE TITLE
Windows Server Edition

### ISSUE THREAD

**Issue by nanderer** [BedrockLauncher/BedrockLauncher#309]
Hi, could you make it work on windows server edition, here some screenshots of how it dose not work on windows server 2019, i also found no other way to make it work there
![grafik](https://user-images.githubusercontent.com/45161625/198146196-d1501b65-50e2-4549-b74d-ac36d5ef592c.png)
![grafik](https://user-images.githubusercontent.com/45161625/198146160-b121ec8b-e7b8-4fd1-987d-ba5a28d5f104.png)

thanks a lot in advance

**Comment by Rayth** [comment]
Not possible because windows server 2019 doesn't work with the Microsoft
store which is a requirement for this.
