### ISSUE TITLE
It doesn't load the game.

### ISSUE THREAD

**Issue by DuckZGamer9122** [BedrockLauncher/BedrockLauncher#31]
Yes I am aware that there is an issue like this already present but I saw no reply that could help and it was 4 days ago.

The launcher just says launching but nothing happens it just does that in an continuous loop with no reason. 

Any solutions? It seems like an terrific launcher but I will have to digress if this isn't solved.

**Comment by CarJem** [comment]
I promise, an Update is coming... but don't make duplicate issues of #25 plz
