### ISSUE TITLE
BedrockLauncher.exe doesn't open

### ISSUE THREAD

**Issue by Lithout** [BedrockLauncher/BedrockLauncher#312]
As much as I try to execute the program it doesn't work, I've installed .NET and everything required, when I execute the program nothing happens

**Comment by Rayth** [comment]
does a log file generate inside the Data/Logs folder?

Do you have administrative priveliges?

**Comment by Lithout** [comment]
Where can I find that folder?

Yes, I have admin priviliges

**Comment by Rayth** [comment]
in the same folder as BedrockLauncher.exe

**Comment by Lithout** [comment]
The only folder that's there is 'runtimes'

**Comment by Rayth** [comment]
did you EXTRACT the zip folder first or just double click it then run it? And was it definitely the .net DESKTOP runtime you installed? it's not the first one on the download page
