### ISSUE TITLE
Closes after pressing play

### ISSUE THREAD

**Issue by lBEASTl** [BedrockLauncher/BedrockLauncher#316]
I have installed everything including after the first time of pressing play but when i try to press it again it just crashes/closes

**Comment by Rayth** [comment]
share log file please. You shouldn't have had to "install" anything regarding the launcher, apart from the .net desktop runtime dependency

**Comment by staffordrn** [comment]
Same issue. Here is the log file:
[Log_2022-11-18_16-32-37.log](https://github.com/BedrockLauncher/BedrockLauncher/files/10044993/Log_2022-11-18_16-32-37.log)

**Comment by lBEASTl** [comment]
sorry im really late but the file is 
[Log_2022-11-24_17-37-08.log](https://github.com/BedrockLauncher/BedrockLauncher/files/10086599/Log_2022-11-24_17-37-08.log)

**Comment by Rayth** [comment]
You need to install the .NET Desktop runtime: https://dotnet.microsoft.com/en-us/download/dotnet/6.0

**Comment by FERFAIL-TXZ** [comment]
Hey, I see this thread is very old but I have the same issue. I have already downloaed the latest and the 6.0 dotnet versions and when I press "Play", it inmediatly crash. I have Minecraft Java & Bedrock bought and linked to the launcher.

**Comment by Rayth** [comment]
> Hey, I see this thread is very old but I have the same issue. I have already downloaed the latest and the 6.0 dotnet versions and when I press "Play", it inmediatly crash. I have Minecraft Java & Bedrock bought and linked to the launcher.

this issue is from before we launched the lite version. Please either create a new issue, or open a support ticket on discord for faster support - link on http://bedrocklauncher.github.io
