### ISSUE TITLE
Program Closes

### ISSUE THREAD

**Issue by Ultracat3** [BedrockLauncher/BedrockLauncher#318]
Everytime I try to download the game itself, the program just closes, what can I do? I've tried reinstalling the launcher but it still happens

**Comment by Rayth** [comment]
Can you upload your log file. You will find it in the Data/Logs folder

**Comment by Ultracat3** [comment]
> Can you upload your log file. You will find it in the Data/Logs folder

How can I upload it?

**Comment by Rayth** [comment]
drag it into the comment box

**Comment by Ultracat3** [comment]
[Log_2022-11-29_17-32-28.log](https://github.com/BedrockLauncher/BedrockLauncher/files/10115113/Log_2022-11-29_17-32-28.log)

**Comment by Rayth** [comment]
Couple of things:
1- Are you on windows 10 or 11?
2- Have you installed the .NET Desktop Runtime from https://dotnet.microsoft.com/en-us/download/dotnet/6.0 (Make sure it is DESKTOP not ASP or SDK)
3- Check if you have any windows updates available

**Comment by Ultracat3** [comment]
> Couple of things: 1- Are you on windows 10 or 11? 2- Have you installed the .NET Desktop Runtime from https://dotnet.microsoft.com/en-us/download/dotnet/6.0 (Make sure it is DESKTOP not ASP or SDK) 3- Check if you have any windows updates available

I'm in windows 10
Installing it
I don't have any

**Comment by Ultracat3** [comment]
I've downloaded the thing and it still closes :(

**Comment by Rayth** [comment]
join https://discord.gg/Ar5SRBZcqn
read this: https://discord.com/channels/841497197594017842/1046507417820725288
