### ISSUE TITLE
program closes

### ISSUE THREAD

**Issue by argon57bbb** [BedrockLauncher/BedrockLauncher#319]
when press play launcher closes. when try to install giving this error
[er.txt](https://github.com/BedrockLauncher/BedrockLauncher/files/10116298/er.txt)
repair in settings->versions doesnt work too
oc win 10
19044.2251
21H2
.net desktop runtime is instaled
dont have avaible updates in win updates
[Log_2022-11-30_00-30-37.log](https://github.com/BedrockLauncher/BedrockLauncher/files/10116499/Log_2022-11-30_00-30-37.log)

**Comment by Rayth** [comment]
you must have a windows update cause the latest win10 version is 22H2. However, the error you've posted means you don't have the correct runtime installed. You need to make sure you get the desktop, which isn't the top of that page. don't get SDK or ASP.net runtimes

**Comment by argon57bbb** [comment]
i installed desktop 64 bit and then 32 bit. nothing changes.
![image](https://user-images.githubusercontent.com/119447021/204721605-5342806c-61e2-4bd5-a496-ebf3df542a6a.png)

**Comment by Rayth** [comment]
join https://discord.gg/Ar5SRBZcqn
read this: https://discord.com/channels/841497197594017842/1046507417820725288

there is additional solutions to this problem
