### ISSUE TITLE
No installer for latest release

### ISSUE THREAD

**Issue by FayneAldan** [BedrockLauncher/BedrockLauncher#32]
There is no installer.exe included for the latest release, breaking the download link in the readme.

**Comment by CoolAbhi1290** [comment]
The installer is now separate from the build. The installer will install the latest build automatically.

**Comment by FayneAldan** [comment]
The download link in the readme needs to be updated.

**Comment by CoolAbhi1290** [comment]
It does not, it makes the user download the latest installer anyways
