### ISSUE TITLE
App Registration Failed :(

### ISSUE THREAD

**Issue by iiJhas** [BedrockLauncher/BedrockLauncher#325]
**(srry x my english)**

Hello. i have been using Bedrock Launcher since some months ago, but now i have this error that i can't resolve.
I tried changing the **Windows.ApplicationModel.Store.dll** , deleting the **.minecraft_bedrock** million of times, restarting pc and nothing.

Here's the crash report and thanks x helps.

_BedrockLauncher.Exceptions.PackageRegistrationFailedException: Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.19.2002.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.Services.Store.Engagement" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 10.0.1610.0, along with this package to install. The frameworks with name "Microsoft.Services.Store.Engagement" currently installed are: {Microsoft.Services.Store.Engagement_10.0.19011.0_x64__8wekyb3d8bbwe Microsoft.Services.Store.Engagement_10.0.19011.0_x86__8wekyb3d8bbwe}
 ---> System.Exception: Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.19.2002.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.Services.Store.Engagement" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 10.0.1610.0, along with this package to install. The frameworks with name "Microsoft.Services.Store.Engagement" currently installed are: {Microsoft.Services.Store.Engagement_10.0.19011.0_x64__8wekyb3d8bbwe Microsoft.Services.Store.Engagement_10.0.19011.0_x86__8wekyb3d8bbwe}
   at BedrockLauncher.Handlers.PackageHandler.DeploymentProgressWrapper(IAsyncOperationWithProgress`2 t) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 511
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 264
   --- End of inner exception stack trace ---
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 275
   at BedrockLauncher.Handlers.PackageHandler.InstallPackage(MCVersion v, String dirPath) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 83_
![image](https://user-images.githubusercontent.com/120413252/207127619-2dd77a7c-30e3-4b4d-a742-2798e262e1c5.png)

**Comment by Rayth** [comment]
https://discord.com/channels/841497197594017842/1046507417820725288 read this post on the discord. it has 2 ways to fix this issue.

**Comment by iiJhas** [comment]
> https://discord.com/channels/841497197594017842/1046507417820725288 read this post on the discord. it has 2 ways to fix this issue.

this is funny bc HASJDHASJH
![image](https://user-images.githubusercontent.com/120413252/207144017-50a14ab5-eb0f-42c5-96b8-0d4a78d0ea63.png)
