### ISSUE TITLE
Package install failed IDK if i already reported this...

### ISSUE THREAD

**Issue by SAB236YT** [BedrockLauncher/BedrockLauncher#327]
[Log_2022-12-14_21-19-09.log](https://github.com/BedrockLauncher/BedrockLauncher/files/10231372/Log_2022-12-14_21-19-09.log)
here is it.

**Comment by SAB236YT** [comment]
and i updated from version (windows) 2004 to 22H2

**Comment by Rayth** [comment]
join https://discord.gg/Ar5SRBZcqn
read this: https://discord.com/channels/841497197594017842/1046507417820725288
