### ISSUE TITLE
The launcher does not open

### ISSUE THREAD

**Issue by Lufims** [BedrockLauncher/BedrockLauncher#328]
I know what's the problem, but I have to confirm if this is it, i'm using windows 7, and the launcher doesn't open, it just crashes, and also, I have dotNet installed correctly, before it was saying an error because I haven't dotNet installed.

**Comment by Rayth** [comment]
Well for a start, Minecraft is for windows 10 or higher so that's an issue right there, and yes this launcher is also made for WIn10 or higher.
