### ISSUE TITLE
Update Button Not Responding

### ISSUE THREAD

**Issue by pororo102** [BedrockLauncher/BedrockLauncher#333]

**Comment by Rayth** [comment]
What update button?

**Comment by pororo102** [comment]
The update button in luancher

**Comment by TheNatBoi** [comment]
Can you send a screenshot?

**Comment by pororo102** [comment]
Its not opening its saying that its removed for a reason

**Comment by TheNatBoi** [comment]
Are you talking about the screenshot to? Try taking a photo with your phone.

**Comment by pororo102** [comment]
It was not working in 2021 version

**Comment by TheNatBoi** [comment]
What was not working?

**Comment by pororo102** [comment]
In last year's version update was not working I even tried spam clicking but doesn't work :(

**Comment by TheNatBoi** [comment]
Have you downloaded [this one?](https://github.com/BedrockLauncher/BedrockLauncher/releases/tag/2022.10.9.152)

**Comment by pororo102** [comment]
Yep

**Comment by TheNatBoi** [comment]
Can you take a photo with a phone? Or press Windows + Shift + S to screenshot.

**Comment by pororo102** [comment]
ok but there is a problem about that when i open it 

![Screenshot_20221229_071630](https://user-images.githubusercontent.com/88652931/209963032-4576e0a7-4df1-440a-852d-7eee1d14ef7b.png)

**Comment by Rayth** [comment]
why is it a shortcut? You shouldn't have a shortcut unless you made it yourself.
Did you extract the zip file after downloading?

**Comment by pororo102** [comment]
yes

**Comment by Rayth** [comment]
Only thing I can think of is your antivirus deleted the exe file after extracting.

**Comment by pororo102** [comment]
yeah

**Comment by TheNatBoi** [comment]
Close issue?

**Comment by pororo102** [comment]
Or The antivirus modifed the code because it has permissions

**Comment by pororo102** [comment]
if someone was using a older version they could not update

**Comment by Rayth** [comment]
the auto updater was removed from the game.
