### ISSUE TITLE
LAUNCHER NOT PASSING LOADING SCREEN

### ISSUE THREAD

**Issue by DragSJ** [BedrockLauncher/BedrockLauncher#336]
I have opened the launcher and the loading screen is all I see. After few minutes The application crashes, Please find me solution.

**Comment by Rayth** [comment]
In the folder where you launched the exe, can you go into the data folder and then logs and send the newest file to here.

**Comment by DragSJ** [comment]
This is it.

**Comment by Rayth** [comment]
there's nothing there

**Comment by ajjxf** [comment]
same question
