### ISSUE TITLE
version dectection problem

### ISSUE THREAD

**Issue by Onyx1589** [BedrockLauncher/BedrockLauncher#337]
when i downloaded the application its running fine but you cant choose what version you can play it only have the version name update but not the specific version you can  play on
![Screenshot 2023-01-01 145749](https://user-images.githubusercontent.com/121744860/210163255-49959646-db71-4064-8158-6a2d2fbabbb1.png)
![Screenshot 2023-01-01 145724](https://user-images.githubusercontent.com/121744860/210163256-eeb9c135-041c-43c4-9e9c-3f0838bd7074.png)

**Comment by Rayth** [comment]
our launcher doesn't provider version names.. that doesn't look like ours. Invalid

**Comment by Onyx1589** [comment]
> our launcher doesn't provider version names.. that doesn't look like ours. 
its does i downloaded it from this site

**Comment by Rayth** [comment]
> > our launcher doesn't provider version names.. that doesn't look like ours.
> > its does i downloaded it from this site

what tab are you on to see the version names? And why would a BEDROCK launcher show java versions?

**Comment by Rayth** [comment]
![image](https://user-images.githubusercontent.com/4260473/210163334-c1c206ae-d3af-470b-984e-2556804bbbc1.png)
![image](https://user-images.githubusercontent.com/4260473/210163361-1f6154f4-8d89-4c44-b070-69f1f9039b5f.png)

**Comment by Onyx1589** [comment]
like i said i only downloaded in this site and i saw this site from ayoutube video becouse i wnated to play bedrock version of minecraft and they said this site

**Comment by Rayth** [comment]
can you upload a log file?

**Comment by Onyx1589** [comment]
let me check

**Comment by Onyx1589** [comment]
it cant

**Comment by Onyx1589** [comment]
https://bedrocklauncher.github.io/ 
this is the where i originaly downloaded it

**Comment by Rayth** [comment]
when you download from here, you get a release.zip file. After extracting and run BedrockLauncher.exe, every time you run it, a log file is created in the data/logs folder which is located in the same location as BedrockLauncher.exe

**Comment by Onyx1589** [comment]
![Screenshot 2023-01-01 150901](https://user-images.githubusercontent.com/121744860/210163434-5c6eea99-505f-4f31-8531-e9cbe9d09714.png)

**Comment by Rayth** [comment]
inside the data folder...

**Comment by Onyx1589** [comment]
![Screenshot 2023-01-01 151511](https://user-images.githubusercontent.com/121744860/210163537-17c92e3b-e19d-42db-a96e-f37057721b76.png)
![Screenshot 2023-01-01 151458](https://user-images.githubusercontent.com/121744860/210163539-e2363711-e73b-42d5-b133-70bae689f8bb.png)
![Screenshot 2023-01-01 151444](https://user-images.githubusercontent.com/121744860/210163540-b721d847-18d4-49e3-815b-6b76dc4f14bc.png)

**Comment by Onyx1589** [comment]
thats the only thing on the data folder

**Comment by Rayth** [comment]
I see no errors, and no one has ever reported this issue. Everyone else's shows the versions properly.

**Comment by Onyx1589** [comment]
idk why either but the only thing is showing is the name version of the update not the specific version

**Comment by Onyx1589** [comment]
im a windows user

**Comment by TheNatBoi** [comment]
> when i downloaded the application its running fine but you cant choose what version you can play it only have the version name update but not the specific version you can  play on
> 
> ![Screenshot 2023-01-01 145749](https://user-images.githubusercontent.com/121744860/210163255-49959646-db71-4064-8158-6a2d2fbabbb1.png)
> 
> ![Screenshot 2023-01-01 145724](https://user-images.githubusercontent.com/121744860/210163256-eeb9c135-041c-43c4-9e9c-3f0838bd7074.png)
> 
> 

The first image is the wallpaper selection... to change version you need to go to the installations tab.

**Comment by TheNatBoi** [comment]
> like i said i only downloaded in this site and i saw this site from ayoutube video becouse i wnated to play bedrock version of minecraft and they said this site 
> 
> 

Also make sure you own the game and have installed and launched it (from Microsoft store) once first
