### ISSUE TITLE
Failed package registration

### ISSUE THREAD

**Issue by NIURAKDIMA** [BedrockLauncher/BedrockLauncher#338]
When registering a package after downloading minecraft, an error pops up. {Google translate}

[Log_2023-01-03_03-51-49.log](https://github.com/BedrockLauncher/BedrockLauncher/files/10333951/Log_2023-01-03_03-51-49.log)
[Error_Message.txt](https://github.com/BedrockLauncher/BedrockLauncher/files/10333952/Error_Message.txt)

**Comment by NIURAKDIMA** [comment]
Downloaded from the official website ( https://bedrocklauncher.github.io/ )

**Comment by Rayth** [comment]
You need to install the .NET Desktop Runtime 6.0. https://dotnet.microsoft.com/en-us/download/dotnet/6.0
MAKE SURE TO GET THE DEKSTOP RUNTIME, NOT THE ASP.NET OR SDK.
