### ISSUE TITLE
All version is trial

### ISSUE THREAD

**Issue by cuti24** [BedrockLauncher/BedrockLauncher#346]
this launcher is error
i enter to game but i cant playgm1 in my world and game tell me buy mc
i hope creator fix this error

**Comment by MetalManiacMc** [comment]
Did you buy the game?

**Comment by cuti24** [comment]
> Did you buy the game?

no

**Comment by TheEpikBoi** [comment]
We must tell you that this launcher does NOT crack the game. Our downloads come from the Microsoft store and you need to OWN the game to play the full version.
