### ISSUE TITLE
i made 1 enchandement that is

### ISSUE THREAD

**Issue by Andrei12333** [BedrockLauncher/BedrockLauncher#35]
Going To http://bedrocklauncher.tk/ will show your website so i think you will like it becuse its a real domain not like a github pages one aslo it will update with the one you normally use

**Comment by CoolAbhi1290** [comment]
Hey there, are you hosting this website? If so, we would like more information as to what service you are using to host this domain and how much you're paying.

**Comment by CoolAbhi1290** [comment]
Hey @Andrei12333, I have investigated this website, and seems like `http://bedrocklauncher.tk/` is not SSL encrypted. We'll be releasing a patch today that will disable cross-origin loading and will render that website useless. If you are the owner of this website, I would strongly recommend you to take it down.
