### ISSUE TITLE
Minecraft 0.13.0.0 doesn't work

### ISSUE THREAD

**Issue by AmnesiaReal** [BedrockLauncher/BedrockLauncher#350]
When i try to download this version it just opens the normal game and in the launcher it gives me a download error.

**Comment by VisionStudiosOF** [comment]
I am having the same problem.

**Comment by Davi72375** [comment]
Same

**Comment by Rayth** [comment]
versions before v1 do not work. neither do betas. We cannot fix as MS removed the downloads from the store
