### ISSUE TITLE
Error while backing up data "-2147018896"

### ISSUE THREAD

**Issue by NINJA101Plays** [BedrockLauncher/BedrockLauncher#351]
I get this error message:
![-2147018896](https://user-images.githubusercontent.com/109701349/211744444-9d205440-12c9-48ca-babb-a020d9c2af18.PNG)

The launcher seems to retry and spits out the same (not too sure about it being the same because I didn't look at it extensively) message multiple times before seeming to end. I don't know whether I should click "Play" or not because I don't want to lose my data.

I didn't copy the message unfortunately so I hope you don't need to copy it or something.

**Comment by Rayth** [comment]
safest thing to do, is goto the default save location for minecraft, manually copy the com.mojang folder thne you can play safely. after pressing play once, you can go back in and put the files back

**Comment by NINJA101Plays** [comment]
I get a "Download failed" error when trying to launch versions I don't have installed. It could be because of the "-2147018896" error but I don't know for sure.

Pastebin: https://pastebin.com/Qda85Z3V

**Comment by Rayth** [comment]
Can you upload a full log file. You can find it inside the `data/logs` folder inside the place you ran the launcher from. Only the latest is required.

**Comment by NINJA101Plays** [comment]
https://pastebin.com/vPWsm5y6

**Comment by Rayth** [comment]
In the data folder, open settings.json with notepad. Change IsFirstLaunch to false, and set CurrentInsiderAccountIndex to 1

Save it then restart launcher and try again.

Also, have you purchased minecraft, or have gamepass ultimate/gamepass for pc?

**Comment by NINJA101Plays** [comment]
Didn't work. Yes, I own the game

**Comment by MFn233** [comment]
man, it happend again to me. i tried your way of solving the problem and it did nothing.
