### ISSUE TITLE
Newer versions won't work

### ISSUE THREAD

**Issue by AstroidexAdam** [BedrockLauncher/BedrockLauncher#352]
When I try to run one of the newer Bedrock Edition versions like 1.18 or 1.19.50 it won't open, but somehow old versions like 0.14 still work properly

**Comment by Rayth** [comment]
have you purchased minecraft?

**Comment by AstroidexAdam** [comment]
> 

I had bought Minecraft Java on my Microsoft account previously

**Comment by Rayth** [comment]
are you logged into that account? if so, try installing via the official launcher first, then run it, uninstall it, and try the launcher here

**Comment by AstroidexAdam** [comment]
yes but I can't download anything from Microsoft store because I get an error

**Comment by Rayth** [comment]
you need to contact MS then it's not a launcher issue. If your store doesn't work, our launcher also doesn't work
