### ISSUE TITLE
Launcher Crash when create profile

### ISSUE THREAD

**Issue by He336** [BedrockLauncher/BedrockLauncher#353]
At First launch it crashed with no reason on step "select a folder"

**Comment by Rayth** [comment]
Open data/settings.json file with notepad, change IsFirstLaunch to false and CurrentInsiderAccountIndex to 1 and save, then try re-run the launcher.

**Comment by besheps** [comment]
ok i have the same problem

**Comment by Rayth** [comment]
> ok i have the same problem

read my reply

**Comment by CantCode023** [comment]
> Open data/settings.json file with notepad, change IsFirstLaunch to false and CurrentInsiderAccountIndex to 1 and save, then try re-run the launcher.

where do I find data/settings.json? I tried opening the file in appdata but I don't find a data folder

**Comment by Rayth** [comment]
it's where you ran bedrock launcher from

**Comment by qwertykid** [comment]
> Open data/settings.json file with notepad, change IsFirstLaunch to false and CurrentInsiderAccountIndex to 1 and save, then try re-run the launcher.

it worked for me hy isnt this closed?

**Comment by Rayth** [comment]
closing due to no response from OP
