### ISSUE TITLE
launcher crashed when the first time running it

### ISSUE THREAD

**Issue by ajjxf** [BedrockLauncher/BedrockLauncher#359]
after installing ,i tried to run it(bedrocklauncher.exe),it opened ,loaded, and crashed
![SharedScreenshot](https://user-images.githubusercontent.com/109795978/218246274-b2eec156-ff3c-4ca7-88d5-3adba26ad10a.jpg)

**Comment by ajjxf** [comment]
(using  win10 and microsoft windows desktop runtime6.0.13)

**Comment by Rayth** [comment]
Please upload a log file. You may find them in the `data/logs` folder in the place where you ran BedrockLauncher.exe from.

**Comment by ajjxf** [comment]
[logs.zip](https://github.com/BedrockLauncher/BedrockLauncher/files/10714980/logs.zip)
this one?(i zipped the folder)

**Comment by Rayth** [comment]
Open `data/settings.json` file with notepad, change IsFirstLaunch to false and CurrentInsiderAccountIndex to 1 and save, then try re-run the launcher.

**Comment by ajjxf** [comment]
> Open `data/settings.json` file with notepad, change IsFirstLaunch to false and CurrentInsiderAccountIndex to 1 and save, then try re-run the launcher.

**Comment by ajjxf** [comment]
still doesnt work  :(

**Comment by TheEpikBoi** [comment]
Try using a VPN 
Just use quick connect or Singapore if you want me.to be specific

**Comment by ajjxf** [comment]
![SharedScreenshot](https://user-images.githubusercontent.com/109795978/219908727-edc65354-71c0-4d01-b994-135fdfeead5f.jpg)
so could you please tell me how to use it?

**Comment by TheEpikBoi** [comment]
You could use Proton VPN, it's easier to use and more user friendly

**Comment by ajjxf** [comment]
now i can open the launcher (the latest version) ,thanks  :)

**Comment by Rayth** [comment]
the latest release was targetted to fix this issue.
