### ISSUE TITLE
I made a logo for bedrock launcher. Sorry if this is useless, idk where else to put it besides issues bc there r enhancements?

### ISSUE THREAD

**Issue by DesertSoldier43** [BedrockLauncher/BedrockLauncher#36]
This is the logo.
![BedrockLauncher](https://user-images.githubusercontent.com/75911941/125153724-96271b80-e10a-11eb-9aa7-79cd41790e48.png)

**Comment by DesertSoldier43** [comment]
And also add a feature to CHANGE the logo of the application

**Comment by CoolAbhi1290** [comment]
Hey @DesertSoldier43, seems like we won't be switching up logos anytime soon, sorry.

**Comment by NT690** [comment]
> And also add a feature to CHANGE the logo of the application

You can change the logo of the app by right-clicking the app in the taskbar, then right-clicking the "Minecraft Bedrock Launcher" option, then click properties, then change icon.
