### ISSUE TITLE
Mouse losing focus constantly since newest update

### ISSUE THREAD

**Issue by omginput** [BedrockLauncher/BedrockLauncher#360]
Since the newest update the mouse loses focus so one can see it and operate in OS but not in game. One has to press ESC 2 times to get the focus back. This happens in an interval of about 1 minute.

**Comment by Rayth** [comment]
when you say newest update are you talking launcher update (there hasn't been one for a couple months) or minecraft update?

**Comment by omginput** [comment]
The flatpak launcher got an update a few days ago

**Comment by Rayth** [comment]
flatpack launcher? our source hasnt been updated since january 1st and that was just the readme file

**Comment by omginput** [comment]
https://flathub.org/apps/details/io.mrarm.mcpelauncher

**Comment by Rayth** [comment]
That's not our launcher. Invalid issue
