### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Enderman8016** [BedrockLauncher/BedrockLauncher#362]
When I downloaded the minecraft version instead of loading the game it gives me this error: Object reference not set to an instance of an object. I've tried changing the config file, re-installing, changing the storage directory, and I get the same error every time. Please help :/

**Comment by Peter20130402** [comment]
is it a popup in windows or is it a popup in the app? I know I'm late but i just wanna know and maybe i can help solve it because i might have the same problem
