### ISSUE TITLE
When will we get the update of 2023? the launcher isnt showing the versions above 1.19.50(neither beta nor preview)

### ISSUE THREAD

**Issue by LeontKing2** [BedrockLauncher/BedrockLauncher#365]

**Comment by Rayth** [comment]
My launcher has all the latest versions. It sounds like yours is failing to update version list. Upload a recent log file from your data/logs folder where you ran bedrocklauncher.exe from

**Comment by Rayth** [comment]
If you're still experiencing this error, we believe we've now fixed it in the latest release from 10 hours ago.
