### ISSUE TITLE
Downloading versions fails

### ISSUE THREAD

**Issue by CoolAbhi1290** [BedrockLauncher/BedrockLauncher#37]
When downloading a new installation or updating one, the launcher fails to fetch download links for them. Visual screenshot:

![](https://i.imgur.com/876cu92.png)
The above image shows me attempting to download the latest beta.

Launcher version: `v0.0.2.1-beta`
OS info irrelevant

Edit: I overrode the launcher with an older version (`v0.0.2.0-beta`) and it seemed to fix the issue, however, the very next day, it stopped working the same way it did with `v0.0.2.1-beta`

**Comment by realmcmonkey** [comment]
same issue here

**Comment by CoolAbhi1290** [comment]
@realmcmonkey I recommend overriding your installation with an [older build](https://github.com/BedrockLauncher/BedrockLauncher-Beta/releases/tag/0.0.2.0)

**Comment by DesertSoldier43** [comment]
I have tried betas from older versions and it doesn't fetch it either.

**Comment by DesertSoldier43** [comment]
some work tho

**Comment by CoolAbhi1290** [comment]
Fixed in `v0.0.2.2-beta`
