### ISSUE TITLE
version problem

### ISSUE THREAD

**Issue by Grewzi** [BedrockLauncher/BedrockLauncher#376]
No matter what version I try to open, it always opens 1.19.70

**Comment by Rayth** [comment]
Please upload a log file from the `data/logs` folder where you run the launcher from

**Comment by Grewzi** [comment]
yeah... i have another problem now i uninstall my .minecraft and my .minecraft_bedrocklauncher and now i cant open minecraft bedrock in both launchers XDDD

**Comment by Rayth** [comment]
well you likely just deleted all your minecraft data because that gets stored in .minecraft_bedrock when you use our launcher. it uses symbolic link to set it to the location that the normal mc uses, so by removing the folder, the symbolic link leads no where.

**Comment by Grewzi** [comment]
i have another problem now
the minecraft opens i see mojang and they insta crash

**Comment by Grewzi** [comment]
[Log_2023-03-16_13-12-58.log](https://github.com/BedrockLauncher/BedrockLauncher/files/10993124/Log_2023-03-16_13-12-58.log)
[Log_2023-03-16_13-14-07.log](https://github.com/BedrockLauncher/BedrockLauncher/files/10993125/Log_2023-03-16_13-14-07.log)
[Log_2023-03-16_13-14-37.log](https://github.com/BedrockLauncher/BedrockLauncher/files/10993126/Log_2023-03-16_13-14-37.log)
[Log_2023-03-16_13-12-14.log](https://github.com/BedrockLauncher/BedrockLauncher/files/10993127/Log_2023-03-16_13-12-14.log)
all the logs i have

**Comment by Grewzi** [comment]
I try with the official launcher and i have the same problem when i open minecraft bedrock

**Comment by Rayth** [comment]
I suspect the issue here, is that you had minecraft installed before using the launcher. try uninstalling minecraft from apps>settings, then run via our launcher on whatever version you want.

be sure to restore that .minecraft_bedrock folder as well if it went to recycle bin or your data will be gone and it will still fail
