### ISSUE TITLE
Step To Fix App registeration failed Windows cannot install package Microsoft.MinecraftUWP_VER_x64__8wekyb3d8bbwe

### ISSUE THREAD

**Issue by BOFOII** [BedrockLauncher/BedrockLauncher#378]
![Screenshot (12)](https://user-images.githubusercontent.com/79498377/229425501-83a362b6-ffb7-4232-b951-137711223a11.png)
![Screenshot (13)](https://user-images.githubusercontent.com/79498377/229425515-ba71cf4d-d4f1-4a43-a81f-b7799becfa2d.png)

1. make sure on Bedrock Launcher you have downloaded the version you want.
2. If you have the original/latest version you downloaded from MS Store, uninstall your Minecraft version (Usually this happens when the user has not downloaded Minecraft from MS Store)
3. redownload Minecraft from your Microsoft Store
4. open your launcher. Reopen your launcher. Just in case, first run your Minecraft and close
5. select the version of Minecraft that was downloaded in step 1. and run. it will automatically unregister the old Minecraft and register the one you selected

Maybe this works for you guys. I spent a day skipping school to find these solutions, from redownloading launchers, re-downloading Minecraft versions, but only this way worked. I hope this also works for you guys

**Comment by Rayth** [comment]
If you'd joined our discord you coulda saved yourself hours and not skipped school.
