### ISSUE TITLE
Official news tab fails to fetch results

### ISSUE THREAD

**Issue by CoolAbhi1290** [BedrockLauncher/BedrockLauncher#38]
The official news tab fails to fetch results and blames it on filters. Visual context:
![](https://i.imgur.com/tekwxTX.png)

Please do note: refreshing does nothing.

Launcher version: `v0.0.2.1-beta`
OS info irrelevant

**Comment by CarJem** [comment]
It's worth noting that what this pulls from:
https://www.minecraft.net/en-us/feeds/community-content/rss
is not responding...

So this could very easily be out of my hands... but still this a bug nonetheless

**Comment by CoolAbhi1290** [comment]
loads for me...

![](https://i.imgur.com/ONOVJ5V.png)

**Comment by CarJem** [comment]
Loading in a physical web browser is different... anyone care to find if the thing actually is reachable from a RSS Reader?

**Comment by CoolAbhi1290** [comment]
@CarJem Feedly, an RSS reader manages to reach it.
![Screenshot_20210803-193953_Feedly](https://user-images.githubusercontent.com/43380238/128103647-7edbf6d3-c720-4b16-875e-4f99080feb06.jpg)

**Comment by CarJem** [comment]
This has been fixed in 0.0.2.5, Closing!
