### ISSUE TITLE
New Installation, Hide Retail, Beta, or Preview!

### ISSUE THREAD

**Issue by AmyGrrl** [BedrockLauncher/BedrockLauncher#380]
When making a new installation. Can you make it so you can choose to hide Retail, Beta, or Preview from the drop down list and remember that setting! It makes the list way to cluttered and long when you only want to install a Retail Build. Thanks!

![Screenshot](https://user-images.githubusercontent.com/31283570/232329940-2d8affee-3da4-47ab-9f8f-71e7ed00359c.jpg)

**Comment by Rayth** [comment]
Instead of using the dropdown, click the 3 dots beside the version box.
![image](https://user-images.githubusercontent.com/4260473/232333777-3320969d-d9c5-4302-bb2b-2d9eea38a61d.png)

**Comment by AmyGrrl** [comment]
I already knew you could click the 3 dots. I will still prefer an option to filter the drop down list. Also thanks for closing this before giving me a chance to respond.
