### ISSUE TITLE
Minecraft Windows 10 Edition Beta 0.13 and older downloads found

### ISSUE THREAD

**Issue by Villager2021** [BedrockLauncher/BedrockLauncher#381]
I found Minecraft Windows 10 Edition Beta 0.13 and older in this website: https://www.mcappx.com/windows/0.12/?h=0.12.0
Use translation software to view full content if you don't speak the language displayed by default
Add those versions to the launcher

**Comment by Rayth** [comment]
These will not be added to the launcher because it is not an official
Microsoft source. All our versions come specifically from the store,
however you can import custom appx files into the launcher.
