### ISSUE TITLE
launcher is not launch

### ISSUE THREAD

**Issue by Radlori** [BedrockLauncher/BedrockLauncher#383]
[Log_2023-04-25_21-55-46.log](https://github.com/BedrockLauncher/BedrockLauncher/files/11323902/Log_2023-04-25_21-55-46.log)

**Comment by Rayth** [comment]
is it just not opening at all but generating the log file?

**Comment by Radlori** [comment]
Yes, im downloaded all needed .NET and VC+, he not works,after a file is created in the "logs"
