### ISSUE TITLE
Stuck on "Registering Package"

### ISSUE THREAD

**Issue by Croqp** [BedrockLauncher/BedrockLauncher#385]
I tried to launch it and it all works but gets stuck on "Registering Package" at 0%. I couldn't find anything else and tried everything. I tried using latest release first maybe it would work but it also got stuck at 0%, and now my actual game wont launch from Microsoft Store. 

![image](https://user-images.githubusercontent.com/132241684/235392287-0787694e-6f6e-4729-8443-da50e74f1e42.png)

**Comment by Rayth** [comment]
The reason its stuck is because you had minecraft installed from the store. Backup your data from the minecraft save location, uninstall minecraft, then try the launcher again.

**Comment by Croqp** [comment]
Is there a good video to do that? I've never done that before lol

**Comment by Rayth** [comment]
Copy the com.mojang folder from `%localappdata%\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games` to somewhere safe. Go to settings > apps and remove minecraft. Then run the game via the launcher, close it. go to the same location and put your files back.
