### ISSUE TITLE
No com.mojang.default folder

### ISSUE THREAD

**Issue by JanGamesHD** [BedrockLauncher/BedrockLauncher#386]
![image](https://user-images.githubusercontent.com/64363088/235451880-18ec7999-746a-46a0-b353-3b279606ba55.png)

I cant find the com.mojang.default folder (Where the old Minecraft files are located.)

**Comment by Rayth** [comment]
When the launcher is open, goto the Installations tab. If you told it to back up data you will have a RecoveryData profile

**Comment by JanGamesHD** [comment]
Oh yes, i found it thanks
