### ISSUE TITLE
[Feature Request] Start Launcher in Fullscreen

### ISSUE THREAD

**Issue by DLazaridisGM** [BedrockLauncher/BedrockLauncher#387]
A Feature Request For A Start In Fullscreen Option In The Launchers Settings Section So The Launcher Starts In Fullscreen.
I Know I Can Just Set Start Maximized In The Shortcut But I Dont Know.

**Comment by Rayth** [comment]
so you want the launcher to start in full screen or minecraft to start in full screen?

**Comment by DLazaridisGM** [comment]
(The Launcher) But Now That You Reminded Me If its Possible to Make The Game Launch In FullScreen After Swithing Profiles That Would Be Great Because That Gets Very Annoying

**Comment by Rayth** [comment]
This would need to go into the bootstrapper, and since the bootstrapper doesn't have "options" to select from I'll need to forget about this request cause it would either be everyone or no one for this.
