### ISSUE TITLE
[Enhancement] Minecraft Launch resolution

### ISSUE THREAD

**Issue by HowardZHY** [BedrockLauncher/BedrockLauncher#390]
like offical java edition launcher's

**Comment by Rayth** [comment]
what do you mean? The size of the minecraft window?

**Comment by HowardZHY** [comment]
> what do you mean? The size of the minecraft window?

yes

**Comment by Rayth** [comment]
because of how the launcher starts the game, this isn't possible to do as far as i can work out.
