### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [BedrockLauncher/BedrockLauncher#392]
Please, re-write this same launcher in the new repository that you can make for android devices so we can get useful working launcher for our devices too to change between versions without removing/installing the game version every time we switch.

**Comment by Rayth** [comment]
No. Our downloads come from the windows store, android devices use the google play store. We don't even know if the play store keeps old versions or not. This is the bedrock launcher for windows. You're welcome to fork it and make your own launcher for android if you can.

**Comment by admin-elvistrujanovic** [comment]
> No. Our downloads come from the windows store, android devices use the google play store. We don't even know if the play store keeps old versions or not. This is the bedrock launcher for windows. You're welcome to fork it and make your own launcher for android if you can.

Well, Minecraft for Android is closed source - even if I can (and I can thanks to the one app that uses Google Play account to download the apk every bedrock version I want in legal way), I'm still unable to get the switchable system on bedrock edition for android.

Well, I've think that you have the working switchable system for that so you just need to modify it and re-write it to Android launcher but as I can see what you wrote there - you also know that it's impossible nor legal to steal closed-source and make it to be open just to be able to make switchable game versions.

**Comment by Rayth** [comment]
To do it on android we have to store the apk files ourselves and at that
point it becomes illegal because anyone can download an apk and install it.
