### ISSUE TITLE
`Microsoft.Services.Store.Engagement` - Missing?

### ISSUE THREAD

**Issue by MineTurtlee** [BedrockLauncher/BedrockLauncher#401]
**Type**
Dependencies
**Description**
see the logs
Edit: **LISTEN**, I DON'T HAVE A D:\a DIRECTORY!
**Screenshots**
not needed
**Logs**
BedrockLauncher.Exceptions.PackageRegistrationFailedException: Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.19.3101.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.Services.Store.Engagement" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 10.0.1610.0, along with this package to install. The frameworks with name "Microsoft.Services.Store.Engagement" currently installed are: {}
 ---> System.Exception: Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.19.3101.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.Services.Store.Engagement" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 10.0.1610.0, along with this package to install. The frameworks with name "Microsoft.Services.Store.Engagement" currently installed are: {}
   at BedrockLauncher.Handlers.PackageHandler.DeploymentProgressWrapper(IAsyncOperationWithProgress2 t) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 511
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 264
   --- End of inner exception stack trace ---
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 275
   at BedrockLauncher.Handlers.PackageHandler.InstallPackage(MCVersion v, String dirPath) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 83

**Comment by PREMIEREHELL** [comment]
you need to install the .NET Desktop Runtime 6.0.6
https://dotnet.microsoft.com/en-us/download/dotnet/6.0

**Comment by MineTurtlee** [comment]
> you need to install the .NET Desktop Runtime 6.0.6 https://dotnet.microsoft.com/en-us/download/dotnet/6.0

Maybe

**Comment by MineTurtlee** [comment]
Meh! It is already installed! 

OS: Windows 11 (Mod Mini beta 8 Tempo as discontinued :<  )

**Comment by Rayth** [comment]
I responded to your ticket on the discord. Please continue resolving this there.

**Comment by MineTurtlee** [comment]
resolved by installing the package in nupkg using device portal.
or Reinstalling Windows.
