### ISSUE TITLE
data disappeared

### ISSUE THREAD

**Issue by Ry2uu** [BedrockLauncher/BedrockLauncher#403]
When I downgraded version, all my minecraft data was lost... this is very painful. I did not expect this!! Does anyone know how to restore the data?
i am crying...................................................................................................................

**Comment by Rayth** [comment]
That depends. Is this first time using the launcher? If so, there should be an installation called Recovery Data which holds all your data prior to using the launcher, assuming you didn't uncheck the backup box or encounter an error during the backup. If you did uncheck the box, or encountered an error, then loaded the game using the launcher on any version, that data is gone.

If you'd been using the launcher for "Latest Release" then it will be in that installation.

Each installation uses different save information. Keep in mind, minecraft worlds are not backwards compatible so if you downgrade version and we didnt store separate data, you couldn't play those worlds anyway.
