### ISSUE TITLE
Program launches newest release instead of the selected one.

### ISSUE THREAD

**Issue by letruxux** [BedrockLauncher/BedrockLauncher#407]
as I said in the title, when I try running an older version of the game, the launcher shoes an error for a split second and launches the updated game 

edit: this happens with some releases, not every release 

![image](https://github.com/BedrockLauncher/BedrockLauncher/assets/102257756/1fee7db8-6f2a-4e18-bc67-2fab2a54c06b)
(i couldn't get logs, sorry for the low res image)

**Comment by Rayth** [comment]
failed to find download links usually happens with old versions or betas which are no longer on the store and can't be accessed.

**Comment by letruxux** [comment]
👍 might aswell delete them from the list then

**Comment by Rayth** [comment]
We plan to in the future, but at the moment the list isn't controlled by us so if we were to remove them now, they'd reappear
