### ISSUE TITLE
i hope to support Chinese

### ISSUE THREAD

**Issue by yanhy2000** [BedrockLauncher/BedrockLauncher#41]
I like this launcher very much, but unfortunately it does not have a Chinese language. I hope that Chinese language can be added, or I want to be able to contribute a language file ，but I don’t know where to modify :(

**Comment by CoolAbhi1290** [comment]
You can translate the launcher to your language throw [crowding bedrock launcher project](https://crowdin.com/project/bedrocklauncher)
