### ISSUE TITLE
Bedrock Launcher is not working.

### ISSUE THREAD

**Issue by DominoKorean** [BedrockLauncher/BedrockLauncher#410]
https://youtu.be/PYZN9Mrt844

**Comment by Rayth** [comment]
It's quite possible the non-english characters in your username/folder names is causing issues. However, if you go into the "app" folder, you should see one called "data" and one inside that called "logs". Upload a log file here.

**Comment by DominoKorean** [comment]
The feature of displaying some default folders, such as "문서" (Documents) and "다운로드" (Downloads), in Korean is a function of Windows. The actual folder names stored is "Downloads," respectively.
Furthermore, within the "app" folder, you will not find any other folders except for the "runtimes" folder.

**Comment by DominoKorean** [comment]
![image](https://github.com/BedrockLauncher/BedrockLauncher/assets/110039366/def97a8b-35ae-42f2-bacf-be8fb9ccd16c)
It works
thank you
