### ISSUE TITLE
It seems like the Crowdin page of Bedrock Launcher is down.

### ISSUE THREAD

**Issue by DominoKorean** [BedrockLauncher/BedrockLauncher#411]
![image](https://github.com/BedrockLauncher/BedrockLauncher/assets/110039366/3a7c9fae-d6be-4f00-ba67-4ffa78537028)

**Comment by Rayth** [comment]
because you have the url wrong: https://crowdin.com/project/bedrocklauncher

**Comment by DominoKorean** [comment]
https://bedrocklauncher.github.io/
In the Bedrock Launcher page, the localization item redirects to that link. It seems like it needs to be modified.
![image](https://github.com/BedrockLauncher/BedrockLauncher/assets/110039366/dbe6b0ee-a1a4-44b5-aada-0e42be43c1d6)

**Comment by Rayth** [comment]
issue has been reported and will be fixed. seems crowdin changed some things
