### ISSUE TITLE
0.13.x versions are listed in versions, but download links for all v0.13.x versions all seem to be broken and therefore inaccessible

### ISSUE THREAD

**Issue by Delvin4519** [BedrockLauncher/BedrockLauncher#413]
Tested 0.13.0, 0.13.1, and 0.13.2 on July 13th, 2023, all download links are broken. Tested v0.13.2 again on July 31st, same thing.

Has anyone had successs accessing v0.13.x versions recently, or are v0.13.x versions not supposed to be on the list and v0.14.x being the oldest accessible playable version?

![image](https://github.com/BedrockLauncher/BedrockLauncher/assets/23464599/69f0bdf4-48fd-4780-963a-11bdc03140aa)

It's kind of a shame that v0.13.x and v0.12.x are missing, lost, or inaccessible versions, meaning that v0.14.x is the oldest playable version and not the initial release of v0.12.1 on Win10. v0.12.x seems to have been lost, missing, or inaccessible.

**Comment by Rayth** [comment]
from the faq on discord:

>>> **Version X doesn't work/Download Failed**
If the version you are trying is an old Beta, they are no longer available and we cannot fix this. If it is a very early 0.x version, they are also not available
The earliest version you can access is 0.14.0.1

**Comment by Rayth** [comment]
The "Failed to find Download Links" error occurs when Microsoft remove that version from the store
