### ISSUE TITLE
Import MCPack files

### ISSUE THREAD

**Issue by CHUCKECHEESETubeYT** [BedrockLauncher/BedrockLauncher#416]
I have a custom Skin Pack file i want to use But it won't Import into the game no matter how many times i try, Can you help me?

**Comment by Rayth** [comment]
If you're using any packs that modify the UI in game, it can break custom skins. also not a launcher issue.

**Comment by CHUCKECHEESETubeYT** [comment]
it's acctualy an issue with the game (i knew i should've been more specific T^T) & no im not using packs that modify the UI, i'm using packs for modifing the minecraft skin
