### ISSUE TITLE
Launcher Crashes after choosing default folder

### ISSUE THREAD

**Issue by TopoPJMask4** [BedrockLauncher/BedrockLauncher#418]
the launcher crashes when click next no other error codes provided

**Comment by Rayth** [comment]
![image](https://github.com/BedrockLauncher/BedrockLauncher/assets/4260473/ca0ea0c9-af60-4fa8-b1b7-c8ab350249db)

**Comment by TopoPJMask4** [comment]
ok, i tried, but when i try to download any version it just crashes, and yes im on administrator account

**Comment by Rayth** [comment]
can you upload the latest log file from the app/data/logs folder starting where you ran StartBedrockLauncher.exe from. It should have details of the crash
