### ISSUE TITLE
lost my worlds after installing it

### ISSUE THREAD

**Issue by Cl3arL5gg** [BedrockLauncher/BedrockLauncher#419]
i thought it'd backup my data but when i checked the localstate folder, everything was wiped

**Comment by Rayth** [comment]
Check if you have an installation in the launcher called "Recovery Data". that's where it's copied to now. If it's not there, then you either unchecked the backup box on first run, or there was an error and you've pressed play since.

**Comment by Cl3arL5gg** [comment]
i already did, i'm not sure what happened but it seems that it wasn't able to copy my minecraft files correctly, i defi shouldn't have had installed the launcher while my game was open ):
good thing i have an older backup of my world so i can just play there, but yeah there's definetely a bug with bedrock launcher installing while original mc is open

**Comment by Rayth** [comment]
> i already did, i'm not sure what happened but it seems that it wasn't able to copy my minecraft files correctly, i defi shouldn't have had installed the launcher while my game was open ): good thing i have an older backup of my world so i can just play there, but yeah there's definetely a bug with bedrock launcher installing while original mc is open

not really a bug.. Files get locked while the game is open so that it can modify them. That issue is on you.
