### ISSUE TITLE
The launcher installs itself in the x86 Program Files directory

### ISSUE THREAD

**Issue by CXCubeHD** [BedrockLauncher/BedrockLauncher#42]
The launcher should install itself in the C:/Program Files/ directory instead of C:/Program Files (x86)/

**Comment by CoolAbhi1290** [comment]
We did faze out x86 recently, so... it's a possibility.

**Comment by CarJem** [comment]
This should have been an issue on the Installer's Repo...
https://github.com/BedrockLauncher/BedrockLauncher.Installer

So I'm closing this.
However, I did just push a commit that fixes this
https://github.com/BedrockLauncher/BedrockLauncher.Installer/commit/e51d9bc301a4b7d714166691f1b4831f93c627ee
