### ISSUE TITLE
[Issue] Launcher Doesn't Delete AppxSignature.p7x File After Importing A Game Version From An Appx File

### ISSUE THREAD

**Issue by DLazaridisGM** [BedrockLauncher/BedrockLauncher#422]
The Launcher Doesn't Delete AppxSignature.p7x File From The Imported Versions Game Files Which If Not Deleted Will Give The Error Below When Attempting To Launch A Profile With The Imported Version.

[Log_2023-11-02_03-21-59.log](https://github.com/BedrockLauncher/BedrockLauncher/files/13233144/Log_2023-11-02_03-21-59.log)

The Error:

BedrockLauncher.Exceptions.PackageRegistrationFailedException: Deployment failed: Package Microsoft.MinecraftUWP_1.2.513.0_x64__8wekyb3d8bbwe with Windows Store origin cannot be sideloaded or installed using developer mode option.
 ---> System.Exception: Deployment failed: Package Microsoft.MinecraftUWP_1.2.513.0_x64__8wekyb3d8bbwe with Windows Store origin cannot be sideloaded or installed using developer mode option.
   at BedrockLauncher.Handlers.PackageHandler.DeploymentProgressWrapper(IAsyncOperationWithProgress`2 t) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 511
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 264
   --- End of inner exception stack trace ---
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 275
   at BedrockLauncher.Handlers.PackageHandler.InstallPackage(MCVersion v, String dirPath) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 83

**Comment by Rayth** [comment]
Do you have developer mode enabled on windows? Settings > system > For Developers

If you do, can you join the discord: https://discord.gg/Ar5SRBZcqn and open a ticket from the support channel, and reference this issue (422) and provide a link to download the appx file you're importing so we can test

**Comment by Sbo-RSA** [comment]
Hey, I've got the same issue. Did you manage to solve it? If so, how?

**Comment by Rayth** [comment]
No it's not fixed at the moment. You need to manually delete the specified
file for the moment

**Comment by Sbo-RSA** [comment]
I've already deleted all the appx files as well as the bedrock.minecraft folder in App Data but when I try to push the play button it gets stuck at "registering package"

**Comment by Rayth** [comment]
you'll need to resetup the launcher if you deleted the .minecraft_bedrock folder. That's where the launcher stores versions etc.

The only file you need to delete is the AppxSignature.p7x file IN THAT EXTRACTED VERSION folder. (.minecraft_bedrock\versions)

If it's stuck at registering package after that, it's a completely different issue and you need to open a separate issue or join discord and use the support ticket system

**Comment by Rayth** [comment]
Attempting to fix this for the next launcher update. Having some small issues

**Comment by Rayth** [comment]
Can confirm this will be fixed in the next launcher update.
