### ISSUE TITLE
[BUG] Wrong Translation

### ISSUE THREAD

**Issue by senina4** [BedrockLauncher/BedrockLauncher#425]
Since I started using **BedrockLauncher**, I've noticed that some translations have **errors**.
# Example
![Example](https://github.com/BedrockLauncher/BedrockLauncher/assets/84493324/fcac9310-ab63-4d5b-aaef-01de0c2cd621)
Hope it can be fixed as soon as possible

**Comment by Rayth** [comment]
Translations are handled on crowdin. Lookup BedrockLauncher project on there and submit your own corrections which will be checked before accepted
