### ISSUE TITLE
Bug: Can't sign-in with the latest version

### ISSUE THREAD

**Issue by Veroniclover** [BedrockLauncher/BedrockLauncher#428]
The first bug appeared here is, the minecraft is stucked at 40%, however i solved it by killing the "Runtime Broker" service... whatever i do, i cant click the sign in button, I have my microsoft/xbox account works fine, I'm using the 1.20.50 btw

And also checked if i'm loggged in bedrocklauncher too
![image](https://github.com/BedrockLauncher/BedrockLauncher/assets/73184907/723979ca-5d06-4290-b016-c902d5911c34)

**Comment by Rayth** [comment]
Not a launcher issue. Probably due to you killing the runtime broker service though as that's required to login.

https://www.youtube.com/watch?v=IzUFfKqBDrs <- this video will fix it permanently.

**Comment by Veroniclover** [comment]
> Not a launcher issue. Probably due to you killing the runtime broker service though as that's required to login.
> 
> https://www.youtube.com/watch?v=IzUFfKqBDrs <- this video will fix it permanently.

i was able to open minecraft using this launcher even if i didnt kill the runtimebroker still not be able to sign in. So this is probably not on runtimebroker.

**Comment by Rayth** [comment]
> > Not a launcher issue. Probably due to you killing the runtime broker service though as that's required to login.
> > https://www.youtube.com/watch?v=IzUFfKqBDrs <- this video will fix it permanently.
> 
> i was able to open minecraft using this launcher even if i didnt kill the runtimebroker still not be able to sign in. So this is probably not on runtimebroker.

the freeze at 40% is the game attempting to login. by you killing the runtime broker it is telling the game to skip that login, and then you can't login. just go through the video i linked and it will stop the 40% freeze

**Comment by Veroniclover** [comment]
> > > Not a launcher issue. Probably due to you killing the runtime broker service though as that's required to login.
> > > https://www.youtube.com/watch?v=IzUFfKqBDrs <- this video will fix it permanently.
> > 
> > 
> > i was able to open minecraft using this launcher even if i didnt kill the runtimebroker still not be able to sign in. So this is probably not on runtimebroker.
> 
> the freeze at 40% is the game attempting to login. by you killing the runtime broker it is telling the game to skip that login, and then you can't login. just go through the video i linked and it will stop the 40% freeze

i already did what's on the video, and now i was able to enter the main menu but the account is not signed in even if it was signed in on the launcher.
![image](https://github.com/BedrockLauncher/BedrockLauncher/assets/73184907/2db59d57-b63d-427c-bfbe-446278033ace)

**Comment by Rayth** [comment]
being signed in onthe launcher is only for downloading the game from the store. you login via the game, or the xbox app on your pc.
