### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by GhostySS4176** [BedrockLauncher/BedrockLauncher#429]
Hi, my problem is that when im trying to install, before puting my profile name and profile directory, the game crashes, what should i do? i downloaded every one and single program that the launcher asked me for, help please

**Comment by Rayth** [comment]
1. Make sure the account you are using is an administrator on the pc, not a normal user who uses an admin login to give permission at the prompt.
2. Make sure you are using a MICROSOFT account on the pc, not a local windows one.
