### ISSUE TITLE
Game Crashes While Launching Old Versions

### ISSUE THREAD

**Issue by topguy222** [BedrockLauncher/BedrockLauncher#433]
game crashingg in mojang screen

**Comment by Rayth** [comment]
Not a launcher issue. Launcher only starts the game. After that it's a game
issue.

**Comment by topguy222** [comment]
> Not a launcher issue. Launcher only starts the game. After that it's a game issue.
> […](#)

but there is nothing in the games files too. (which version should i play i wanna play an old version)

**Comment by Rayth** [comment]
again, if the game launches then crashes its something on your pc crashing it. the mojang screen is usually where the game checks your account to make sure you can actually play the game

**Comment by topguy222** [comment]
> again, if the game launches then crashes its something on your pc crashing it. the mojang screen is usually where the game checks your account to make sure you can actually play the game

ok thanks the newer versions work but ill try to  restart my pc to see if it works or its just a problem with the old versions
