### ISSUE TITLE
how??

### ISSUE THREAD

**Issue by ShopRobloxsieuuytin** [BedrockLauncher/BedrockLauncher#436]
![image](https://github.com/BedrockLauncher/BedrockLauncher/assets/125343920/55b0cadd-4efe-4066-b036-e9cb9b27c2d6)
![image](https://github.com/BedrockLauncher/BedrockLauncher/assets/125343920/58c6ce8f-5b3e-40f7-a724-2743d7984dd6)
how??

**Comment by Rayth** [comment]
You need the x64 version of the .NET Desktop runtime.

**Comment by Rayth** [comment]
https://dotnet.microsoft.com/en-us/download/dotnet/6.0

Make sure to select DESKTOP runtime x64. If you don't have a 64bit PC this
won't work.

**Comment by ShopRobloxsieuuytin** [comment]
> https://dotnet.microsoft.com/en-us/download/dotnet/6.0 Make sure to select DESKTOP runtime x64. If you don't have a 64bit PC this won't work.

Oh ,my PC x86😭😭
