### ISSUE TITLE
Downloaded 7-Zip Installer

### ISSUE THREAD

**Issue by enessmr** [BedrockLauncher/BedrockLauncher#437]
no text here and its an problem

**Comment by Rayth** [comment]
The exe file is a self extracter made with 7zip, not the installer for 7zip.

**Comment by enessmr** [comment]
cuz i dont install it For a LONG WHILE

Ryan Morrison ***@***.***>, 4 Şub 2024 Paz, 05:51 tarihinde
şunu yazdı:

**Comment by enessmr** [comment]
and thank you
