### ISSUE TITLE
Minecraft is only getting trail version

### ISSUE THREAD

**Issue by Amaahn** [BedrockLauncher/BedrockLauncher#439]
Hi... My minecraft launcher is working is smothly and after the version installation the minecraft opened and start the mojang window then it is saying to unlock full version what i can do

**Comment by Rayth** [comment]
do you have legal access to the game, either purchased or game pass?

**Comment by epicmann24** [comment]
where would you get the dll from? also mine has been working till i updated it.

**Comment by epicmann24** [comment]
update i got it working again by removing some of the devices on my microsoft account on the "Microsoft Store device management" page.

**Comment by Rayth** [comment]
> I can confirm, BedrockLauncher launches the game in Trial mode while MS Store launches the game normally. This issue has been prevalent and the only way to fix it afaik is to obtain an illegal copy of `Windows.ApplicationModel.Store.dll` in order to bypass the Trial mode screen.

ifr this happens then when you first ran the launcher you didn't select the correct account. The launcher uses whichever account you select when you first run to download from the store. It doesn't modify anything, literally just downloads.
