### ISSUE TITLE
Error Code -2147018896

### ISSUE THREAD

**Issue by robloxsantino2022** [BedrockLauncher/BedrockLauncher#440]
I just downloaded the launcher but this issue keeps popping up.
![rfdtgdfdfcdsfcscs](https://github.com/BedrockLauncher/BedrockLauncher/assets/149177155/e4ee0c55-0399-460f-934d-42d86b9102dd)

**Comment by Rayth** [comment]
Do a manual backup of your worlds and stuff then uncheck the box for creating a backup when you run the launcher.
