### ISSUE TITLE
launching 1.17 on bedrock launcher launches normal minecraft bedrock 1.20

### ISSUE THREAD

**Issue by HACKERPRO908** [BedrockLauncher/BedrockLauncher#441]
when i lauched a 1.17 bedrock version with my account WHICH HAS A LEGAL MINECRAFT COPY, it launched the normal 1.20 instead of 1.17

**Comment by Rayth** [comment]
> when i lauched a 1.17 bedrock version with my account WHICH HAS A LEGAL MINECRAFT COPY, it launched the normal 1.20 instead of 1.17

You had minecraft installed before using the launcher. Backup your game files, then uninstall it via settings>apps in windows and try the launcher again.
