### ISSUE TITLE
Cannot update the game through Microsoft Store

### ISSUE THREAD

**Issue by FrankXu06** [BedrockLauncher/BedrockLauncher#442]
After running version 1.20.62 of the game through the launcher, update the game to 1.20.71 through Microsoft Store and delete the 1.20.62 installation from the launcher. But the game still launches as version 1.20.62 from the official Minecraft Launcher. This still happens after emptying the 'versions' folder and reinstalling the game from Microsoft Store.

**Comment by Rayth** [comment]
That's because you can't update to 1.20.71 right now. Mojang disabled it 2 days after release

**Comment by FrankXu06** [comment]
> That's because you can't update to 1.20.71 right now. Mojang disabled it 2 days after release

Sorry my fault I didn't notice the announcements from Mojang

**Comment by Rayth** [comment]
It's the same reason we removed the version from the launcher when it stopped working. Once it is re-enabled, that version and any newer versions (like 1.20.72) will be added to the launcher.
