### ISSUE TITLE
Error -2146233088

### ISSUE THREAD

**Issue by Iatethechickenuggets** [BedrockLauncher/BedrockLauncher#443]
Hey, I am a bit irritated about this issue. When I reinstalled it few times more than 10 times, I still got the same problem. I tried with different versions of Minecraft Bedrock and still doesn't work. How do I fix this?
![image_2024-03-24_121205445](https://github.com/BedrockLauncher/BedrockLauncher/assets/164742915/14122beb-2d57-42fd-8226-dfd76203455f)

**Comment by Rayth** [comment]
screenshotting an error doesn't really help say what the error is, but chances are you need to reinstall the .NET Desktop runtime
