### ISSUE TITLE
Launcher Crashing after Setting Up Profile/Folder

### ISSUE THREAD

**Issue by MegaFTW3** [BedrockLauncher/BedrockLauncher#444]
Just crashing nothing popping up

**Comment by Rayth** [comment]
**Launcher Crashes when creating profile, or selecting save location**

MAKE SURE THE ACCOUNT YOU USE THE LAUNCHER ON, IS AN ADMINISTRATOR. YOU CANNOT USE A NORMAL ACCOUNT AND PROVIDE ADMIN INFO WHEN STARTING THIS LAUNCHER.

Second note: You must be using a microsoft account, not a local windows account.

If this occurs when both the above are true, please reinstall the VC++ Runtime: https://aka.ms/vs/17/release/vc_redist.x64.exe

(This issue has popped up repeatedly recently so I'd like to highlight it)
