### ISSUE TITLE
switching versions completely clears out the roamingstate folder

### ISSUE THREAD

**Issue by Furzide** [BedrockLauncher/BedrockLauncher#447]
this is bad for a variety of reasons, one of them being that configs for third party mods/clients are stored in there, resulting in them being deleted.

**Comment by Rayth** [comment]
Not a bug. It's not the launcher that deletes them. When you changed version, the launcher uninstalls ther existing version to install the new version. It's the computer itself deleting that folder. You'll need to back up the RoamingState folder before version switching.

**Comment by Furzide** [comment]
> Not a bug. It's not the launcher that deletes them. When you changed version, the launcher uninstalls ther existing version to install the new version. It's the computer itself deleting that folder. You'll need to back up the RoamingState folder before version switching.

it didn't do that on older versions of bedrocklauncher thats the thing

**Comment by Rayth** [comment]
That part of the launcher didn't get changed when we swapped to lite
version. It must've been something on the way the computer handles
uninstalling and installing minecraft that changed.

You can get around it using 7zip to make a zip folder of what you need
saved and move that zip folder somewhere. Then you'll be able to restore
files
