### ISSUE TITLE
ERROR 

### ISSUE THREAD

**Issue by shayan8888887657yus** [BedrockLauncher/BedrockLauncher#448]
CANT INSTALL SOME VERSIONS ERROR DOWNLOAD FAILED :) _CRASH___

**Comment by Rayth** [comment]
Can you join the discord server and report them in a channel I set up for
this. Link is on the home page.

Note that if the version is a beta version we know those won't load.

The reason for this error is microsoft/mojang removed the non working
versions from the store

**Comment by Rayth** [comment]
https://discord.gg/Ar5SRBZcqn
