### ISSUE TITLE
multi instance on bedrock

### ISSUE THREAD

**Issue by TheeBossKerny** [BedrockLauncher/BedrockLauncher#449]
i have search for hours for multi instance with 2 separate minecraft bedrock and i would like to know if there is any way to do that with this launcher or if you know any other ways.

**Comment by Rayth** [comment]
Do you mean different versions with different saves?

**Comment by TheeBossKerny** [comment]
No i mean to have to of my accounts connected with minecraft open at the same time and same version, so i can for example connect to lifeboat at the same time

**Comment by Rayth** [comment]
that's physically not possible. The game uses the xbox app to login, it's not controlled by the launcher for bedrock.

**Comment by TheeBossKerny** [comment]
There is no over possible ways to achieve that like duplicating the xbox app ?
