### ISSUE TITLE
Launcher closes after pressing "Play"

### ISSUE THREAD

**Issue by FERFAIL-TXZ** [BedrockLauncher/BedrockLauncher#451]
As the title says, every time that I press "Play" the launcher crash. I have the dotnet 6.0 and the latest version too (8.0).

In the installation I selected the fixed one (the recommended one as its says), and Portable Mode is disabled by default.
The storage directory is located at:
_C:\Users\{myusername}\AppData\Roaming\.minecraft_bedrock_

And the log... I don't know where is located at...

**Comment by FERFAIL-TXZ** [comment]
[Log_2024-04-24_14-58-19.log](https://github.com/BedrockLauncher/BedrockLauncher/files/15101188/Log_2024-04-24_14-58-19.log)

**Comment by Rayth** [comment]
Are you using a lite or modified version of windows?

**Comment by FERFAIL-TXZ** [comment]
I'm using a modified version of Windows. AtlasOS 0.3.2

**Comment by Rayth** [comment]
You need a working store on your pc to use this launcher. Lite/modified versions tend not to have the store properly installed so it's missing features it needs.

**Comment by FERFAIL-TXZ** [comment]
Hey, but I can play Minecraft Bedrock from the official launcher downloaded from the MS store...

**Comment by Rayth** [comment]
if you just did that, uninstall Minecraft and try again from out launcher. One of the fixes for that is to install minecraft, run it then uninstall it

**Comment by FERFAIL-TXZ** [comment]
Gonna try. I'll let you know

**Comment by FERFAIL-TXZ** [comment]
**It worked!** So, I just needed to install MC Bedrock from the official launcher, uninstall it and open it again in the Bedrock Launcher. Thanks for the support mate :)

**Comment by Rayth** [comment]
It's because installing minecraft installs the required thing that your pc was missing for our launcher to run the installer.
