### ISSUE TITLE
Insider, not preview!

### ISSUE THREAD

**Issue by DarthArnettJr** [BedrockLauncher/BedrockLauncher#453]
The insider is not offering betas for minecraft anymore. How am I supposed to play betas? The only way to play current betas is via preview!  So now what?

**Comment by Rayth** [comment]
Preview replaced Beta. They made it a separate game due to so many people getting stuck in Beta in the past. I don't understand your issue here, also not a launcher issue. Closing.

**Comment by DarthArnettJr** [comment]
My issue is that I can't access versions below 1.0.0.16.

**Comment by Rayth** [comment]
Anything marked as Beta on the launcher will not work. MS removed those.
The lowest version you can launch is 0.14 (ive tested this myself)
