### ISSUE TITLE
Launcher closes after pressing "Next" on any menu.

### ISSUE THREAD

**Issue by MarkGG8181** [BedrockLauncher/BedrockLauncher#454]
Hi, I have this issue where the launcher just closes when I press "Next" on the profile creation screen.

[Log_2024-05-01_17-26-26.log](https://github.com/BedrockLauncher/BedrockLauncher/files/15178296/Log_2024-05-01_17-26-26.log)

**Comment by Rayth** [comment]
From FAQ on discord:

>>> **Launcher Crashes when creating profile, or selecting save location**

MAKE SURE THE ACCOUNT YOU USE THE LAUNCHER ON, IS AN ADMINISTRATOR. YOU CANNOT USE A NORMAL ACCOUNT AND PROVIDE ADMIN INFO WHEN STARTING THIS LAUNCHER.

Second note: You must be using a microsoft account, not a local windows account.

If this occurs when both the above are true, please reinstall the VC++ Runtime: https://aka.ms/vs/17/release/vc_redist.x64.exe

(This issue has popped up repeatedly recently so I'd like to highlight it)

**Comment by MarkGG8181** [comment]
> From FAQ on discord:
> 
> **Launcher Crashes when creating profile, or selecting save location**
> 
> MAKE SURE THE ACCOUNT YOU USE THE LAUNCHER ON, IS AN ADMINISTRATOR. YOU CANNOT USE A NORMAL ACCOUNT AND PROVIDE ADMIN INFO WHEN STARTING THIS LAUNCHER.
> 
> Second note: You must be using a microsoft account, not a local windows account.
> 
> If this occurs when both the above are true, please reinstall the VC++ Runtime: https://aka.ms/vs/17/release/vc_redist.x64.exe
> 
> (This issue has popped up repeatedly recently so I'd like to highlight it)

Hi, thank you so much. Installing your provided version of VC++ Runtime fixed it. Apparently I had an older version and updating it seemed to fix this issue.
