### ISSUE TITLE
cant get past setup

### ISSUE THREAD

**Issue by SirGamers** [BedrockLauncher/BedrockLauncher#455]
whenever i try to make a profile or select a folder, it crashes

**Comment by Rayth** [comment]
**Launcher Crashes when creating profile, or selecting save location**

MAKE SURE THE ACCOUNT YOU USE THE LAUNCHER ON, IS AN ADMINISTRATOR. YOU
CANNOT USE A NORMAL ACCOUNT AND PROVIDE ADMIN INFO WHEN STARTING THIS
LAUNCHER.

Second note: You must be using a microsoft account, not a local windows
account.

If this occurs when both the above are true, please reinstall the VC++
Runtime: https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by Frisk4973** [comment]
same thing here idk what to do

**Comment by Rayth** [comment]
Try reading my post above
