### ISSUE TITLE
cant start 

### ISSUE THREAD

**Issue by Aisultan14366** [BedrockLauncher/BedrockLauncher#456]
when i try to run it it shows the main and just closes and does nothing

**Comment by Aisultan14366** [comment]
okay

**Comment by Aisultan14366** [comment]
bruh i dont find app\data\logs
gosh dang it

**Comment by Rayth** [comment]
The app folder is where the startbedrocklauncher.exe is. Inside that is a
data folder or should be. If the data folder isn't there do you get any
messages while the start application is loading?

**Comment by Aisultan14366** [comment]
Uploading bandicam 2024-05-16 21-11-29-071.mp4…

**Comment by Rayth** [comment]
what's inside that app folder? can you send a screenshot

**Comment by Aisultan14366** [comment]
![Capture 1](https://github.com/BedrockLauncher/BedrockLauncher/assets/148531623/90809f64-7bb1-44c5-b16a-7abbf80d9ff9)
![Capture](https://github.com/BedrockLauncher/BedrockLauncher/assets/148531623/3f1b7ad8-29f8-49d5-ae97-18fe4a8c3262)

**Comment by Rayth** [comment]
reinstall both of these: 
- https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.30-windows-x64-installer
- https://aka.ms/vs/17/release/vc_redist.x64.exe
then restart your pc and try again

**Comment by Aisultan14366** [comment]
Finally it worked!
