### ISSUE TITLE
Downloading version issues

### ISSUE THREAD

**Issue by IronKelvin** [BedrockLauncher/BedrockLauncher#458]
Whenever I launch a new installation, it always says download failed. I've tried restarting the launcher, but nothing seems to be working.

**Comment by IronKelvin** [comment]
Yeah, I'm stuck on version 1.4.2.0 and whenever I try to download a new installation of any version it is unable to download.

**Comment by Rayth** [comment]
Can you upload a log file (same place as the startbedrocklauncher.exe file, app folder, data folder, log folder)

**Comment by IronKelvin** [comment]
Sure, also it appears that I can only use some versions for some reason. I can't access 1.14 or 1.11 but I can access 1.16.0.2 but not 1.16.0.57. Anyways, here's the crash log: 
[Log_2024-05-17_12-08-59.log](https://github.com/BedrockLauncher/BedrockLauncher/files/15354308/Log_2024-05-17_12-08-59.log) If that doesn't work let me know (I'm new to GitHub).

**Comment by Rayth** [comment]
yeah thats the standard error for microsoft removing versions. Can you list all the versions you tried that failed, and whether they are marked as beta, preview or release

**Comment by IronKelvin** [comment]
1.11.01 (Beta). 1.14.01 (Beta). Yep, I'm pretty sure that was the issue. Thanks for the help!
