### ISSUE TITLE
Error while backing up data "-2147018896"

### ISSUE THREAD

**Issue by MFn233** [BedrockLauncher/BedrockLauncher#459]
![image](https://github.com/BedrockLauncher/BedrockLauncher/assets/103323756/bba90e12-6e33-42ae-abd6-a44548e474fa)

>"Didn't work"

![image](https://github.com/BedrockLauncher/BedrockLauncher/assets/103323756/74c54563-e558-4c44-bc9c-387b1570b65b)

1. I own the game, I bought it in ms store
2. The game is full version, but the game file has been moved to another disk
3. I tried for your method many times but it didn't work

original issue(i am another person): https://github.com/BedrockLauncher/BedrockLauncher/issues/351
@Rayth

**Comment by Rayth** [comment]
backup fails are random and usually due to user permissions. just make a manual backup

**Comment by MFn233** [comment]
Thanks...Now i will try to solve it by myself
thank for your help

**Comment by Rayth** [comment]
All you gotta do is copy the com.mojang folder somewhere. I don't have the
exact location right now
