### ISSUE TITLE
Cannot Open Launcher

### ISSUE THREAD

**Issue by mrdumo** [BedrockLauncher/BedrockLauncher#467]
I downloaded this launcher because I was excited, but when I double click on the executable, nothing happened, now I'm disappointed, what should I do? (HELP NEEDED)

**Comment by Rayth** [comment]
which executable are you double clicking? the one you download is a self-extracter. It creates a folder called BedrockLauncher in the same location or a location you specify

**Comment by Artiugo** [comment]
Estou com o mesmo problema, assim que aperto o botão de download no site, ele cria o executável "BadrockLauncherSetup.exe". E por algum motivo, o executável não é iniciado.
