### ISSUE TITLE
Bedrock not Launching | Error Code: -2146233088

### ISSUE THREAD

**Issue by voidxO7** [BedrockLauncher/BedrockLauncher#470]
![image](https://github.com/BedrockLauncher/BedrockLauncher/assets/140977903/e7495fbd-0da5-44b5-ab9a-cdcb031b7b36)

>2024-06-21 15:24:09.1924|DEBUG||Version: 2024.5.31.2
>2024-06-21 15:24:09.2148|DEBUG||Git Repo: https://github.com/BedrockLauncher/BedrockLauncher
>2024-06-21 15:24:09.2148|DEBUG||Git Branch: lite
>2024-06-21 15:24:09.2148|DEBUG||Git Commit: 660a061
>2024-06-21 15:24:09.2148|DEBUG||Git Sha: 660a0612a88faec1823e719a9ef7d5d02f888e3f
>2024-06-21 15:24:09.2148|DEBUG||Application Starting...

> 2024-06-21 15:24:09.3506|DEBUG||Application Initalization Started!
> 2024-06-21 15:24:09.3506|DEBUG||Application Initalization Finished!
> 2024-06-21 15:24:09.8868|DEBUG||Preparing Application...
> 2024-06-21 15:24:48.9277|DEBUG||Checking for updates
> 2024-06-21 15:24:49.7740|DEBUG||Current tag: 2024.5.31.2
> 2024-06-21 15:24:49.7740|DEBUG||Latest tag: 2024.5.31.2
> 2024-06-21 15:24:49.7740|DEBUG||Preparing Application: DONE
> 2024-06-21 15:25:08.4775|DEBUG||Skipping package removal - same path: Microsoft.MinecraftUWP_1.20.8101.0_x64__8wekyb3d8bbwe C:\Users\*\AppData\Roaming\.minecraft_bedrock\versions\48f0d81e-0cc1-4e97-ab85-c9d3d24e848f
> 2024-06-21 15:25:08.4775|DEBUG||Registering package
> 2024-06-21 15:25:10.1611|DEBUG||Deployment done: Completed
> 2024-06-21 15:25:10.1611|DEBUG||App re-register done!
> 2024-06-21 15:25:13.1257|DEBUG||App launch finished!
> 2024-06-21 15:27:51.6891|DEBUG||Skipping package removal - same path: Microsoft.MinecraftUWP_1.20.8101.0_x64__8wekyb3d8bbwe C:\Users\*\AppData\Roaming\.minecraft_bedrock\versions\48f0d81e-0cc1-4e97-ab85-c9d3d24e848f
> 2024-06-21 15:27:51.6895|DEBUG||Registering package
> 2024-06-21 15:27:53.6086|DEBUG||Deployment done: Completed
> 2024-06-21 15:27:53.6086|DEBUG||App re-register done!
> 2024-06-21 15:27:56.5252|DEBUG||App launch finished!
> 2024-06-21 15:30:36.9638|DEBUG||Skipping package removal - same path: Microsoft.MinecraftUWP_1.20.8101.0_x64__8wekyb3d8bbwe C:\Users\*\AppData\Roaming\.minecraft_bedrock\versions\48f0d81e-0cc1-4e97-ab85-c9d3d24e848f
> 2024-06-21 15:30:36.9638|DEBUG||Registering package
> 2024-06-21 15:30:38.8866|DEBUG||Deployment done: Completed
> 2024-06-21 15:30:38.8866|DEBUG||App re-register done!
> 2024-06-21 15:30:41.7907|DEBUG||App launch finished!
> 2024-06-21 15:31:34.9807|DEBUG||Download start
> 2024-06-21 15:31:34.9807|DEBUG||Download starting
> 2024-06-21 15:31:35.5836|DEBUG||Resolved download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/7e6bbddf-5061-4c0c-acef-9741dc64e1e6?P1=1719019674&P2=404&P3=2&P4=e6eLMXtnEAU0wC%2fS6uMiZvBOO0aWsDH4yOCkFYSNtXHw2Q0x2TDCsbtD8oGHOHmNveANJL5z0pHqG5Y%2b0raBtw%3d%3d

**Comment by Rayth** [comment]
Log file is located in the app/data/logs folder from where you ran
startbedrocklauncher.exe from

**Comment by voidxO7** [comment]
Fixed! I broke the WindowsApps folder messing with the skin packs persona. 

Anyone else who did that. Run: `icacls "C:\Program Files\WindowsApps" /reset /t /c /q` This resets the folder's permissions.
