### ISSUE TITLE
Cannot Update Minecraft After Installing Bedrock Launcher

### ISSUE THREAD

**Issue by maxandroverforever** [BedrockLauncher/BedrockLauncher#474]
Hi,
I recently installed the Bedrock Launcher for nostalgic purposes (I started playing on 1.16 of that edition). After playing that for awhile, I set it back to recovery data to open the latest release (which at the time was 1.20.81). After 1.21 came out, I opened the game again to play on the Hive with a friend who couldn't use Hypixel at the moment, and it didn't update past 1.20.81. How do I fix this? I want the game to update itself (or to just manually update it) and I would prefer not to have to uninstall the game.

**Comment by Rayth** [comment]
Please upload a log file. You may find them in the `app/data/logs` folder in the place where you ran StartBedrockLauncher.exe from.

**Comment by maxandroverforever** [comment]
[Log_2024-05-31_21-59-28.log](https://github.com/user-attachments/files/16018578/Log_2024-05-31_21-59-28.log)
[Log_2024-06-01_08-00-11.log](https://github.com/user-attachments/files/16018579/Log_2024-06-01_08-00-11.log)
[Log_2024-06-01_08-01-17.log](https://github.com/user-attachments/files/16018580/Log_2024-06-01_08-01-17.log)
[Log_2024-06-25_13-46-56.log](https://github.com/user-attachments/files/16018581/Log_2024-06-25_13-46-56.log)
[Log_2024-06-25_13-47-46.log](https://github.com/user-attachments/files/16018582/Log_2024-06-25_13-47-46.log)
[Log_2024-05-31_21-50-03.log](https://github.com/user-attachments/files/16018583/Log_2024-05-31_21-50-03.log)
[Log_2024-05-31_21-58-59.log](https://github.com/user-attachments/files/16018584/Log_2024-05-31_21-58-59.log)
Here's all the logs in the folder.

**Comment by Rayth** [comment]
You need to update your launcher. The version list system was changed and
the old launcher list is no longer updated since 1.20.81

**Comment by maxandroverforever** [comment]
Ok, thank you! Is there any way to 'remove' the launcher (I know it is a portable install) so that Bedrock/Minecraft Launcher can update it again?

**Comment by Rayth** [comment]
Copy the data folder from inside the app folder of your current launcher,
run the extractor on the new one and paste that data folder into the new
app folder. Alternatively, you can allow the self extractor to overwrite
your existing launcher

**Comment by crafty35a** [comment]
> Copy the data folder from inside the app folder of your current launcher, run the extractor on the new one and paste that data folder into the new app folder. Alternatively, you can allow the self extractor to overwrite your existing launcher

I'm running into this same issue, and I don't think I understand this reply. It almost sounds like you are telling him how to update Bedrock Launcher? But the question is how to completely remove Bedrock Launcher so the Windows store/Minecraft Launcher version will be able to update itself properly.

My exact details: I need the current Bedrock Preview version (1.21.20.21). This version does not show as an option in Bedrock Launcher. Now that I have installed Bedrock Launcher, the Minecraft Launcher no longer seems to be able to install/run 1.21.20.21 (it just launches 1.21.10.24 which is what Bedrock Launcher installed as the latest preview). I am guessing this is because of the symbolic link that Bedrock Launcher creates. If so, how do we remove this symbolic link?

**Comment by Rayth** [comment]
The new preview hasn't been added to bedrock launcher yet that's why it
isn't loading it.

If you want the latest preview, uninstall preview from windows
settings>apps then install from official launcher.

**Comment by YaelMagana29** [comment]
I found how to uninstall everything and use Minecraft Launcher, when you open the program for the first time there is a default path (which is not the portable one) we must delete that path, the entire .minecraft_bedrock
C:\Users\(user)\AppData\Roaming\.minecraft_bedrock, in the launcher go to installations and delete both normal and preview and close everything and open the official launcher and install

**Comment by YaelMagana29** [comment]
That's what worked for me, the installation failed but it was a connection problem, and now I'm playing from the official launcher

**Comment by Rayth** [comment]
All you had to do was go to settings>apps in windows and uninstall
minecraft and/or minecraft preview you had installed with the launcher.
Then you could use the official launcher
