### ISSUE TITLE
Don't allow unnamed installations

### ISSUE THREAD

**Issue by Hamsteroonie** [BedrockLauncher/BedrockLauncher#475]
When you create a new unnamed installation, BedrockLauncher puts the packageData folder in your profile floder instead of a folder with the name of an installation, so when you delete that installation it deletes the parent directory, which contains all your save data

**Comment by Rayth** [comment]
That's not really a bug. Why would you create an unnamed installation? When
you press the delete button you tell it to delete that installation folder
so by not giving it a name it deletes the root installation folder.

**Comment by HTV04** [comment]
> That's not really a bug. Why would you create an unnamed installation?

Why does the launcher let you create an unnamed installation at all? Seems like such installations could easily be created by accident. If all installations can be deleted with them, I would definitely consider this a catastrophic bug.

**Comment by jasnn72** [comment]
i just lost so much progress because of this. intentional or not, it's so easy to accidentally delete literally every world and have no way of getting it back

**Comment by Rayth** [comment]
Will be in next launcher release.
