### ISSUE TITLE
how do you download this thing onto windows 

### ISSUE THREAD

**Issue by MaskTwoFaced** [BedrockLauncher/BedrockLauncher#481]
I have watched some videos and stuffs and ive tried to extract the zip file aswell but i cant seem to get the bedrocklauncher.exe to appear onto anything. some help would be nice :)

**Comment by Rayth** [comment]
There is no zip file now. Download the bedrocklaunchersetup.exe and run it.
It will create a folder called BedrockLauncher and then you run
startbedrocklauncher.exe from inside that
