### ISSUE TITLE
This is an open source project

### ISSUE THREAD

**Issue by BinaryHarbinger** [BedrockLauncher/BedrockLauncher#483]
Soo this is an open source project and I think you should port it to Linux. If you port it to linux just think 'bout it there is a Minecraft Bedrock Launcher that really alows you to play Bedrock on Linux. Maybe you guys could port it to mac neither =d

**Comment by Rayth** [comment]
Any linux launchers use the android app. I believe there may be a mac one that also does the same. We use windows and you need a working MS Store to use this launcher.

If you want to port it to linux, go ahead
