### ISSUE TITLE
minecraft does not enter

### ISSUE THREAD

**Issue by Korey666** [BedrockLauncher/BedrockLauncher#488]
hello, my problem is that minecraft does not come in, I go to the menu, click play and nothing happens, I go back, click play, there is also nothing happening, just no action, just does not come in what should I do?

**Comment by Rayth** [comment]
Please upload a log file. You may find them in the app/data/logs folder in the place where you ran StartBedrockLauncher.exe from.

**Comment by Korey666** [comment]
[Log_2024-08-02_22-36-26.log](https://github.com/user-attachments/files/16474656/Log_2024-08-02_22-36-26.log)
вот мой файл журнала

**Comment by Rayth** [comment]
You need this: https://survivingbedrock.com/Microsoft.Services.Store.Engagement_10.0.19011.0_x64__8wekyb3d8bbwe.Appx

If your microsoft store doesn't work, that will need fixed first.

**Comment by Korey666** [comment]
я не особо понял что мне нужно делать с этим файлом что вы скинули я нажимаю это скачиваеться как читание у меня нету Microsoft store можно по подробнее.

**Comment by Rayth** [comment]
If you don't have microsoft store, get it. You need it to use this launcher.
