### ISSUE TITLE
I unistall and install the launcher but i got different error.

### ISSUE THREAD

**Issue by lol216** [BedrockLauncher/BedrockLauncher#49]
Application Starting...
Application Pre-Initalization Finished!
Checking for updates
Current tag: 0.0.2.1
Latest tag: 0.0.2.1
Registering package
Deployment progress: Processing 0%
Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.17.1004.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.Services.Store.Engagement" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 10.0.1610.0, along with this package to install. The frameworks with name "Microsoft.Services.Store.Engagement" currently installed are: {Microsoft.Services.Store.Engagement_10.0.19011.0_x86__8wekyb3d8bbwe Microsoft.Services.Store.Engagement_10.0.19011.0_x64__8wekyb3d8bbwe}
App re-register failed:
System.Exception: Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.17.1004.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.Services.Store.Engagement" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 10.0.1610.0, along with this package to install. The frameworks with name "Microsoft.Services.Store.Engagement" currently installed are: {Microsoft.Services.Store.Engagement_10.0.19011.0_x86__8wekyb3d8bbwe Microsoft.Services.Store.Engagement_10.0.19011.0_x64__8wekyb3d8bbwe}
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<DeploymentProgressWrapper>d__28.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 596
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<ReRegisterPackage>d__27.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 562

**Comment by lol216** [comment]
I am 64bit window 10

**Comment by Rayth** [comment]
> I am 64bit window 10

@lol216 The base error is still the same as #47 that you posted yesterday. Looks like a MS Store error on your PC. Are you running the launcher in admin mode?

**Comment by lol216** [comment]
Yes

**Comment by CoolAbhi1290** [comment]
@lol216 Please stop creating new issues and continue to expand upon the old ones if they're related.
