### ISSUE TITLE
Launcher Crashes During Setup

### ISSUE THREAD

**Issue by Kaleb99jOfficial** [BedrockLauncher/BedrockLauncher#491]
The launcher crashed during setup on the folder selection. I have a video of it here [https://www.youtube.com/watch?v=J3t546K9UeU](https://www.youtube.com/watch?v=J3t546K9UeU) (black screen in video is UAC prompt)

Also attached are the log files for both attempts seen in the video.

[Log_2024-08-05_15-14-34 first launch.log](https://github.com/user-attachments/files/16501922/Log_2024-08-05_15-14-34.first.launch.log)
[Log_2024-08-05_15-15-05 second launch.log](https://github.com/user-attachments/files/16501923/Log_2024-08-05_15-15-05.second.launch.log)

If it helps, my main Windows account is connected to a Microsoft account where I own Bedrock. My security settings are set up through a fully local Windows admin account, so I have to enter the password to get through UAC prompts. This is probably relevant because the launcher throws an authentication exception in the log.

**Comment by Rayth** [comment]
That is why. The account running the launcher needs to be admin not just
approved by admin

**Comment by Kaleb99jOfficial** [comment]
> That is why. The account running the launcher needs to be admin not just approved by admin

Running the launcher fully under the admin account worked, thanks for the quick response.
