### ISSUE TITLE
for all OS! pls

### ISSUE THREAD

**Issue by Ethan9112** [BedrockLauncher/BedrockLauncher#492]
make one for linux like the bedrock launcher from flathub but instead microsoft account.
if your are not familiar with linux this are the distros ubuntu any version, mint any version, maybe Arch Linux any version.

**Comment by Rayth** [comment]
Linux does not have a native version of bedrock. If you want to play bedrock on linux, use a different launcher.

**Comment by tulpenkiste** [comment]
> Linux does not have a native version of bedrock. If you want to play bedrock on linux, use a different launcher.

Couldn't it theoretically run bedrock via wine?
