### ISSUE TITLE
[Issue] Extraction Error for 1.21.21

### ISSUE THREAD

**Issue by AvgZing** [BedrockLauncher/BedrockLauncher#500]
Seemingly a disconnect between the recognized Installed Versions and the versions set in Installations. Installations thinks that 1.21.21 is installed, while the Versions tab does not show it as installed. So it's trying to extract a package that was never installed. Since it doesn't show up in the Settings-> Versions tab, it cannot be repaired.

**Comment by Rayth** [comment]
I need exact steps to reproduce this error

**Comment by Rayth** [comment]
can you get the latest update I did today and try install again.

**Comment by AvgZing** [comment]
Fixed it. Had an error initially but the missing 1.21.21 appx appeared in the directory. So I closed and reopened the launcher and it installed itself properly and all is working. Thanks.

**Comment by NSPC911** [comment]
Bump, 1.21+ doesnt show in the current versions in Bedrock Launcher and Latest Stable leads to it downloading 1.20.81

**Comment by Rayth** [comment]
> Bump, 1.21+ doesnt show in the current versions in Bedrock Launcher and Latest Stable leads to it downloading 1.20.81

that's cause you're on an old launcher version.
