### ISSUE TITLE
[BUG] Recovery Data installations uses wrong directory

### ISSUE THREAD

**Issue by RuiNtD** [BedrockLauncher/BedrockLauncher#502]
**Describe the bug**
The Recovery Data installations use the wrong directory names.

**To Reproduce**
1. Have existing Minecraft Bedrock installation and data
2. Setup Bedrock Launcher for the first time
3. When prompted, choose to backup your existing data.
4. Go to Installations and click Open Folder on Recovery Data.
5. Notice the folder being empty.

**Expected behavior**
The Recovery Data installation should use the RecoveryData directory (with no space) and the Recovery Data (Preview) installation should use the RecoveryDataPreview directory.

**Screenshots**
![image](https://github.com/user-attachments/assets/088b8e67-3b45-4a79-b93b-9a71e19ca90d)

**Additional context**

**Comment by Rayth** [comment]
Is it saving in the profiles folder rather than making a folder in the named profile folder? This has been mentioned before and so far i've been unable to reproduce it
