### ISSUE TITLE
[BUG] Launcher fails to copy game files from an imported game version, from temp folder to pre existing folder.

### ISSUE THREAD

**Issue by DLazaridisGM** [BedrockLauncher/BedrockLauncher#503]
**Describe the bug**
after importing removing and importing an appx file a second time with a name that begins with [ Minecraft- ] the launcher will fail to copy the extracted files from the created temp folder to a pre existing folder where the files would be stored.

**To Reproduce**
1. Go to 'Settings/Versions'
2. Click on 'Install From Local file'
3. Select and install any version [In my case i used a 0.12.0.1 version]
4. Click on 'Refresh'
5. The imported version will be available
6. On the imported version click on the 3 dots '...'
7. remove
8. Yes
9. Click on 'Refresh'
10. Repeat Step 2/3 (Use the same version)/4
11. The imported version doesn't show up again
12. Go to .minecraft_bedrock\versions
13. In the versions folder delete folder named [ name of the imported appx ]
14. Go back to the launcher 
15. Click on 'Refresh' 2 times
16. Imported version will be available again.

**Expected behavior**
the launcher should not fail to copy the game files from the temp folder to a final pre existing folder

**Screenshots**

https://github.com/user-attachments/assets/26737afb-8d69-40df-9101-171f5d74563d

https://github.com/user-attachments/assets/1d6971d4-0b0d-4779-a1e7-ee88000eb2c8

**Additional context**
1) This behavior happens when the appxs name starts with [ Minecraft- ]
2) Importing an Appx Files without [ Minecraft- ] in their name doesn't require the user to click refresh
3) Affects Launcher Versions 2024.8.18.21 and older

**Comment by Rayth** [comment]
So just to clarify,
if the Appx file starts with Minecraft- it doesn't load it into the verison list after hitting refresh? And if Minecraft- isn't in the Appx file name, it doesn't need to be refreshed at all?

**Comment by Rayth** [comment]
Also as another note, I'm not going to look into this until the next release is out as I made some changes to importing to fix the other bug you reported. If it still happens on that version i'll look into it further.

**Comment by DLazaridisGM** [comment]
> So just to clarify, if the Appx file starts with Minecraft- it doesn't load it into the verison list after hitting refresh? And if Minecraft- isn't in the Appx file name, it doesn't need to be refreshed at all?

1)when an appx with Minecraft- is imported it load fine but when remove and imported again it doesnt

2)if the appx file name doesnt start with Minecraft- it load but doesnt need a refresh
