### ISSUE TITLE
[BUG] Launcher Crashes after clicking Kill/Kill Game

### ISSUE THREAD

**Issue by DLazaridisGM** [BedrockLauncher/BedrockLauncher#509]
**Describe the bug**
Launcher crashes after clicking Kill/Kill Game in the Play section.

**To Reproduce**
1. Go to 'Setting/General'
2. Enable 'Keep the Launcher open while games are running'
3. Click on 'Minecraft: Bedrock Edition' (Top Left)
4. Click on 'Play' (With Any Profile Selected)
5. Wait for the game to start and the Kill button to show up
6. Click on 'Kill'

**Expected behavior**
Launcher shouldn't crash when clicking on Kill/Kill Game and it should terminate the running instance of the game.

**Screenshots**

https://github.com/user-attachments/assets/292624f2-356b-4f1b-afa1-3ba48358d6d9

**Additional context**

**Comment by Rayth** [comment]
I get the following pop up when I try
![image](https://github.com/user-attachments/assets/4f36d784-c5e0-4f51-b037-4b50c7e6aea4)

**Comment by Rayth** [comment]
legitimately have no idea about this one tbh

**Comment by DLazaridisGM** [comment]
some info if that might help i changed some code from an older build and the kill button work now heres an image
![Screenshot (492)](https://github.com/user-attachments/assets/d7e8f71a-2872-49db-ad2a-88fc00ba8f8c)
