### ISSUE TITLE
[BUG] Github Button in the about tab under carjems info Doen't do anything.

### ISSUE THREAD

**Issue by DLazaridisGM** [BedrockLauncher/BedrockLauncher#511]
**Describe the bug**
In the About tab clicking on the Github Button Under Jarjems info does nothing.

**To Reproduce**
1. Go to 'Settings/About'
3. Click on 'Github' Under Carjems info

**Expected behavior**
Clicking on the Github button should redirect to carjems main github page

**Screenshots**

https://github.com/user-attachments/assets/aaf85305-4585-4712-b847-854bfaf867ba

**Additional context**
in AboutPage.xaml
Line58 is   Tag="{StaticResource GeneralText_GitHub}"
instead of Tag="{StaticResource CJ_GithubURL}"

Path for the file is in BedrockLauncher/Pages/Settings/AboutPage.xaml
Affects: 2024.8.26.28

**Comment by TTF-fog** [comment]
![image](https://github.com/user-attachments/assets/85046989-4b10-4b4c-98b3-5f4ff8eadae5)
seems like the tag should be CJ_GithubURL instead
