### ISSUE TITLE
[BUG] Big green button and installation selector don't automatically update on language change.

### ISSUE THREAD

**Issue by DLazaridisGM** [BedrockLauncher/BedrockLauncher#513]
**Describe the bug**
when the launchers language is changed the Main Play Button doesn't update the Play text string to the selected languages text string without launching and closing the game

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Keep launcher open while games are running'
3. Click on 'Choose any language' other than english
4. Click on 'Play tab' (Top Left)
5. Click on 'Play'
6. wait for the game to start
7. close the game

**Expected behavior**
when the launchers language is changed the Play text should change without having to launch and close the game

**Screenshots**

https://github.com/user-attachments/assets/b14951a9-a6d9-49bf-8fbb-92fd7ae45296

**Additional context**
There is one more issue related to this
affects: 2024.8.26.28

**Comment by Rayth** [comment]
I assume everything else updates automatically?

**Comment by DLazaridisGM** [comment]
> I assume everything else updates automatically?

In the play screen yes, there is one issue in the WelcomePage2 (The Screen with the "Fixed Folder" - "Portable/RootFolder" Options)  where the language changes in the on the Browse/Release buttons even tho it shouldn't because the buttons are set to StaticResource

**Comment by DLazaridisGM** [comment]
got another issue

**Comment by Rayth** [comment]
Re-opened as big green button still isn't updating.
