### ISSUE TITLE
[Feature Request] Play Button in the Play Screen should have its own text string key for translation purposes

### ISSUE THREAD

**Issue by DLazaridisGM** [BedrockLauncher/BedrockLauncher#514]
**Is your feature request related to a problem? Please describe.**
i was translating the launcher and i noticed that the Play Button in the Play Screen and the Play Tab use the same string soo it makes the translation for some languages harder to make more sense and look more neat.

**Describe the solution you'd like**
id like for the 'Play Button' in the 'Play Screen' to have its own string key, i think this would fit well 'GameTab_PlayButton_Play_Text'
with the existing 'GameTab_PlayButton_Kill_Text' string key

**Describe alternatives you've considered**
an alternative would be to use the existing 'InstallationsPage_PlayButton' string key which is used for the 'Play Button' in the 'Installations Screen', because the text should be the same on both buttons anyway

**Additional context**
this issue is related to #513 code wise

**Comment by Rayth** [comment]
Did you check the crowdin for this or did you pull it from the launcher code?

**Comment by DLazaridisGM** [comment]
tested in code

**Comment by Rayth** [comment]
According to the code, this button has it's own string key:
`GameTab_PlayButton_Text`

**Comment by Rayth** [comment]
and confirmed its in the translations.

**Comment by DLazaridisGM** [comment]
but that string key is shared with the Play Button that it next to the Installation Button

**Comment by Rayth** [comment]
ok changing it to the InstallationsPage_PlayButton
still cant work out why language wont change

**Comment by DLazaridisGM** [comment]
ok yeah thats works, perfect.
