### ISSUE TITLE
[BUG] Keeps downloading the wrong minecraft

### ISSUE THREAD

**Issue by sugarylettuce49** [BedrockLauncher/BedrockLauncher#515]
**Describe the bug**
I press play on latest release and it keeps downloading the preview version and doesn't even launch it after. It does install however.

**To Reproduce**
Launch app, press play, boom.

**Expected behavior**
Pressing play for latest release launches the latest normal minecraft.

**Screenshots**

**Additional context**

**Comment by Rayth** [comment]
This has been resolved. Was a minor database error. You may need to go to `%appdata%\.minecraft_bedrock` and delete the community_versions and community_technical_versions files

**Comment by sugarylettuce49** [comment]
oh ok thank you 👍
