### ISSUE TITLE
[BUG] When Latest Release/Preview/Beta is selected in the profile selection menu and the language is changed the text of these profiles doesnt update to the selected languages text.

### ISSUE THREAD

**Issue by DLazaridisGM** [BedrockLauncher/BedrockLauncher#519]
**Describe the bug**
When Latest Release/Preview/Beta is selected in the profile selection menu in the Play Screen and the language is changed the text of these profiles doesnt get updated to the selected languages text.
**To Reproduce**
1. Click on 'The Profile Selection Menu'
2. Choose 'Latest Release/Preview or Beta'
3. Go to 'Setting/General'
4. Click on 'Language'
5. Select some language
6. Click on 'Minecraft: bedrock Edition' (Top Left)
7. In the Profile Selection Menu select 

**Expected behavior**
When Any of these Profiles Latest Release/Preview/Beta is selected in the profiles are selected and the language is changed the text should change automatically.

**Screenshots**

https://github.com/user-attachments/assets/b123f250-4de3-445c-860a-364bf4f66ed2

**Additional context**

**Comment by Rayth** [comment]
The installation names are hard coded and language independant. For these ones in particular they also refer to the directory for storing the save data.

**Comment by Rayth** [comment]
so upon looking at this, it seems they do change. It's the main part of the selector that doesnt change automatically.

**Comment by Rayth** [comment]
Going to close this and link to #513 as both are affected
