### ISSUE TITLE
Error "object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by PavelDobCZ23** [BedrockLauncher/BedrockLauncher#53]
What happens is, that I hit "PLAY", it tries to lunch Minecraft and then Minecraft window crashes and error like this pops up: 
![image](https://user-images.githubusercontent.com/62188082/130976194-38f4a561-c976-49cc-9218-9d6d609acaa2.png)
After that, Bedrock Launcher crashes as well.
Translated it means - "object reference not set to an instance of an object" which probably happens because Minecraft crashes and so object can't be found, but is there any way I can avoid this issue or is it bug you need to fix in the code? I'd really like to use Bedrock Launcher but this makes it impossible :/

**EDIT:**
This crash can be fixed by changing the directory of Minecraft installations. Characters `á` and `š` in the directory path caused the issue.

**Comment by CarJem** [comment]
Needs a bit more information as this is kind of pointless... a log file might help

**Comment by CoolAbhi1290** [comment]
Marking as invalid until a log file is provided

**Comment by PavelDobCZ23** [comment]
Ok so I have to create another backup of MC data and download it again cause of error log file.... 😑
Ok ig, but make sure to fix it if I'll do so then please very much. 🙏

**Comment by CoolAbhi1290** [comment]
@PavelDobCZ23 Please provide a  log. We know this is a valid issue, but we cannot do much about it without the log.

**Comment by PavelDobCZ23** [comment]
> @PavelDobCZ23 Please provide a  log. We know this is a valid issue, but we cannot do much about it without the log.

Well the issue didn't happen after I reinstalled as I've changed the directory to one without `á` and `š`, the conditions hint that character encoding might be an issue. I can try using portable version of the program and try to reproduce it there.

**Comment by CoolAbhi1290** [comment]
I'm closing this then
