### ISSUE TITLE
Can't play the game

### ISSUE THREAD

**Issue by ItzzNobody** [BedrockLauncher/BedrockLauncher#535]
![image](https://github.com/user-attachments/assets/b46e1368-6048-4ff3-a848-74d90fbd8694)

I installed the game but whenever I try to run the game this pops up.

**Comment by Rayth** [comment]
Support is no longer provided on Github. However, as I stated on the discord before you left, this launcher will not crack the game for you since you stated you haven't purchased it or have a gamepass subscription.
