### ISSUE TITLE
Minecraft Dungeons launchable offline

### ISSUE THREAD

**Issue by TheDoctor200** [BedrockLauncher/BedrockLauncher#538]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**
It can’t be launched offline, both the launcher / Xbox / Ms Store Version have that problem. Would be nice to have it in the Bedrock Launcher. Dungeons needs an active internet connection to launch. 

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by Rayth** [comment]
We have no plans to include dungeons into the launcher. If we did, we also can't bypass the online requirement. Keep in mind our launcher also requires an internet connection for updating the versions list.
