### ISSUE TITLE
Trial?

### ISSUE THREAD

**Issue by joshuadjteam** [BedrockLauncher/BedrockLauncher#539]
Im trying to install MC Bedrock on my PC and its a free trial! in MinecraftUWP 1.21.3003. This is weird since it works on my PC. Same insider account and i purchased Minecraft Bedrock. If anyone cane help me that'd be great!

**Comment by Rayth** [comment]
Make sure your store is logged into the account that owns minecrat. This is not a launcher issue though and we no longer offer support on github. If you need further support for this, I suggest contacting microsoft. If you need launcher support, join our discord.

**Comment by joshuadjteam** [comment]
ok
