### ISSUE TITLE
Will this delete my worlds and data? 

### ISSUE THREAD

**Issue by minecraft12343** [BedrockLauncher/BedrockLauncher#551]
I'm worried that this would delete my worlds/data. I'm on 1.21.44 and all I want to do is downgrade to 1.21.31 so I can use horion. Can I please have clarification?

**Comment by Rayth** [comment]
Anything that has been opened in 1.21.44 wont be able to be opened by 1.21.31. If you haven't opened the worlds, then you create an installation with the version you want and you'll need to copy the world files over as the launcher would save them under the latest release installation. If you aren't already using the launcher, make sure you make a backup of your worlds first. For any further support, please join our discord.
