### ISSUE TITLE
App registration error

### ISSUE THREAD

**Issue by DyeTk7137** [BedrockLauncher/BedrockLauncher#552]
**Describe the bug**
Before the launcher install minecraft Bedrock 1.21.44, the launcher always crash or error and I can't install minecraft bedrock but if download a older version (example: 0.14.0.1), Bedrock launcher can install but if install a version higher, It will crash.

**Expected behavior**
I expect Bedrock launcher can fix this error

**Comment by Rayth** [comment]
Please join our discord for support. Link is on the home page of the website
