### ISSUE TITLE
Adding version 0.14.3?

### ISSUE THREAD

**Issue by redpixel2** [BedrockLauncher/BedrockLauncher#556]
I found the actual file itself floating around in some russian site, and i have confirmed the md5 hash to be the same as the one recorded in another archive.

I have no clue whether or not the update id is crucial but I think it is still possible to add the version.

Microsoft.MinecraftUWP_0.143.0.0_x64__8wekyb3d8bbwe.Appx
c74fd23c25c236d35a98cd132f9854aa

![462581647_2937306569753103_3623473957074810359_n](https://github.com/user-attachments/assets/5280e78b-bd75-43e4-9284-af93fd6f5403)
![image](https://github.com/user-attachments/assets/aca3f2bb-e405-4749-a41e-d86e5e0858fb)

**Comment by Rayth** [comment]
Thanks but the file isn't available from the MS Store anymore so we can't add it.
