### ISSUE TITLE
[BUG] App registration failed. How fix?

### ISSUE THREAD

**Issue by NinpaRad** [BedrockLauncher/BedrockLauncher#558]
The launcher cannot launch the latest version of minecraft due to a registration problem. How fix this?

I only saw a post on the topic of the 2021 version.
**Crash report:**
BedrockLauncher.Exceptions.PackageRegistrationFailedException: Deployment failed: Windows не удается установить пакет Microsoft.MinecraftUWP_1.21.5007.0_x64__8wekyb3d8bbwe, поскольку он зависит от платформы, которую не удается найти. Предоставьте платформу "Microsoft.VCLibs.140.00", опубликованную "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", с нейтральной архитектурой или архитектурой процессора x64 и минимальной версией 14.0.33519.0 вместе с этим пакетом для установки. Платформы с именем "Microsoft.VCLibs.140.00", установленные в настоящий момент: {Microsoft.VCLibs.140.00_14.0.32530.0_x86__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.32530.0_x64__8wekyb3d8bbwe}
 ---> System.Exception: Deployment failed: Windows не удается установить пакет Microsoft.MinecraftUWP_1.21.5007.0_x64__8wekyb3d8bbwe, поскольку он зависит от платформы, которую не удается найти. Предоставьте платформу "Microsoft.VCLibs.140.00", опубликованную "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", с нейтральной архитектурой или архитектурой процессора x64 и минимальной версией 14.0.33519.0 вместе с этим пакетом для установки. Платформы с именем "Microsoft.VCLibs.140.00", установленные в настоящий момент: {Microsoft.VCLibs.140.00_14.0.32530.0_x86__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.32530.0_x64__8wekyb3d8bbwe}
   at BedrockLauncher.Handlers.PackageHandler.DeploymentProgressWrapper(IAsyncOperationWithProgress`2 t) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 535
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 280
   --- End of inner exception stack trace ---
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 291
   at BedrockLauncher.Handlers.PackageHandler.InstallPackage(MCVersion v, String dirPath) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 84
   Sorry for my bad english

**Comment by Rayth** [comment]
Fix your Microsoft store.

**Comment by NinpaRad** [comment]
How? D=
![image translated](https://github.com/user-attachments/assets/8fcdc220-5d1a-49c4-b82a-434fbdf59527)

**Comment by Rayth** [comment]
Someone else apparently used adguard to install the Microsoft.VCLibs.140.00 package and got it working. Other than that, there's nothing we can do.
