### ISSUE TITLE
[BUG] Bedrock launcher does not launch Minecraft sometimes

### ISSUE THREAD

**Issue by Peter20130402** [BedrockLauncher/BedrockLauncher#559]
**Describe the bug**
When launching Minecraft (In some cases) There is an error stating :
```
BedrockLauncher.Exceptions.AppLaunchFailedException: Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at BedrockLauncher.Handlers.PackageHandler.LaunchPackage(MCVersion v, String dirPath, Boolean KeepLauncherOpen) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 56
   --- End of inner exception stack trace ---
```

**To Reproduce**
Steps to reproduce the behavior: (2 Variants)
Variant 1(No portable mode):
> 1. Go to 'Play'
> 2. Click on 'Play'
> 3. See error

Variant 2(In portable mode):
> 1. Install Minecraft bedrock with portable mode
> 2. Delete game files and expect Bedrock launcher to install again
> 3. See error

>Both variantshave the same error and are just different ways to reproduce the error.

**Expected behavior**
Variant 1: Expect Bedrock launcher to install Minecraft Bedrock in the provided storage directory
Variant 2: Expect Bedrock launcher to reinstall Minecraft bedrock in the portable storage directory

**Screenshots**
![image](https://github.com/user-attachments/assets/213a89fb-7ccb-40df-b52f-6cd13a10eb6e)

**Additional context**
Log file: 
[Log_2024-12-17_13-54-12.log](https://github.com/user-attachments/files/18160824/Log_2024-12-17_13-54-12.log)

Another bug I am experiencing that might be related to or might be caused by this:
Bedrock launcher keeps loading until I change the language. Unfortunately, nothing in the logs say anything about this.

**Comment by Rayth** [comment]
2 different errors, even if the message is the same. The first happens when the game crashes before the launcher can detect that it has actually launched. this isn't a launcher bug. The second one is because you're deleting files. Also not a bug. If you want to delete a version you need to delete it either while launcher is closed, or from the settings>versions menu.
