### ISSUE TITLE
Cannot delete a skin pack from UI

### ISSUE THREAD

**Issue by NT690** [BedrockLauncher/BedrockLauncher#56]
Trying to delete a skin pack made in the launcher grants you with a frozen screen where you can do nothing but move the character around, and the only way to un-freeze it is to close the app
https://user-images.githubusercontent.com/70166536/131237938-788a7899-2840-4051-9aba-74dbb48c24b5.mp4

**Comment by CoolAbhi1290** [comment]
A hilarious layering issue

**Comment by NT690** [comment]
[Clarification] You can delete it manually from file explorer by opening the folder and deleting it, just not in the app.

**Comment by CarJem** [comment]
I've made a fix that should appear in Beta 0.0.2.7

**Comment by CoolAbhi1290** [comment]
Seems like it works now, gonna close this

**Comment by NT690** [comment]
Sounds good.
