### ISSUE TITLE
"Unhandeled exception occurred" (HRESULT:0x8007045A)

### ISSUE THREAD

**Issue by Emeraled345** [BedrockLauncher/BedrockLauncher#58]
![image](https://user-images.githubusercontent.com/87779947/131377239-aaa4b46e-b24a-4714-893a-8b499e10874c.png)

After the installation process, the launcher fails to load/assembly the following DLL routine:
'CefSharp.Core.Runtime.dll'

Notes:

- This happened both times when installing into a Portable Drive and Internal Drive
- Changing between stable and beta builds did not fix it
- You cannot uninstall the application using its built-in Uninstaller.exe (Must do it manually)

**Comment by CarJem** [comment]
Since we no longer have any references to CefSharp... this issue has been presumably fixed in the betas... and unless you can provide a screenshot of the issue on the beta... I can address this...
