### ISSUE TITLE
App re-register failed

### ISSUE THREAD

**Issue by Makeshift-Moose** [BedrockLauncher/BedrockLauncher#6]
Hi I am getting this error when I try to launch a version of bedrock through the launcher. In the attached crash report it says it is already installed. I can't find it in the add or remove program list.
[Crash-Log.txt](https://github.com/BedrockLauncher/BedrockLauncher/files/6627427/Crash-Log.txt)

**Comment by Makeshift-Moose** [comment]
I tried to uninstall Bedrock launcher and install Minecraft from the Microsoft Store. The store ends in error Code: 0x80070003

**Comment by realmcmonkey** [comment]
Minecraft is still on your computer somewhere

**Comment by Makeshift-Moose** [comment]
I logged into my laptop with the other user account and uninstalled Minecraft there and it started working. It looks and works great thanks for making this.
