### ISSUE TITLE
In-App News Viewer?

### ISSUE THREAD

**Issue by NT690** [BedrockLauncher/BedrockLauncher#60]
Instead of redirecting the user to the browser, news articles should be parsed in the launcher and displayed.

**Comment by CoolAbhi1290** [comment]
What do you mean? Don't we already have a news viewer? Please elaborate more, until then, I'm marking this as invalid.

**Comment by NT690** [comment]
I mean the news article

**Comment by CoolAbhi1290** [comment]
What news article. Please elaborate in meaningful sentences.

**Comment by NT690** [comment]
When you click on the headlines in the news tab, it sends you to the web browser to read the full article. instead of that, you could have it view in-app

**Comment by CoolAbhi1290** [comment]
Oh, now you're making sense \:\)

**Comment by NT690** [comment]
sry
