### ISSUE TITLE
Long Profile Names Take Up The Entire Profile Pane

### ISSUE THREAD

**Issue by NT690** [BedrockLauncher/BedrockLauncher#61]
![2021-08-31 21_45_28-Minecraft Bedrock Launcher](https://user-images.githubusercontent.com/70166536/131613531-4d3f22d9-c242-4427-8698-766f2b5a030d.png)

**Comment by Rayth** [comment]
I'm not sure what can be done about that. That's general word wrapping for you. Why would you have a name that long though?

**Comment by NT690** [comment]
My gamertag i use for naming profiles is 1 number too long

**Comment by TheEpikBoi** [comment]
You can rename your profile to something else. Like remove the underscore is there is any and write something like this: TheEpikBoi . And your in-game gamertag will always remain same no matter what you make your launcher profile

**Comment by TheEpikBoi** [comment]
You can rename your profile to something else. Like remove the underscore is there is any and write something like this: TheEpikBoi . And your in-game gamertag will always remain same no matter what you make your launcher profile

**Comment by NT690** [comment]
I know its just preference

**Comment by CoolAbhi1290** [comment]
I don't see what can be done about it. The wraps into multiple lines, and that seems to be fine. It also clips it when it gets too big. I'm closing this for now. If you can explain what behavior you expected, message in this thread and I'll reopen the issue if the reason is valid.

**Comment by NT690** [comment]
Looking back the name goes over the "Profile" text (circled in red)
![2021-09-01 12_09_48-Minecraft Bedrock Launcher](https://user-images.githubusercontent.com/70166536/131729837-b261ca0b-3f33-4ac2-90c2-d860ed2f93f0.png)

**Comment by CoolAbhi1290** [comment]
Oh sorry about that, my screen is a bit tiny right now \:\/

**Comment by NT690** [comment]
np
