### ISSUE TITLE
After downlaoding latest beta, extracting and launching the game, I keep getting the same error

### ISSUE THREAD

**Issue by MazeWave** [BedrockLauncher/BedrockLauncher#62]
![image](https://user-images.githubusercontent.com/25009364/131892416-224aaf92-a486-42ca-ad23-a7209a4a0e10.png)
***'The object reference is not defined to an instance of an object'***

I saw the mojang's studio logo appear and the game crash after this. After closing the error context menu, bedrock launcher close itself. I f there is any way to get logs for more details.

**Comment by PavelDobCZ23** [comment]
I see you are using French langauge. Make sure directory path to the installation has no special characters like `é` `à` etc.

**Comment by NT690** [comment]
i think this issue is related to #53

**Comment by CoolAbhi1290** [comment]
Duplicate of #53

**Comment by NT690** [comment]
oh i was right lol

**Comment by MazeWave** [comment]
The problem is that Bedrock Launcher isn't installed as a portable launcher but in the default location (Program File x86)

**Comment by PavelDobCZ23** [comment]
> The problem is that Bedrock Launcher isn't installed as a portable launcher but in the default location (Program File x86)

1. Program Files Directory **isn't** a problem. I was talking about Minecraft data.
2. I used Bedrock Launcher as portable installation before.
