### ISSUE TITLE
You can edit the "Changes" notes in the Launcher tab of the News Page.

### ISSUE THREAD

**Issue by NT690** [BedrockLauncher/BedrockLauncher#69]
https://user-images.githubusercontent.com/70166536/133186910-bdfa7510-e5c5-4ca5-aa75-63cb2eff9137.mp4

**Comment by TresAbhi** [comment]
Woah

**Comment by TresAbhi** [comment]
What made you go "Yeah, I should try to type some text into the news page today!"?

**Comment by NT690** [comment]
I saw the text caret so I assumed you could do something to the notes

**Comment by TresAbhi** [comment]
It's been eons since I heard someone say text caret

**Comment by NT690** [comment]
~~It makes me sound smart~~ I've heard the name and it sounds better than "text cursor"

**Comment by TresAbhi** [comment]
> It makes me sound smart
it does

**Comment by NT690** [comment]
seems fixed so gonna close
