### ISSUE TITLE
Error when installing/updating to launcher beta

### ISSUE THREAD

**Issue by maicol07** [BedrockLauncher/BedrockLauncher#71]
![](https://user-images.githubusercontent.com/9463142/133805083-e50ab954-b721-45ec-8f54-b766c2efd6e4.png)

**Comment by TresAbhi** [comment]
**2 things:**
1. It would be more helpful if you provide the full log (preferably in English)
2. This is probably a problem of the [installer](https://github.com/BedrockLauncher/BedrockLauncher.Installer)

CarJem, you handle this one, IDK if I should migrate this one to the installer

**Comment by TresAbhi** [comment]
Closing for now, too little info

**Comment by maicol07** [comment]
> Closing for now, too little info

What do you want? I don't know if the launcher has a log

**Comment by TresAbhi** [comment]
We need the log, and if possible, in English. Plus, a quick summary of how the error happened and how it can be reproduced is needed.
