### ISSUE TITLE
Framework `Microsoft.Services.Store.Engagement` is missing

### ISSUE THREAD

**Issue by SearMr-cool** [BedrockLauncher/BedrockLauncher#73]
Error log:

```
Application Starting...
Application Pre-Initalization Finished!
Checking for updates
Current tag: 0.0.2.1
Latest tag: 0.0.2.1
Registering package
Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.17.3004.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.Services.Store.Engagement" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 10.0.1610.0, along with this package to install. The frameworks with name "Microsoft.Services.Store.Engagement" currently installed are: {}
App re-register failed:
System.Exception: Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.17.3004.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.Services.Store.Engagement" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 10.0.1610.0, along with this package to install. The frameworks with name "Microsoft.Services.Store.Engagement" currently installed are: {}
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<DeploymentProgressWrapper>d__28.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 596
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<ReRegisterPackage>d__27.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 562
```

**Comment by NT690** [comment]
Unrelated to the topic, but how do you get the 0.0.2.7 version? I'm on 0.0.2.6 and the releases tab isn't showing 0.0.2.7.

**Comment by TresAbhi** [comment]
Weird... It's supposed to exist...

Lemme remove that

**Comment by NT690** [comment]
Not the answer I expected.

**Comment by SearMr-cool** [comment]
I have done some messing around on my computer but the launcher still worked fine but it still could be causing this issue, just letting you know

**Comment by SearMr-cool** [comment]
update: I installed minecraft from the microsoft store and I am able to launch minecraft from the launcher

**Comment by KanimeXP** [comment]
I also have this problem. Can it be fixed?

**Comment by KanimeXP** [comment]
Or should I download minecraft from the store and it will work for me?

**Comment by Rayth** [comment]
try it. quite often downloading from store then uninstalling will allow the launcher to work but i think that's a separate issue from this.

**Comment by KanimeXP** [comment]
ok i try

**Comment by KanimeXP** [comment]
still same

**Comment by KanimeXP** [comment]
Not working.

**Comment by Rayth** [comment]
you'll just have to use the microsoft store version then until we get a fix. alot of work is going on atm with the launcher

**Comment by KanimeXP** [comment]
ok.Will play MCPE because I have pocketmine server :D

**Comment by Rayth** [comment]
You realise MCPE is the exact same thing? Bedrock covers windows 10, android, ios, all other mobile devices, xbox, switch, playstation

**Comment by KanimeXP** [comment]
They also have a similar interface.

**Comment by KanimeXP** [comment]
Still no fix :/

**Comment by Rayth** [comment]
You only posted yesterday. There hasn't been an update to this launcher in a while and the next update is big. may take a while

**Comment by KanimeXP** [comment]
Dufam ze to update opravi tento problem :D

**Comment by KanimeXP** [comment]
I hope this update fixes this problem: D

**Comment by KanimeXP** [comment]
I'm thinking of a future update.

**Comment by KanimeXP** [comment]
Interestingly, version 0.15.0.0 and older do not have this problem. They just turn on and then turn off immediately.

**Comment by KanimeXP** [comment]
They do not display any error message alert.

**Comment by Rayth** [comment]
thats because a lot of the error logging got added later

**Comment by KanimeXP** [comment]
But why it will display the Mojang logo. But not in the new versions.

**Comment by KanimeXP** [comment]
I read the logs. And found out. The app re-register succeeded at 0.15.0.0 and below

**Comment by KanimeXP** [comment]
Uwup Handler does not work the oldest.

**Comment by NT690** [comment]
I would highly suggest using MCMrArm's Version Switcher ([here](https://github.com/MCMrARM/mc-w10-version-launcher/releases/tag/0.3.0)) as a temporary workaround if you still want to play windows MC.

**Comment by KanimeXP** [comment]
MCMrArm's .I got same problem

**Comment by KanimeXP** [comment]
But I try again.

**Comment by Rayth** [comment]
the store engagement problem is specific to your computer. different launchers wont fix it. A previous comment stated that installing minecraft from the microsoft store will allow you to launch it from the launcher.

**Comment by KanimeXP** [comment]
I have not purchased minecraft. A minecraft trial is not available in the Microsoft store.

**Comment by KanimeXP** [comment]
So I can't play it: /

**Comment by KanimeXP** [comment]
Yes I found it!!
Minecraft trial !

**Comment by KanimeXP** [comment]
Is it enough if I only install Minecraft trial from the microsoft store?

**Comment by Rayth** [comment]
..you need to own minecraft to use this launcher. this is not a pirate program

https://bedrocklauncher.github.io/faq

**Comment by KanimeXP** [comment]
thanks It works

**Comment by KanimeXP** [comment]
I'm fine. Do you just know where the worlds are stored?

**Comment by KanimeXP** [comment]
I want to add my own worlds. And edit them

**Comment by TresAbhi** [comment]
> I'm fine. Do you just know where the worlds are stored?

`%appdata%`/.minecraft_bedrock`

Also, please reduce the number of messages. Try to keep your thoughts in one message at a time.

**Comment by Rayth** [comment]
> > I'm fine. Do you just know where the worlds are stored?
> 
> `%appdata%`/.minecraft_bedrock`
> 
> Also, please reduce the number of messages. Try to keep your thoughts in one message at a time.

It's actually:
`%localappdata%\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftWorlds` by default.

**Comment by TresAbhi** [comment]
@Rayth That's for the version installed through the Microsoft Store. Bedrock Launcher's data is in `%appdata/.minecraft_bedrock`. He's asking for the launcher's location.

**Comment by gabrielitook** [comment]
necesito ayuda

**Comment by gabrielitook** [comment]
Windows no puede instalar el paquete Microsoft.MinecraftWindowsBeta_1.18.3031.0_x64__8wekyb3d8bbwe porque depende de un marco que no se encontró. Proporcione el marco "Microsoft.Services.Store.Engagement" publicado por "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", con arquitectura de procesador neutra o x64 y versión mínima 10.0.1610.0, junto con este paquete para instalarlo. Los marcos con el nombre "Microsoft.Services.Store.Engagement" instalados actualmente son: {Microsoft.Services.Store.Engagement_10.0.18101.0_x64__8wekyb3d8bbwe Microsoft.Services.Store.Engagement_10.0.18101.0_x86__8wekyb3d8bbwe}
   en BedrockLauncher.ViewModels.GameManager.<RegisterPackage>d__27.MoveNext() en D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:línea 549
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en BedrockLauncher.ViewModels.GameManager.<Launch>d__19.MoveNext() en D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:línea 277

**Comment by gabrielitook** [comment]
algo asi me aparece

**Comment by gabrielitook** [comment]
no ce que significa :(

**Comment by TresAbhi** [comment]
@gabrielitook

Traducido por Traductor de Google

Tuve que empalmar bastantes respuestas ya que no aportaron nada al problema. Su bitácora, sin embargo, persiste.

--

Translated by Google Translate

I had to splice quite a few replies as they did not contribute anything to the issue. Your log, however, presists.

**Comment by Fabrico84** [comment]
This does not have a solution yet, right?

**Comment by Rayth** [comment]
> Does this have a fix yet? It's closed but is still a problem for me.

Are you on the latest version? Hasn't been reported recently.

**Comment by EnderMaster77** [comment]
> Are you on the latest version? Hasn't been reported recently.

Yeah, I think so. 

Heres the log:
[Log_2022-10-19_16-36-45.log](https://github.com/BedrockLauncher/BedrockLauncher/files/9825028/Log_2022-10-19_16-36-45.log)

**Comment by Rayth** [comment]
@CarJem can you take a look at this one? It says it needs the framework for microsoft.store.engagement, but also says that it's installed

**Comment by Rayth** [comment]
Resolved. Install .NET Desktop runtime

**Comment by MineTurtlee** [comment]
Uh. I have a solution if it is still not working.
As if .NET is installed but the error still persists then you need to use the command in PS 
Find it here:
![image](https://github.com/BedrockLauncher/BedrockLauncher/assets/97010924/e0b39e8d-d8db-42c0-bf3b-ee528222dbda)
Stumble through your C:\ (as i dualboot so it is D:\)
Find the Engagement
Depending on your arch, click the equivalent folder.
Go to Device portal (for example, localhost:50080)
Extract everything from appx
select manifest
install!
(done using revios)
