### ISSUE TITLE
add a server client download function in the create new installation tab

### ISSUE THREAD

**Issue by burtvadr** [BedrockLauncher/BedrockLauncher#78]
add a server client download function in the create new installation tab, using the link provided by mojang https://minecraft.azureedge.net/bin-win/bedrock-server-1.17.31.01.zip : changing the version of link will download the desired version, ex: https://minecraft.azureedge.net/bin-win/bedrock-server-X.XX.XX.XX.zip

![image](https://user-images.githubusercontent.com/67408916/134740425-694d0949-4813-4ec9-9369-d3f9569eba39.png)
![image](https://user-images.githubusercontent.com/67408916/134740553-992f5da3-c094-49c3-9be3-4ab403ea6a3a.png)

**Comment by Rayth** [comment]
Personally I don't think this would be a good feature, unless a server management system was also coded into the launcher (similar to foxy's mcbeplay system). Most people won't know what to do with a BDS download and could end up expecting it to be something entirely different.

**Comment by burtvadr** [comment]
note: there are no server clients for beta versions

**Comment by burtvadr** [comment]
> Personally I don't think this would be a good feature, unless a server management system was also coded into the launcher (similar to foxy's mcbeplay system). Most people won't know what to do with a BDS download and could end up expecting it to be something entirely different.

you're right, but I personally think it would be a good addition for the convenience of just one click, even if the function is not useful for everyone the practicality pays off

**Comment by Andrei12333** [comment]
Theres a link to where it should rediract to https://www.minecraft.net/en-us/download/server/bedrock

**Comment by Xd-pro** [comment]
> Theres a link to where it should rediract to https://www.minecraft.net/en-us/download/server/bedrock

This isn't a good idea because that only works for the latest version of the server software even when you use it on an old version of Minecraft.
