### ISSUE TITLE
`CefSharp.Core.Runtime.dll` not found

### ISSUE THREAD

**Issue by ghost** [BedrockLauncher/BedrockLauncher#84]
I tried using the launcher but an error came that looks like this :

![The error image](https://user-images.githubusercontent.com/86378749/137602501-23a84729-a2f4-4da1-96c2-6f6e8d5331b2.png)

Rough translation by @NT690:
```
"Unhandled exception occurred: The CefSharp.Core.Runtime.dll file or assembly, or a dependency on it, was not found. The specified module was not found"
```

**Comment by TresAbhi** [comment]
Just for convince, can you translate that?

**Comment by NT690** [comment]
"Unhandled exception occurred: The CefSharp.Core.Runtime.dll file or assembly, or a dependency on it, was not found. The specified module was not found" is roughly what it translates to

**Comment by ImNathanPlayz** [comment]
try install the old public beta

**Comment by KingTino104** [comment]
can you find a fix

**Comment by Rayth** [comment]
Try installing whichever one of these matches your OS build:
https://docs.microsoft.com/en-GB/cpp/windows/latest-supported-vc-redist?view=msvc-170

This appears to be an error on your pc not the application.

**Comment by KingTino104** [comment]
> 

Hey, i already have the x64 and x86 thingy.

**Comment by Metacinnabar** [comment]
Would be good to add Redist to the required software part of the documentation!

**Comment by Rayth** [comment]
> Would be good to add Redist to the required software part of the documentation!

Why are you commenting on closed issues?

https://github.com/BedrockLauncher/BedrockLauncher/releases/tag/2022.7.4.195

This isn't even a problem anymore. Cefsharp reliance was removed.
