### ISSUE TITLE
Minecraft crashes at its launch with no launcher anomaly

### ISSUE THREAD

**Issue by potatowtf** [BedrockLauncher/BedrockLauncher#88]
Every time I try to start any version other than the most recent one, my game crashes.

[**Video available**](https://user-images.githubusercontent.com/92950685/138356129-2d3116ea-327b-4f35-b302-d099ea5edb64.mp4)

Error log:
```
Application Starting...
Application Pre-Initalization Finished!
Checking for updates
Current tag: 0.0.2.1
Latest tag: 0.0.2.1
Removing package: Microsoft.MinecraftUWP_1.14.105.0_x64__8wekyb3d8bbwe
Package is in development mode
Deployment progress: Processing 0%
Deployment progress: Processing 100%
Deployment done: Completed
Removal of package done: Microsoft.MinecraftUWP_1.14.105.0_x64__8wekyb3d8bbwe
Registering package
Deployment progress: Processing 1%
Deployment progress: Processing 2%
Deployment progress: Processing 49%
Deployment progress: Processing 51%
Deployment progress: Processing 98%
Deployment progress: Processing 98%
Deployment progress: Processing 100%
Deployment done: Completed
App re-register done!
App launch finished!
```

**Comment by TresAbhi** [comment]
@potatowtf Yes, I'm here. I'm a human too lol, I don't stay on GitHub 24/7. The log can be found in the launcher installation directory (generally in `C:\Program Files` or `C:\Program Files (x86)`.

**Comment by potatowtf** [comment]
The log file says this:
Application Starting...
Application Pre-Initalization Finished!
Checking for updates
Current tag: 0.0.2.1
Latest tag: 0.0.2.1
Removing package: Microsoft.MinecraftUWP_1.14.105.0_x64__8wekyb3d8bbwe
Package is in development mode
Deployment progress: Processing 0%
Deployment progress: Processing 100%
Deployment done: Completed
Removal of package done: Microsoft.MinecraftUWP_1.14.105.0_x64__8wekyb3d8bbwe
Registering package
Deployment progress: Processing 1%
Deployment progress: Processing 2%
Deployment progress: Processing 49%
Deployment progress: Processing 51%
Deployment progress: Processing 98%
Deployment progress: Processing 98%
Deployment progress: Processing 100%
Deployment done: Completed
App re-register done!
App launch finished!
i'm pretty sure i did something wrong lol

**Comment by potatowtf** [comment]
maybe checked the wrong place?

**Comment by Rayth** [comment]
i noticed it froze on 45%. try this https://www.youtube.com/watch?v=IzUFfKqBDrs
