### ISSUE TITLE
Automatically delete old latest beta/latest versions

### ISSUE THREAD

**Issue by Narlotl** [BedrockLauncher/BedrockLauncher#93]
When downloading the latest version using the latest version or latest beta option, the old betas remain on the computer, taking up lots of space. 
It would be nice if these got deleted after updating to a new version.

**Comment by john-tettis** [comment]
Hey I could resolve this issue!

**Comment by NT690** [comment]
Open a pull request (I think correct me if I'm wrong @TresAbhi )

**Comment by TresAbhi** [comment]
> @john-tettis  Consider opening a pull request (I think, correct me if I'm wrong @TresAbhi )

What? Who's John? Why was I pinged? What does this have to do with a PR?

**Comment by Rayth** [comment]
> > @john-tettis  Consider opening a pull request (I think, correct me if I'm wrong @TresAbhi )
> 
> What? Who's John? Why was I pinged? What does this have to do with a PR?

Because John is saying he could fix this issue so he'd have to create a pull request when done so which Car would then need to review
