### ISSUE TITLE
Beta won't launch

### ISSUE THREAD

**Issue by dremonq** [BedrockLauncher/BedrockLauncher#94]
Error -2146233088

**Comment by TresAbhi** [comment]
Can you please provide a log?

**Comment by NT690** [comment]
This could possibly be related to #39. Try checking that out.

**Comment by Rayth** [comment]
> This could possibly be related to #39. Try checking that out.

Without the log requested we can't make any assumption. Closing this issue due to no response

**Comment by TresAbhi** [comment]
@Rayth, give @dremonq enough time (7 days minimum to respond).

**Comment by derspyy** [comment]
I might add that I'm experiencing the same issue.

https://mclo.gs/b88Itf0

**Comment by TresAbhi** [comment]
@derspyy, that's #81

**Comment by dremonq** [comment]
> @Rayth, give @dremonq enough time (7 days minimum to respond).

hm

**Comment by TresAbhi** [comment]
@dremonq, please provide a more constructive reply

**Comment by NT690** [comment]
I think this should be closed as it has been 2 weeks since the last reply.

**Comment by TresAbhi** [comment]
I totally forgot about this lol.
