### ISSUE TITLE
The App Wont Open it only Open Error

### ISSUE THREAD

**Issue by CreepKing8288** [BedrockLauncher/BedrockLauncher#95]
![error](https://user-images.githubusercontent.com/93425203/139525899-6c3cc559-0854-4142-a0c7-b5227fc3f2f2.PNG)
[Log.txt](https://github.com/BedrockLauncher/BedrockLauncher/files/7446106/Log.txt)

**Comment by Rayth** [comment]
We need a bit more information since no one else is reporting anything similar. Did you run it in admin mode? windows version? launcher version? Have you tried re-installing the launcher?

**Comment by CreepKing8288** [comment]
I try re-installing it and Use it on admin mode

**Comment by CreepKing8288** [comment]
I have windows 10

**Comment by NT690** [comment]
I would either suggest adding a different label or closing this issue as it seems very inactive.

**Comment by TresAbhi** [comment]
@CreepKing8288 Also, a log would be helpful

**Comment by CreepKing8288** [comment]
theres a log

**Comment by CreepKing8288** [comment]
under the screenshot

**Comment by CreepKing8288** [comment]
[Log.txt](https://github.com/BedrockLauncher/BedrockLauncher/files/7641340/Log.txt)

**Comment by CreepKing8288** [comment]
re send

**Comment by Rayth** [comment]
@CreepKing8288 can you confirm whether you are using the release version or the beta version of the launcher? I've recently used both and not getting this error

**Comment by NT690** [comment]
Close Issue? (18 days since last reply)

**Comment by CreepKing8288** [comment]
> @CreepKing8288 can you confirm whether you are using the release version or the beta version of the launcher? I've recently used both and not getting this error

Release

**Comment by CreepKing8288** [comment]
I'm so sorry I couldn't open sometimes
